### ISSUE TITLE
Add plain Sass examples to README.md

### ISSUE THREAD

**Issue by sparkiegeek** [vanilla-framework/vanilla-framework#1015]
I'd like to use Vanilla in a project that doesn't have a Gulp workflow. It would be great if there were examples of how to compile Sass that includes Vanilla without having to reverse-engineer the Gulp configuration (i.e. assume the reader has just installed Sass CLI and wants to use Vanilla)

**Comment by yaili** [comment]
@barrymcgee is this ready to be worked on? can be moved to backlog?

**Comment by anthonydillon** [comment]
The new get started page has a section on compiling Vanilla using node-sass
without gulp.

https://github.com/vanilla-framework/vanilla-framework/blob/develop/docs/en/index.md#install-via-npm

**Comment by yaili** [comment]
@anthonydillon so it's done?

**Comment by anthonydillon** [comment]
Yeah in code and will be release today.
