### ISSUE TITLE
Broken link mixin?

### ISSUE THREAD

**Issue by sparkiegeek** [vanilla-framework/vanilla-framework#1016]
Using vanilla-framework 1.1.12 with a trivial .scss file (`@import '../../../../node_modules/vanilla-framework/scss/build';`) I get the following error trying to compile it using `sass` command line (3.4.21 (Selective Steve)):

`sass --no-cache --style=extended canonical/landscape/static/root/signup-vanilla.scss canonical/landscape/static/root/signup-vanilla.css`

> Error: Mixins may not be defined within control directives or other mixins.
>        on line 4 of /home/acollard/src/landscape/vanilla-spike/node_modules/vanilla-framework/scss/_patterns_links.scss
>        from line 43 of /home/acollard/src/landscape/vanilla-spike/node_modules/vanilla-framework/scss/_vanilla.scss
>        from line 2 of /home/acollard/src/landscape/vanilla-spike/node_modules/vanilla-framework/scss/build.scss
>        from line 1 of /home/acollard/src/landscape/vanilla-spike/canonical/landscape/static/root/signup-vanilla.scss
>  Use --trace for `backtrace.`

**Comment by sparkiegeek** [comment]
This appears to be a regression between 1.1.7 and 1.1.8, if I use 1.1.7 then it works just fine.

**Comment by sparkiegeek** [comment]
Ah, and appears to be working "by accident" using Gulp. See https://github.com/sass/node-sass/issues/1459

**Comment by barrymcgee** [comment]
@sparkiegeek Thank you for raising this - I've submitted a PR and will mint a release as soon as this is merged.

**Comment by sparkiegeek** [comment]
@barrymcgee awesome.

Where do I track the work that will stop this happening again? e.g. adding `sass` CLI to your CI or whatever else

**Comment by barrymcgee** [comment]
@sparkiegeek 1.1.13 is now released.

I've raised a [separate issue ](https://github.com/vanilla-framework/vanilla-framework/issues/1018) to ensure something like this doesn't slip through again.
