### ISSUE TITLE
Floats on checkbox and radio styles

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1027]
Default form checkbox and radio styles have `float: left`. This causes radio buttons to be misaligned with text. For example: 
https://codepen.io/anthonydillon/pen/KmVMWM

Is there a reason for the float? It would be nice to fix the spacing too.

**Comment by barrymcgee** [comment]
@kwm14 This spacing was mentioned in today's WG as well. There's no specific mention of radio buttons in the specs, is there? https://github.com/ubuntudesign/vanilla-design/blob/master/Forms/forms.md

**Comment by kwm14** [comment]
@barrymcgee having a look through the vanilla-design repo there is no mention of checkbox and radio buttons. 

In our Vanilla documentation we have:

**Patterns/Forms**
https://docs.vanillaframework.io/en/patterns/forms

**Base/Forms**
https://docs.vanillaframework.io/en/base/forms#input-elements

Base/Forms has checkbox and radio button options and looking at the example the margin between icon and text looks quite big using `1rem` of margin. I'd propose to use `0.5rem` to close that gap.

**Comment by kwm14** [comment]
@barrymcgee I'm happy to do a design spec for it, but would like to push it to the next iteration as within **Base/Forms** we have our Dropdown list which was a topic of conversation also in our WG yesterday.

**Comment by barrymcgee** [comment]
@kwm14 Ok cool, do you want to reassign this issue to next Iteration?

**Comment by kwm14** [comment]
@barrymcgee yes I'll move it back to Triaged and pick up next iteration with some other work.

**Comment by kwm14** [comment]
Design spec added [here](https://github.com/ubuntudesign/vanilla-design/tree/master/Forms). Closing this issue and will create a new one for work to be added/updated into documentation.
