### ISSUE TITLE
Update breadcrumbs link style based on new design spec

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1034]
1. Go to a page that uses Vanilla breadcrumbs.
2. Try to tell which of the breadcrumbs are links.

Currently, breadcrumbs that are links look quite similar to breadcrumbs that are not. The only difference is in font weight.

Sometimes this difference in weight is fairly obvious, such as in Firefox on Ubuntu:
![vanilla breadcrumbs ubuntu](https://cloud.githubusercontent.com/assets/19801137/25342737/c6f3b272-2904-11e7-8e8a-a14b6afa22f8.png)

But sometimes it is barely noticable, such as in Safari on iOS:
![vanilla breadcrumbs safari](https://cloud.githubusercontent.com/assets/19801137/25342988/9f30896c-2905-11e7-8f26-949a80c6a95e.jpg)

And sometimes, as on [build.snapcraft.io](https://build.snapcraft.io/) build pages, all the breadcrumbs are links. So it wouldn’t matter what weight is used, the breadcrumbs would still look _more similar_ to nearby non-link text than they do to nearby link text:
![vanilla breadcrumbs](https://cloud.githubusercontent.com/assets/19801137/25343084/e52910a6-2905-11e7-8374-301ca7d07782.png)

(Even if repeating the heading at the end of the breadcrumbs was a solution to this problem, that would be using text to solve a problem that could be more concisely solved with visual design.)

I understand that [in navigation menus and other closely bordered areas, it isn’t necessary for links to be coloured and/or underlined](https://www.nngroup.com/articles/guidelines-for-visualizing-links/): the context makes it clear. But breadcrumbs often are not in an area like that.

Linked breadcrumbs become coloured and underlined on hover, but on touch devices there is no hover.

**Pattern proposal:** Unless they are inside a [strip](https://docs.vanillaframework.io/en/patterns/strip), breadcrumb links should be the same colour as normal links.

[Resolving this is part of [build.snapcraft.io issue #653](https://github.com/canonical-ols/build.snapcraft.io/issues/653).]

**Comment by yaili** [comment]
@matthewpaulthomas Is your proposal something like this?

<img width="598" alt="breadcrumb-standard-links" src="https://cloud.githubusercontent.com/assets/223966/25381491/e630e068-29ab-11e7-9aaf-6777629f2db8.png">

@kwm14 @spencerbygraves Thoughts?

**Comment by spencerbygraves** [comment]
I don't mind the proposed pattern of having blue links unless they are in a strip. Alternatively, we could design the breadcrumb pattern so that it's always in a strip, or has a line above and below, or similar.

If we go for blue, can this be an exception to the strong style, which we keep for titles elsewhere?

**Comment by matthewpaulthomas** [comment]
@yaili Yes, that’s exactly what I had in mind, thank you. (Sorry I forgot to attach a sketch/mockup myself.)

@spencerbygraves Requiring breadcrumbs to be inside a strip would make it more obvious that they were links, but it wouldn’t look so good in two cases:
- Where, as in my iPhone screenshot above, the breadcrumbs sometimes wrap to multiple lines. It would look more awkward for a coloured block to vary in height, from page to page, than it does for text-only breadcrumbs to vary in their number of lines.
- Where, as in the build.snapcraft.io example above, the `<h1>` avoids redundant text by serving as the last item in the breadcrumb chain. Logically this would mean the heading should go inside the strip too. This would make the page look much boxier. (For example, in build.snapcraft.io, it would be competing visually with the notification box you can see immediately above).

For those reasons I’d prefer just to colour the links.

**Comment by spencerbygraves** [comment]
Ok, thanks @matthewpaulthomas. Let's try blue.

**Comment by yaili** [comment]
Updated design spec: https://github.com/ubuntudesign/vanilla-design/tree/master/Breadcrumbs

The PNG doesn't seem to have updated, but it can be seen in the commit. Maybe it's just a cache thing.
