### ISSUE TITLE
Link to Grid page in strip documentation

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1035]
From [the “Strip” reference](https://docs.vanillaframework.io/en/patterns/strip): “The strip pattern provides a full width strip container in which to wrap a row. A strip can have light (`.p-strip--light`) or dark (`.p-strip--dark`) grey background. A `.p-strip` container should always be the parent of a `.row` and never the other way around.”

Okay, but what is this “row” thing? Is it a table row? The code example suggests not. So what else?

**Comment by yaili** [comment]
@barrymcgee could you clarify? Should there also be a Related section on this page that links to Grid?

**Comment by barrymcgee** [comment]
@yaili Yes, and probably we should add brackets after .row .. (from the [link] Grid)

**Comment by yaili** [comment]
@matthewpaulthomas do you think that linking to the Grid page where it explains row would suffice?

**Comment by matthewpaulthomas** [comment]
@yaili Yes, rows are described very early in that page, so I think that would be fine. (Even clearer would be if that first “rows” on the Grid page was a `<dfn>` element.)

**Comment by matthewpaulthomas** [comment]
(Follow-up: in [docs.vanillaframework.io#108](https://github.com/ubuntudesign/docs.vanillaframework.io/issues/108) I’ve proposed that “Strip” come immediately after “Grid” in a “Global layout” category.)
