### ISSUE TITLE
Documentation breadcrumbs all look like links on hover, but none are

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1036]
1\. Go to [the Breadcrumbs reference page](https://docs.vanillaframework.io/en/patterns/breadcrumbs).
2\. If it is not already, resize the window narrow enough that the contents menu is replaced by breadcrumbs.
3\. If you’re using a pointing device, hover over each of the breadcrumbs.
4\. Click each of the breadcrumbs.

What happens:
3\. Each breadcrumb changes to the link colour.
4\. Nothing.

![vanilla breadcrumbs docs](https://cloud.githubusercontent.com/assets/19801137/25345647/7cc5ea40-290d-11e7-8f97-ca8ba41557eb.png)

What should happen:
3\. If something isn’t a link, it shouldn’t be styled as if it is.
4\. The “Patterns” breadcrumb should actually be a link.

(3) seems to be caused because the link styling relies on the use of a `.p-breadcrumbs__link` class (“`.p-breadcrumbs__link, .p-breadcrumbs__link:visited`”), instead of relying on the existence of an actual link (“`.p-breadcrumbs :link, .p-breadcrumbs :link:visited`”).

(4) was probably caused because link breadcrumbs and non-link breadcrumbs look too similar (#1034), so whoever implemented the breadcrumbs on this site didn’t notice that they weren‘t links.

**Comment by yaili** [comment]
I'm moving this issue to the Vanilla Docs theme repo, as it's an issue across the entire theme. Thanks for spotting this.

**Comment by yaili** [comment]
This issue was moved to vanilla-framework/vanilla-docs-theme#37
