### ISSUE TITLE
The default margin around the nav logo is too much

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#1037]
## Current bug

The element `.p-navigation__logo` does not account or constrain the size of any given logo nor is any guidance in docs given.

As a result, my nav bar immediately looked broken when I dropped my logo in and I had to manually override the margin: 

```css
.p-navigation__logo {
    margin: .75rem;
}
```

## Expected result

- Framework should limit size of logo

OR

- Framework should position logo in middle of navbar regardless of size

OR

- Docs should advise on size of logo needed

**Comment by yaili** [comment]
@barrymcgee is this related to https://github.com/vanilla-framework/vanilla-framework/issues/1083 and https://github.com/ubuntudesign/vanilla-store-theme-design/issues/10 ?

**Comment by barrymcgee** [comment]
@yaili Yes.

**Comment by yaili** [comment]
This doesn't sound like it's ready to be worked on… have there been any decisions on this? There's no design guidance yet.
