### ISSUE TITLE
At 768px - the nav combines small/large styling

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#1038]
## Bug

1. Click to navigation example on running `gulp jekyll`
2. Reduce screen width to exactly 768px
3. Observe behavior

![screen shot 2017-04-25 at 08 36 59](https://cloud.githubusercontent.com/assets/505570/25373709/9d9f1a7c-2992-11e7-8746-8e58fc0310b3.png)

## Expected result

There should be a clean transition between small and large screen navigation styles.

**Comment by yaili** [comment]
@anthonydillon was this closed, or still in develop?

**Comment by anthonydillon** [comment]
Yes it was with the new nav work.
