### ISSUE TITLE
<small> font size too small at small viewport

### ISSUE THREAD

**Issue by deadlight** [vanilla-framework/vanilla-framework#1046]
## Issue

The `<small>` tag is [documented in the base styles](https://docs.vanillaframework.io/en/base/typography#small-text) as being a fixed font size of 13px. In the small viewport, this is not the case - it renders as 12.1875px.

I think that a fixed size at all viewports is correct (for example, the "small print" in ubuntu.com's footer is 13px at all viewports).

## Proposed solution

The `<small>` tag should be rendered as 13px at all viewports.

**Comment by yaili** [comment]
@spencerbygraves shall we say 14px for the smallest text?
