### ISSUE TITLE
Create color-accent and color-accent-background

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#1054]

**Comment by yaili** [comment]
Suggestion discussed at working group:
- to have a variable color-accent which is different from color-brand
- color-accent can be used in brochure theme to make some elements orange, for e.g. contextual footer border, list ticks, tabs highlights
- color-accent is currently a colour variable in the brochure theme that is used to define the background colour of the strip-accent - it is currently aubergine, but…
- we shouldn't have orange background strips in brochure theme, or any site, so…
- if this change is made, then we need to rename the existing color-accent in the brochure theme

Did I miss anything?

**Comment by anthonydillon** [comment]
How about using `$color-accent` for styling small elements like the tick lists, tab highlights, etc. And, create a new setting called `$color-accent-background` which can be applied to large elements like strips?

**Comment by yaili** [comment]
I think before we decided that it would be good to do an inventory of sites that would use the accent background. @spencerbygraves @kwm14 do you know any examples?

**Comment by yaili** [comment]
Notes from the working group:
- brand colour doesn't work for non-www.ubuntu.com
- color-accent-background and color-accent work for all sites
- color-accent will be the default for ticks
- color-accent and color-accent-background will be color-brand by default
- we need to take more detailed notes

**Comment by yaili** [comment]
This issue was moved to vanilla-framework/vanilla-brochure-theme#77
