### ISSUE TITLE
Bower and gulp bump

### ISSUE THREAD

**Issue by richmccartney** [vanilla-framework/vanilla-framework#1059]
## Is this a proposal or an amendment?

- Proposal

## Context

- Should we consider adding bower as another package manger for Vanilla Framework? This can follow the same rules with ```npm``` when adding a bower package it will only pull the SCSS source files?

- Can we think about using gulp to bump our versioning as well? https://www.npmjs.com/package/gulp-bump

**Comment by anthonydillon** [comment]
Agreed this would increase the audience for Vanilla with little effort.

Note: Bump the version of bower by the release scripts.

**Comment by yaili** [comment]
@anthonydillon can you assign priority?

**Comment by anthonydillon** [comment]
Now that I have more experience with bower. We would need to commit the compiled CSS. This would cause confusion when code reviewing. Due to this I am not sure it's such a good idea. If someone knows a better bower workflow then please let me know.
