### ISSUE TITLE
Fixed/floating notification

### ISSUE THREAD

**Issue by deadlight** [vanilla-framework/vanilla-framework#1064]
In the implementation of the new cookie policy bar style we needed to create a version of the notification that is fixed in position at the bottom of the page and can be dismissed.

This is achieved by adding a "p-notification--floating" class.

I think this is a common enough use-case to have as a core part of vanilla.

![Example](https://cloud.githubusercontent.com/assets/118614/25741181/7f35f032-3181-11e7-9060-0a76df6e45ee.png)

**Comment by anthonydillon** [comment]
To be developed in brochure theme.

**Comment by yaili** [comment]
@anthonydillon should this be moved to brochure theme?

**Comment by anthonydillon** [comment]
This pattern modification is bespoke to the cookie policy. It should be handled locally by the canonical-cookie-policy project. Which it is currently.
