### ISSUE TITLE
Matrix left padding on first row item

### ISSUE THREAD

**Issue by grahambancroft** [vanilla-framework/vanilla-framework#1066]
## Process

1. Navigate to the matrix pattern - https://docs.vanillaframework.io/en/patterns/matrix

## Expected result

There should no left padding on the first item of each row

## Current result

There is left padding on the first item of each row

## Screenshot

![screen shot 2017-05-08 at 10 57 54](https://cloud.githubusercontent.com/assets/2152/25799576/667f9f26-33dd-11e7-8333-cd0fb63bf692.png)

**Comment by yaili** [comment]
For reference, here is the design spec: https://github.com/ubuntudesign/vanilla-design/tree/master/Matrix
