### ISSUE TITLE
Indented nested ordered list text to align with the number

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#1068]
Currently on ubuntu.com, there is custom style for indenting nested numbered lists:

https://cl.ly/173m2N3a1L1y

When converting to Vanilla v1, these lists flatten:

https://cl.ly/1Z0D0R1E3Q2a

**Comment by yaili** [comment]
Are you referring to the indentation of the text in ubuntu.com? That doesn't right. But the way Vanilla is doing it doesn't look right either:

- text inside list items should align left, not wrap around the bullet/number
- nested lists should be indented

I think we need to review this in Vanilla.

**Comment by Caleb-Ellis** [comment]
Closing as the issue has been resolved. Ordered and unordered list text are padded on the left so they don't wrap around the bullet/number.

![screenshot 3](https://user-images.githubusercontent.com/25733845/35288449-9dd522e2-005c-11e8-9b75-cab52dc2123e.png)
