### ISSUE TITLE
add .is-trisected and .is-quartered to lists

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-framework#1070]
## Is this a proposal or an amendment?

- Amendment, sort of

for `.p-list--divided` we have `.is-split`, which cuts a list into two... I think we need two more... for thirds adn quarters

``` sass
@mixin ubuntu-p-is-trisected {

  [class*='p-list'] {

    &.is-trisected {

      @media (min-width: $breakpoint-medium) {
        display: flex;
        flex-wrap: wrap;

        .p-list__item {
          width: calc(33.33% - .5rem);
          margin-right: .5rem;

          &:nth-child(3n+3) {
            margin-right: 0;
          }

          &:nth-last-child(0) {
            border-bottom: 0;
          }
        }
      }
    }
  }
}

@mixin ubuntu-p-is-quartered {

  [class*='p-list'] {

    &.is-quartered {

      @media (min-width: $breakpoint-medium) {
        display: flex;
        flex-wrap: wrap;

        .p-list__item {
          width: calc(25% - .5rem);
          margin-right: .5rem;

          &:nth-child(4n+4) {
            margin-right: 0;
          }

          &:nth-last-child(0) {
            border-bottom: 0;
          }
        }
      }
    }
  }
}
```

## Visual

.is-trisected

![image](https://cloud.githubusercontent.com/assets/441217/26058457/dbf97518-3975-11e7-88f4-20691ea937ca.png)

.is-quartered

![image](https://cloud.githubusercontent.com/assets/441217/26058410/b83abba0-3975-11e7-9c86-b0e41fb9feec.png)

## Context

see /download/alternate-downloads

## State

na

## Progressive enhancement

perhaps in large it is 1/3rds or 1/4rs but mobile to 1/2s then mobile full size

**Comment by yaili** [comment]
Notes from working group:
- We will keep this pattern in ubuntu.com until another site needs it, before it's promoted to brochure theme
- How can we make these site-only patterns visible? - create a page in the wiki: Patterns to watch out for - @anthonydillon will create this page now
- Having a page that shows all the site patterns - each site can have their own wiki page for this
- Use the Vanilla wiki page to list to all the other sites' patterns
