### ISSUE TITLE
Using stackoverflow for questions

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1071]
I would like to propose that we start asking questions on stackoverflow instead of on IRC to help publises Vanilla and acts as quick documentation.

**Comment by yaili** [comment]
@anthonydillon what's the priority level?

**Comment by anthonydillon** [comment]
@yaili low as it's just an experiment.

**Comment by kwm14** [comment]
Once the Vanilla community grows and more users adopt our framework we will experiment with this idea. Closing for now.
