### ISSUE TITLE
p-matrix__img should be max-width: 60px, not a calculation

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-framework#1072]
## Process

1. go to /download/alternative-dowloads
2. look at the Ubuntun Budgie logo
3. see that it is larger than the other logo

## Expected result

* images should always be 60px or 3.75rem

## Current result

* they change sized depending on the original logo size

## Screenshot

![image](https://cloud.githubusercontent.com/assets/441217/26062433/b14fc3fa-3982-11e7-8100-830dead67432.png)

should be

![image](https://cloud.githubusercontent.com/assets/441217/26062466/c3e8f342-3982-11e7-86bd-c0c9eb1c0d59.png)

**Comment by yaili** [comment]
Spec: https://github.com/ubuntudesign/vanilla-design/tree/master/Matrix

**Comment by yaili** [comment]
@anthonydillon you're assigned to this issue, did you work on it?

**Comment by anthonydillon** [comment]
No, I was assigned. It's free to be picked up.
