### ISSUE TITLE
Copy icon looks like a link icon

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1073]
# Pattern amendment

[The “Code snippet” pattern](https://docs.vanillaframework.io/en/patterns/code-snippet) uses a Copy icon that consists of a stylized chain with three links:

![vanilla - copy icon](https://cloud.githubusercontent.com/assets/19801137/26063646/7fad5ea8-3986-11e7-8f7a-d8ea2e5a0d0d.png)

This is confusing, because Copy icons seldom look like a chain, whereas that motif *is* commonly used for inserting hyperlinks.

![insert link icons](https://cloud.githubusercontent.com/assets/19801137/26063951/6ef33398-3987-11e7-890e-dbd89cb3ee5b.png)

It is much more common for [a “Copy” icon](https://www.google.co.uk/search?tbm=isch&q=copy&tbs=isz:i) to show two overlapping boxes or pages, or sometimes a clipboard.

Since we are likely to use two overlapping boxes to [convey “opens in a new window/tab”](https://github.com/canonical-ols/build.snapcraft.io/issues/765), I suggest that our Copy icon use a stylized clipboard.

**Comment by yaili** [comment]
@matthewpaulthomas do you know if there is an icon for this already designed for Suru? I assume you're saying something like this (see screenshot)?

<img width="357" alt="screen shot 2017-05-16 at 16 24 35" src="https://cloud.githubusercontent.com/assets/223966/26114042/37c90d16-3a54-11e7-8c65-8657c1845557.png">

**Comment by matthewpaulthomas** [comment]
@yaili [In the “Icons” folder on Dropbox](https://www.dropbox.com/search/work?path=%2FApps+and+Platform+Team%2F9.+Icons&qsid=35291599385114432032797348072670&query=copy) I can find (multiple copies of) one Copy icon:
![edit-copy](https://cloud.githubusercontent.com/assets/19801137/26116629/b6de6446-3a5b-11e7-8819-e97179b67349.png)
([SVG version](https://www.dropbox.com/search/work?path=%2FApps+and+Platform+Team%2F9.+Icons&preview=edit-copy.svg&qsid=35291599385114432032797348072670&query=copy))

However, this follows the “two overlapping boxes” motif that I questioned above as being easily confusable with “opens in a new window/tab”. So yes, I would prefer a clipboard-based icon like the GitHub one.

**Comment by matthewpaulthomas** [comment]
We didn’t discuss it at all, but Bartek has noticed [the same issue in build.snapcraft.io](https://github.com/canonical-ols/build.snapcraft.io/issues/779).

**Comment by yaili** [comment]
What about adapting the edit-paste icon, I found this in Dropbox in Suru Theme.

<img width="94" alt="screen shot 2017-05-19 at 11 15 15" src="https://cloud.githubusercontent.com/assets/223966/26243645/732cecb0-3c84-11e7-8da5-1aa97cb00de5.png">

**Comment by matthewpaulthomas** [comment]
Yes, [that looks very similar to many “Copy to Clipboard” icons](https://www.google.co.uk/search?tbm=isch&tbs=isz:i&q=copy+to+clipboard). It does raise the question of what the corresponding Paste icon would look like — but with the demise of Ubuntu Touch, I’m not aware of any apps we develop that have a Paste button anyway.

**Comment by yaili** [comment]
Notes from working group:
- We all agree that the current icon is not right
- Option: use text instead of icon?
- Icon: based on the edit-paste above, use the clipboard with an arrow pointing to it
- Design needed

**Comment by yaili** [comment]
This issue was moved to ubuntudesign/vanilla-design#24
