### ISSUE TITLE
Review vertical space between Headings and containers

### ISSUE THREAD

**Issue by joanasa89** [vanilla-framework/vanilla-framework#1077]
# 2. Pattern proposal
Problem:
There's no enough space between the heading and the container and between the container and the link.
## Visual
![vertical-spacing](https://cloud.githubusercontent.com/assets/21334617/26117211/aa961d1c-3a5d-11e7-86f5-77dd99360652.png)

Solution:
Propose utility class to add more margin to the element top and bottom.
## Visual
![more-margin](https://cloud.githubusercontent.com/assets/21334617/26117460/8de289e8-3a5e-11e7-9854-96200ea8631d.png)

## Is this a proposal or an amendment?
- Proposal

**Comment by barrymcgee** [comment]
Thanks, @joanasa89 - there's already an on-going unit of work to fix up vertical spacing across all typography here: https://github.com/vanilla-framework/vanilla-framework/issues/960

**Comment by yaili** [comment]
Design notes:
- Let's first wait for the new vertical rhythm to land
- If this doesn't fix the issue (which probably won't), we can try something else:
  - Add space between rows?
  - Add space between columns?
  - Utility class?
- We can discuss again when the time comes

**Comment by yaili** [comment]
Closing: duplicate of https://github.com/vanilla-framework/vanilla-framework/issues/1091
