### ISSUE TITLE
Code snippet - text over copy button

### ISSUE THREAD

**Issue by deadlight** [vanilla-framework/vanilla-framework#1078]
## Process

- Go to [https://docs.vanillaframework.io/en/patterns/code-snippet](https://docs.vanillaframework.io/en/patterns/code-snippet)
- Shrink the viewport until the code content overflows the element (I know that this is a very narrow viewport but content can be much longer)
- Hover over the "copy" button and see that the text appears over the button

## Expected result

The text should be under the button and not visible.

## Screenshot

![text-over-button](https://cloud.githubusercontent.com/assets/118614/26196124/d7a469a4-3bb5-11e7-9190-48e47892212f.png)

**Comment by yaili** [comment]
What browser are you using? I can't see this.

<img width="168" alt="screen shot 2017-05-19 at 09 16 55" src="https://cloud.githubusercontent.com/assets/223966/26239199/f27b6110-3c73-11e7-8afb-e65ee1383c98.png">

**Comment by yaili** [comment]
OK, I hadn't hovered. If I hover I see the bug.

**Comment by barrymcgee** [comment]
@deadlight This appears to be now already resolved on the `develop` branch - I've built a demo from develop here and cannot replicate: http://vanilla-framework-develop.demo.haus/vanilla-framework/examples/patterns/code-snippet/

Can you please verify and close this issue if you're satisfied?

**Comment by anthonydillon** [comment]
This has been fixed in the latest release.
