### ISSUE TITLE
On mobile, adjacent buttons are vertically stacked even when they could fit in one row

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1079]
According to @kwm14, on mobile screens, the Vanilla layout for a group of buttons stacks them vertically:

![add repos phone mockup cropped](https://cloud.githubusercontent.com/assets/19801137/26241988/ae650af2-3c7e-11e7-9563-a30970c95c5b.png)

This wastes space, and increases scrolling, when the button labels are short enough that there would be room for the buttons to fit alongside each other.

For Ubuntu Touch, [I specified that dialog buttons should be laid out horizontally](https://docs.google.com/document/d/19ZQrxQ-n-74n9v9aSwF9qs8IPYKDIp1l5bc43L9ohmg/edit#bookmark=id.dnuk48do9sh) whenever they would fit on one row, and stack vertically otherwise. Vanilla may not need the primary/secondary/cancel “slots” I specified, but it could use the same basic orientation.

![dialog-action-area wide](https://cloud.githubusercontent.com/assets/19801137/26242544/b29319d2-3c80-11e7-9182-21ad5a898d58.png) ![dialog-action-area narrow](https://cloud.githubusercontent.com/assets/19801137/26242556/ba2e0206-3c80-11e7-8116-9030d16ae24a.png)

**Proposal:** A group of buttons should be laid out horizontally when there is room for them to fit on one row, and stacked vertically otherwise.

**Comment by yaili** [comment]
I believe we added, or are in the process of adding, a utility which makes the buttons not go full width on mobile, as this is a common case. @deadlight can you confirm the status of this, it started because of the ubuntu.com footer?

**Comment by barrymcgee** [comment]
@deadlight Can you clarify above please?

**Comment by anthonydillon** [comment]
After an investigation, this is not something that is possible without JavaScript. There is no way of knowing when an element wraps and therefore cannot make it 100% width when it does. 

The best I could do it change the breakpoint that stacks buttons but that does not solve this issue:
https://codepen.io/anthonydillon/pen/NaZyyW

Therefore, setting to will not fix.

**Comment by matthewpaulthomas** [comment]
Vanilla’s accordion component already uses JavaScript. And as Vanilla gains more sophisticated form components, they will often need JavaScript too. So it seems odd that fixing this requiring JavaScript would be a reason not to fix it.

**Comment by anthonydillon** [comment]
The JavaScript for an accordion pattern is quiet simple. It's a click event
that toggles a class. The JavaScript to perform multiple button width
calculations and apply a class if greater is far more complex. Due buttons
sizes increasing when loading icons are displayed for example. This pattern
would also require a window resize listener to trigger the calculations
each time the browser is resized.

I was hoping for a flexbox solution for this but it is not possible.

We do official support JavaScript and are in the process of hiding it from
the documentation. Therefore I was hesident to add more patterns that
require JavaScript until we have a means of delivering the functionally to
the users.
