### ISSUE TITLE
Inconsistent navigation header height between Vanilla-using sites

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1083]
[The “Navigation” page](https://docs.vanillaframework.io/en/patterns/navigation) shows a navigation header that is 48px high:
`html {font-size: 16 px}` × (`.p-navigation__link > a {font-size: .875rem}` +
`.p-navigation .p-navigation__links .p-navigation__link {padding: .75rem 1.25rem;}`)
= 16px × (0.875 + 0.75 top + 0.75 bottom) = 48px.

Some sites using Vanilla are consistent with this:
48px [www.ubuntu.com](https://www.ubuntu.com/)
48px [www.canonical.com](https://www.canonical.com/)
48px [maas.io](https://maas.io/)

Unfortunately, others are not:
50px [build.snapcraft.io](https://build.snapcraft.io/) ([#800](https://github.com/canonical-websites/build.snapcraft.io/issues/800))
51px [snapcraft.io](https://snapcraft.io/), including [snapcraft.io/docs](https://snapcraft.io/docs/)
53px [docs.ubuntu.com](https://docs.ubuntu.com/core/en/)
53px [jujucharms.com](https://jujucharms.com/how-it-works)

The jujucharms.com example is apparently from the past couple of weeks, and build.snapcraft.io from only 3~4 months ago, which suggests that this is not just a matter of some sites using out-of-date Vanilla versions.

So, it may be worthwhile investigating how they became inconsistent, and how this can be avoided in future.

**Comment by spencerbygraves** [comment]
In the case of the jujucharms.com header, it's taller than 48px due to it's relationship with the GUI header, and in turn with elements in the GUI such as the inspector and the service/machine view switcher.

If we decide that all headers need to be the same height, we can look into changing it.

**Comment by yaili** [comment]
This issue is related to: https://github.com/ubuntudesign/vanilla-store-theme-design/issues/10 - which should probably move to vanilla-design…

**Comment by yaili** [comment]
This issue was moved to ubuntudesign/vanilla-design#38

**Comment by yaili** [comment]
This issue was moved to ubuntudesign/vanilla-design#39
