### ISSUE TITLE
Investigate spacing for single elements to eradicate the need for `.u-padding-bottom`

### ISSUE THREAD

**Issue by deadlight** [vanilla-framework/vanilla-framework#1091]
# .u-padding-bottom

## Is this a proposal or an amendment?
Proposal

## Visual

A matrix next to a paragraph with a button.

### Without class:
![without](https://cloud.githubusercontent.com/assets/118614/26619822/0a8e67da-45d8-11e7-9e4c-9a097c6265a3.png)

### With `u-padding-bottom--x-large`:
![with](https://cloud.githubusercontent.com/assets/118614/26619825/10675180-45d8-11e7-9336-74ec587704ef.png)

## Context

In what context will the pattern be used?
Usually to add some vertical spacing between stacked elements which would not ordinarily have padding.

## Progressive enhancement
This uses spacing variables which scale with viewport.

## Code
```
.u-padding-bottom {
  padding-bottom: $sp-medium;

  &--large {
    padding-bottom: $sp-large;
  }

  &--x-large {
    padding-bottom: $sp-x-large;
  }
}
```

**Comment by yaili** [comment]
Working group notes:
- Related to https://github.com/vanilla-framework/vanilla-framework/issues/1077
- Next steps would be the same as issue #1077

**Comment by yaili** [comment]
Working group notes:
- @anthonydillon will investigate options to deal with spacing between rows (mostly…)

**Comment by barrymcgee** [comment]
<img width="1305" alt="screen shot 2017-06-28 at 09 10 04" src="https://user-images.githubusercontent.com/505570/27627301-380baa3a-5be3-11e7-84c8-bd2ebb5c5001.png">
