### ISSUE TITLE
Default button colours should match neutral button

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#1097]
Right now if you don't specify a button type, you get a border colour that was not specified, can we make sure that if no style is selected, it uses the neutral styles?

**Comment by anthonydillon** [comment]
Can you give details here, please? I can see the `#666` border [in vanilla-framework](https://github.com/vanilla-framework/vanilla-framework/blob/develop/scss/_base_button.scss#L14) but don't know what to change it too. [The spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Buttons/buttons.md#common) states no default background or border.

**Comment by yaili** [comment]
OK, I will change the spec to say neutral should be the default if no style is stated

**Comment by yaili** [comment]
It's updated now.
