### ISSUE TITLE
Build is-crossed state for list items

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1101]
We have `is-ticked` but we have nothing for `is-crossed`.

**Comment by yaili** [comment]
Do we have designs for it?

**Comment by anthonydillon** [comment]
Doesn't look like it. Looks like we are missing a few list patterns in the
design repo:
https://github.com/ubuntudesign/vanilla-design/tree/master/Lists

**Comment by yaili** [comment]
Do you mean some list patterns haven't been built, or haven't designed? 🤔

**Comment by barrymcgee** [comment]
What does `.is-crossed` even look like?

@yaili I think we should be looking at the `vanilla-design` repo as the single source of truth - if it's not there, it hasn't been designed and/or signed off so shouldn't be in Vanilla...

**Comment by yaili** [comment]
Working group notes:
- Added this a part of existing issue: https://github.com/ubuntudesign/vanilla-design/issues/25
