### ISSUE TITLE
Advanced usage documentation page

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#1102]
In addition to the get-started documentation page (which is hopefully going to land soon), we should create a page about advanced usage, which explains how to include Vanilla in your Sass if you're using Gulp, or other build/development systems. This page should then be linked from get-started.

**Comment by yaili** [comment]
Would that be here or in vanillaframework.io?

**Comment by nottrobin** [comment]
It would be here. In docs.

**Comment by yaili** [comment]
Where in the navigation would that live in docs.vanillaframework.io?

**Comment by nottrobin** [comment]
I haven't thought too much about it. Do you have a strong opinion? Off the top of my head, `docs.vanillaframework.io/advanced-usage` seems like it would make sense.

**Comment by yaili** [comment]
OK. I just think we need to think about where these pages that aren't patterns live in the Vanilla and Vanilla themes docs. Are they under a separate heading? We will probably have more than one, right? What should it be called?

**Comment by nottrobin** [comment]
Can't they live at the top level, alongside `index.md` and next to the `base` etc. folders? Since they're general guides.

**Comment by anthonydillon** [comment]
We should follow the emerging pattern of documentation throughout the
company. Which is, index.md contains a getting started guide. With advanced
options.
