### ISSUE TITLE
Review "This field is required" on forms pattern

### ISSUE THREAD

**Issue by joanasa89** [vanilla-framework/vanilla-framework#1126]
## "This field is required"

# 2. Pattern amendment
At the moment the "This field is required" appears in a very subtle way and in the same style as the input's labels (see image)
![screen shot 2017-06-21 at 17 04 59](https://user-images.githubusercontent.com/21334617/27394703-074427bc-56a5-11e7-9193-022f3aebd665.png)

## Is this a proposal or an amendment?
- Amendment
- Pattern : Forms 

## Proposal
I propose using a different style for "This field is required".
Here some options: 

A - use a different colour (maybe red colour?) and add a red outline to the empty field _or_
B - use italic weight _or_
C - add an asterisk at the end of each label and provide a legend which tells the meaning of it. Something like "* Indicates required field" _or_
D - Reduce the font size to 14px

**Comment by richmccartney** [comment]
@joanasa89 I suggest talking to @kwm14 & @spencerbygraves  as we've done work on this for MAAS and Juju to help the proposal. We've done quite a lot of work on forms.

**Comment by kwm14** [comment]
@joanasa89 I adopted the styling from @spencerbygraves original design, in MAAS form fields are horizontal rather than vertical so I adjusted the position of 'form label' to address:

- the design is also accessible 👍 

### MAAS form validation
![form-validation](https://user-images.githubusercontent.com/17748020/27579843-cb8ad592-5b20-11e7-9cec-2a96fcbe839b.png)

**Comment by joanasa89** [comment]
Cool! Looks more intuitive. @yaili is this something we can implement on ubuntu.com?

**Comment by richmccartney** [comment]
@joanasa89 there are other layout permutations to this, i.e we keep the label on top, or to the left with spacing and also completely inline for forms that require it. 

@kwm14 We don't have any other designs showing off this layout do we?

**Comment by spencerbygraves** [comment]
https://github.com/vanilla-framework/vanilla-framework/issues/731

**Comment by yaili** [comment]
Isn't this already in Vanilla? 🤔

Some notes: 
The "This field is required" from the original comment should be styled as an error, and shows up on submit. We have started moving away from indicating required fields, and just indicate the optional ones, as part of the label.

**Comment by anthonydillon** [comment]
We have decided to move toward labelling just optional fields in the label. For example: https://github.com/canonical-websites/www.ubuntu.com/issues/649.

If the form is submitted with some black required fields a validation error should be displayed.
