### ISSUE TITLE
Suggest installing vanilla-framework with --save-dev

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#1139]
Following on from:

https://github.com/vanilla-framework/vanilla-framework/pull/1136#discussion_r125323595

I'd like to reconsider using `--save-dev` instead of `--save` in the official getting started instructions.

> I don't remember concurring. The difference between --save and --save-dev is that in the former case the dependency will be included in all child project. That is, if my-project --saves vanilla-framework, and then ants-project adds my-project as a dependency, ants-project will also get vanilla-framework.
> 
> I don't think this is at all relevant for the expected use-case. I think in normal websites, vanilla-framework is simply a build resource, only relevant for local building, not an actual dependency for the website project itself, which actually just needs some built CSS.
> 
> So I think we should use --save-dev.
> 
> I realise this has now been merged, but I think I'll file an issue about it now.
>
> --save is relevant for vanilla themes, but not usually for website projects.

I would suggest that encouraging people to use `--save` will actually more likely pollute their website's dependencies unintentionally. It's better to encourage them to err on the side of caution by not causing them to automatically propagate their dependencies into child projects unless they know what they are doing.

**Comment by yaili** [comment]
@nottrobin is this a proposal?

**Comment by nottrobin** [comment]
I don't think it's a proposal at this stage, I think it's a work item. I had a little discussion with @barrymcgee about it, and I think we decided that we *would* use `--save-dev`. I'll submit a PR now.

**Comment by yaili** [comment]
@nottrobin thanks 👍
