### ISSUE TITLE
Top margin on main navigation

### ISSUE THREAD

**Issue by grahambancroft** [vanilla-framework/vanilla-framework#1140]
## Process

The new vertical rhythm update adds top margin to the header

## Expected result

There shouldn’t be top margin on the header

## Current result

There’s margin above the header

## Screenshot

![screen shot 2017-07-04 at 10 57 06](https://user-images.githubusercontent.com/2152/27825489-9e281f60-60a7-11e7-9723-fa5fe5476c26.png)

**Comment by barrymcgee** [comment]
How did Percy miss that? 🤔

**Comment by yaili** [comment]
@barrymcgee is it because the header isn't followed or following anything in the examples?

**Comment by barrymcgee** [comment]
@yaili Oh, I thought it was the navigation header.
