### ISSUE TITLE
Top margin on .wrapper

### ISSUE THREAD

**Issue by grahambancroft** [vanilla-framework/vanilla-framework#1142]
## Process

The new vertical rhythm update adds top margin to the .wrapper class that is used on our sites

## Expected result

There shouldn’t be top margin on the .wrapper

## Current result

There’s margin above the .wrapper

## Screenshot

![screen shot 2017-07-04 at 11 43 56](https://user-images.githubusercontent.com/2152/27831036-c4186982-60c0-11e7-890e-0b9f5db569f5.png)

**Comment by anthonydillon** [comment]
Let's use the margin-collapse utility for this case.
