### ISSUE TITLE
Vanilla assumes inline whitespace between breadcrumb items

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1146]
Breadcrumb pattern assumes there is a whitespace in HTML between breadcrumb items to display correct spacing.

If breadcrumb HTML is rendered without whitespace between items (for example is rendered by React from JSX) like:
```html
<ul class="p-breadcrumbs"><li class="p-breadcrumbs__item"><a class="p-breadcrumbs__link" href="#">Breadcrumb One</a></li><li class="p-breadcrumbs__item"><a class="p-breadcrumbs__link" href="#">Breadcrumb Two</a></li><li class="p-breadcrumbs__item"><a class="p-breadcrumbs__link" href="#">Breadcrumb Three</a></li><li class="p-breadcrumbs__item">Breadcrumb Four</li></ul>
```
it will have incorrect spacing (arrow will be closer to previous item):

<img width="583" alt="screen shot 2017-07-04 at 16 39 17" src="https://user-images.githubusercontent.com/83575/27834628-f999b02c-60d7-11e7-8b24-7681180aa50f.png">

## Expected result

Ideally breadcrumb pattern should ignore whitespace and render correctly regardless of existence of inline space between elements:

<img width="599" alt="screen shot 2017-07-04 at 16 45 52" src="https://user-images.githubusercontent.com/83575/27834704-4822aa8c-60d8-11e7-9b6d-7e89411a4b06.png">

**Comment by anthonydillon** [comment]
This is a bug. We should be careful when using inline-block.
