### ISSUE TITLE
Footer links alignment

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#1149]
Default spacing on Footer links of off due to vertical rhythm changes:

Screenshot:

<img width="704" alt="screen shot 2017-07-05 at 11 38 56" src="https://user-images.githubusercontent.com/505570/27860927-9d912c7a-6176-11e7-918d-403c3886cc17.png">

**Comment by barrymcgee** [comment]
Once the above is resolved, this should be too.

**Comment by anthonydillon** [comment]
Confirm it looks better:
![footer - vanilla framework - examples](https://user-images.githubusercontent.com/1413534/28156600-5888ae42-67ab-11e7-850a-6a05d2443853.png)
