### ISSUE TITLE
Do we need a horizontal rule in docs before Related section?

### ISSUE THREAD

**Issue by Lukewh** [vanilla-framework/vanilla-framework#1180]
When converting all 'Related' headings to `<h3>`s I noticed that most of the pages had `<hr />`s immediately above. I added `<hr />`s to those pages that didn't have them. Do we need these? If so should we style them from the default?
We will also need to consider spacing around them.

## Screenshots
<img width="934" alt="screen shot 2017-07-18 at 09 19 58" src="https://user-images.githubusercontent.com/479384/28307319-6e52065e-6b9a-11e7-8cd8-d19429dd3ada.png">
<img width="919" alt="screen shot 2017-07-18 at 09 20 11" src="https://user-images.githubusercontent.com/479384/28307324-71c81e9a-6b9a-11e7-8529-1f7c012873a2.png">

**Comment by yaili** [comment]
I think we should have them, the hrs should have some default Vanilla styling, do they not?

**Comment by Lukewh** [comment]
@yaili they don't have styles.

**Comment by anthonydillon** [comment]
It should look like this:
https://vanilla-framework.github.io/vanilla-framework/examples/base/hr/

If it doesn't then can you look into it?
