### ISSUE TITLE
[Proposal] Add Jekyll / GitHub Pages Guide To Docs?

### ISSUE THREAD

**Issue by sudopluto** [vanilla-framework/vanilla-framework#1199]
## Documentation enhancement

I am currently using vanilla framework on my github pages site using git submodules. I based this on a old blog post / sample repo. Perhaps we can add the submodule guide to the documentation?

**Comment by barrymcgee** [comment]
Hi @sudopluto - is your site open source? Can you link to it so I can see how you are set up using submodules?

**Comment by sudopluto** [comment]
https://github.com/sudopluto/sudopluto.github.io, the vanilla info should be in the readme. That is only needed for local development as github pages handles submodules on their end, so vanilla itself is not tracked.

**Comment by anthonydillon** [comment]
The suggestion is to include the method below in the documentation of Vanilla.
https://design.canonical.com/2015/11/using-vanilla-with-jekyll/

**Comment by barrymcgee** [comment]
@sudopluto Thank you for this proposal - it's great to see another site in the wild using Vanilla framework.

I've added a section to the 'Getting started' section of the docs and submitted a Pull Request (see above). 

This issue will be discussed in our Working Group on Monday 24/07/17 and if accepted, it will be merged and deployed on Thursday 27/07/17. Please keep watching this issue for updates.

**Comment by Lukewh** [comment]
👍
