### ISSUE TITLE
Include CSS variables into our SCSS variables

### ISSUE THREAD

**Issue by richmccartney** [vanilla-framework/vanilla-framework#1242]
# Pattern proposal/amendment

## Is this a proposal or an amendment?

- Proposal

## Context

After talking to @anthonydillon in a recent 1:1 I brought forward and idea to streamline vanilla framework a bit further and to be a lot more progressive with development. Currently if a developer or outside contributor wishes to use the framework they can by either;

1. Pulling down the minified version of the framework and built as CSS  
2. Include the uncompiled SCSS into their own project and go through the build process for what they need

Both are great but the CSS version doesn't offer great simple variable changes that you get with compiling your own SCSS.

My proposal is to build the CSS we host using and compiled with CSS variables (If unclear here is a great post about this here https://css-tricks.com/difference-between-types-of-css-variables/). By doing so it'll make smaller variable overrides such as `$brand-color` a lot easier. This variable in SCSS would be linked to a css variable for example `--brand-color: #F00;` and then can be overridden in CSS when hosted via root _example_:

`
:root {
  --brand-color: #0F0;
}
`

My proposed method would follow a post from last year by Jake Albaugh's to use the scss `map-get()` function and other powerful `mixin` to give the flexibility but also add the progressgive enhancement required as Internet Explorer Edge 14 and bellow doesn't support CSS `var`

Blog post – https://codepen.io/jakealbaugh/post/css4-variables-with-fallbacks-using-sass

## Benefit

From this work if done, the main benefit will mean hosting minified CSS with out compiling and being able to do simple theme style overrides to the framework. It'll also reduce the knowledge required to understand SCSS and how the framework is built. Hopefully this can also spur on more adoption too as the framework would be seen to be thinking forward.

**Comment by yaili** [comment]
Working group notes:
- The cost vs benefit of acting on this issue is high
- We should solve this issue later, when CSS Variables are more widely supported
- We will close this issue for now, but should refer back to it when it becomes a requirement
