### ISSUE TITLE
Heading icon specifying font-size and line-height

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#1263]
_From @anthonydillon on June 8, 2017 16:32_

I am currently working on fixing the heading icon pattern as it [should not dictate](https://github.com/vanilla-framework/vanilla-brochure-theme/issues/78#issue-230005808) the font-size and line-height. But the spec states it [should be a heading-3](https://github.com/ubuntudesign/vanilla-brochure-theme-design/blob/master/Heading%20icon/heading-icon.md) style.

Should the pattern stay as is or should the spec be updated?

_Copied from original issue: ubuntudesign/vanilla-brochure-theme-design#23_

**Comment by yaili** [comment]
I will update.

**Comment by yaili** [comment]
Opening again so we don't forget to fix.

**Comment by kwm14** [comment]
### Design spec has been updated

According to the MD file:
- Title font size: depends on heading style applied
- Title line height: depends on heading style applied
