### ISSUE TITLE
Assets server upload failing upon release

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#1268]
When running the release process on Jenkins, the final step to upload the new release to the assets server failed.

<img width="1043" alt="screen shot 2017-08-14 at 14 31 59" src="https://user-images.githubusercontent.com/505570/29273890-d993ad50-80fd-11e7-8e47-f76b4ce12ce1.png">

This means that the direct link (as advertised in the hotlink section of docs) is failing.

https://assets.ubuntu.com/v1/vanilla-framework-version-1.4.3.min.css

**Comment by anthonydillon** [comment]
This is caused by putting the jobs to the new Jenkins instance. The
external GitHub repo that contained the asset uploader functions is missing
from the jobs.

Robin should be able to help here.

I believe the entire job should fail if part of the release errors.

**Comment by nottrobin** [comment]
Yes Robin or @WillMoggridge should be able to help. We should now be using the new [upload-assets](https://github.com/canonical-webteam/upload-assets) snap-installable utility to upload this stuff.
