### ISSUE TITLE
Navigation pattern needs to show current highlighted page and rollover state

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#1269]
The current navigation pattern does not cater for a hover state.  It also needs to a state to highlight the current page.

**Comment by yaili** [comment]
@barrymcgee should this be in the vanilla-design repo?

**Comment by barrymcgee** [comment]
@yaili If it will be picked up in Working Group from repo, then yes.

**Comment by yaili** [comment]
@barrymcgee ok, but we generally submit proposals that we know are design tasks directly in the design repos.

**Comment by barrymcgee** [comment]
Moved to: https://github.com/ubuntudesign/vanilla-design/issues/50
