### ISSUE TITLE
Remove margin from card heading

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1280]
## Is this a proposal or an amendment?

- Card pattern amendment

## Amendment

- Link to design [spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Card) 
-  Remove margin from card heading

## Visual

**Current result**
![screen shot 2017-08-21 at 10 06 56](https://user-images.githubusercontent.com/17748020/29511936-a3efb8f0-8658-11e7-803f-b0281e9eb861.png)

**Expected result**
![screen shot 2017-08-21 at 10 09 39](https://user-images.githubusercontent.com/17748020/29512000-e2c49b40-8658-11e7-8495-d57d03c28284.png)

**Comment by barrymcgee** [comment]
@anthonydillon Can you run Vanilla locally and check why the styling for `.p-card__header` in the `@ extend .p-card` is not being run? 

Isolating it on Sassmeister - https://www.sassmeister.com/gist/31c404267d1e25ccb2534d3effeb1b30 - it works fine?
