### ISSUE TITLE
Design sidebar navigation pattern

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1285]
- Speak with @spencerbygraves regarding this design
- New version of sidebar built by @barrymcgee

**Comment by kwm14** [comment]
@spencerbygraves could you design review this for me.

I've created a new design taking influence from your original sidebar navigation and what Barry had built for the dashboard theme. Once I design sign-off I will generate the spec.

### Sidebar navigation
![Sidebar-navigation.png](https://images.zenhubusercontent.com/593a661951aa2c30578102ca/6bb02ceb-1810-47ed-b8d8-f3c70e75e841)

**Comment by kwm14** [comment]
### Updated design

- adding indent to second and third levels
- allows users to view tiered content
- @spencerbygraves ready for re-review

![Sidebar-navigation.png](https://images.zenhubusercontent.com/593a661951aa2c30578102ca/b98a2556-c37d-4ac3-847e-1aa11dbbcc4a)

**Comment by spencerbygraves** [comment]
@kwm14 A couple more thoughts...

- Would we also have the grey background on the open second level?
- I would try keeping the second level link indented after clicking, and indent level 3 links one step further. Assuming we don't go much deeper than third level links.

**Comment by kwm14** [comment]
### Updated design

- based on @spencerbygraves feedback

![sidebar-navigation](https://user-images.githubusercontent.com/17748020/29967559-1551f206-8f0f-11e7-8ca1-2c3cb285b77f.png)

**Comment by kwm14** [comment]
- Design and spec created 
- Added to vanilla-design repo [here](https://github.com/ubuntudesign/vanilla-design/tree/master/Sidebar%20navigation)
