### ISSUE TITLE
Typographic scale needs updating in the docs

### ISSUE THREAD

**Issue by spencerbygraves** [vanilla-framework/vanilla-framework#1304]
# 1. Bug

## Process

1. Navigate to https://docs.vanillaframework.io/en/base/typography#typographic-scale

## Expected result

The type scale table should match the latest:

https://github.com/vanilla-framework/vanilla-framework/issues/960
https://github.com/vanilla-framework/vanilla-framework/pull/1095

**Comment by kwm14** [comment]
Thanks @spencerbygraves 

This issue is in our current iteration for Scheduled maintenance to be [updated](https://app.zenhub.com/workspace/o/vanilla-framework/vanilla-framework/issues/1270).
