### ISSUE TITLE
Bigger variant of Media Pattern

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1315]
# Pattern proposal/amendment

## Is this a proposal or an amendment?

- Amendment

If amendment, what is the name of the pattern to be amended?

Media object pattern (bigger version)

## Visual

**Large screen**

![image](https://user-images.githubusercontent.com/9105999/29878520-ab4c130c-8d9a-11e7-9e53-48eea19d2e5f.png)

**Small screen**

![image](https://user-images.githubusercontent.com/9105999/29878542-bd72def8-8d9a-11e7-93b0-54e19f906fde.png)

**Sizing**

![image](https://user-images.githubusercontent.com/9105999/29959607-0b1fd8bc-8ef0-11e7-90a8-cf3e17e956a4.png)

## Context

Newly designed Snap Details page includes a component consisting of a snap icon, name, publisher, install button etc.

This seems very similar in layout to current Media Object pattern but uses different sizing (icon is bigger, larger heading).

It would be nice to have such variant in code Vanilla. Currently to achieve similar look we need to use grid directly which behaves differently on smaller screens (stacks on top of each other).

Context: https://github.com/CanonicalLtd/snapcraft-design/issues/54

**Comment by anthonydillon** [comment]
I would love to use element queries to make this element responsive without
modifiers. As your design shows. Unfortunately, element queries are not
available yet.

In my option, there are two way forward with this:
1. Create a modifier for the media object pattern (proposed)
2. Create a new pattern named by the function this pattern is performing

I believe the best way forward would be to extend the media object pattern
as there is not enough visual difference between the two designs. Also, I
can not think of a good name for a new pattern for this.

**Comment by matthewpaulthomas** [comment]
A pattern is worthwhile if it will save more time than it costs. That might well be the case here. But a few issues to consider:

- If a pattern doesn’t have an obvious name, people are less likely to use it. To me, the name “media object” is already vague: if I didn’t know what it was already, I would have guessed it was some kind of video player element. And maybe there isn’t a good name. (Labelled icon? Icon with data?)

- How much easier would the markup be with this pattern than without it? For example, this pattern seems like it would also be used on [Juju charm pages](https://jujucharms.com/postgresql/). But they currently don’t even have the equivalent elements in their own container element — they share the same `<div class="inner-wrapper">` as stuff alongside and below.

- Would this help pages become more consistent? [Juju bundle pages](https://jujucharms.com/hadoop-spark/) have the same structure as charm pages, but without an icon, which makes the text alignment inconsistent. Maybe bundles should have a generic icon, and adopting the pattern would encourage that.

**Comment by barrymcgee** [comment]
Just to note - "Media object" is the common term for this pattern across the industry..

- http://www.stubbornella.org/content/2010/06/25/the-media-object-saves-hundreds-of-lines-of-code/
- https://css-tricks.com/media-object-bunch-ways/
- https://v4-alpha.getbootstrap.com/layout/media-object/

**Comment by pmahnke** [comment]
almost done

**Comment by matthewpaulthomas** [comment]
Well, TIL. Thanks, @barrymcgee.

I’ve reported issues (linked above) on adopting the pattern on jujucharms.com.
