### ISSUE TITLE
Investigate animations with Percy

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1323]
Percy is picking up animated icon as a diff every time as the icon is rotated differently each snap shot. 

Is there a way to stop animations in examples for Percy or do we need to move the animated patterns to there own example and have Percy ignore it?

**Comment by bartaz** [comment]
Percy is supposed to automatically freeze CSS animations:
https://percy.io/docs/learn/animations#automatic-animation-freezing-in-percy

But I couldn't find any info about what to do if it doesn't (or if animation still produces false positives)

**Comment by anthonydillon** [comment]
Thanks @bartaz wonder how they stop CSS animations. Maybe sets all content's transform/animation to none with important.

@barrymcgee might be worth a support ticket.

**Comment by bartaz** [comment]
@anthonydillon Maybe they pause it by adding `animation-play-state: pause`.

https://developer.mozilla.org/en-US/docs/Web/CSS/animation-play-state

**Comment by bartaz** [comment]
@anthonydillon Actually, this may be the case.

Our spin animation in Vanilla uses `!important`: https://github.com/vanilla-framework/vanilla-framework/blob/develop/scss/_utilities_animations.scss#L4

Maybe that's why their way to pause animation doesn't work because it's overridden by !important.

**Comment by barrymcgee** [comment]
Sounds probable.. if this doesn't turn out to eb the case, I can email them directly.

**Comment by anthonydillon** [comment]
This has been fixed via https://github.com/vanilla-framework/vanilla-framework/pull/1353

**Comment by barrymcgee** [comment]
Icons have been resolved but the animation is still not being paused

**Comment by barrymcgee** [comment]
This is now resolved.
