### ISSUE TITLE
Key-value table pattern proposal

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1349]
# Pattern proposal - Key-value table

## Is this a proposal or an amendment?

- Proposal
- Amendment

## Visual

<img width="458" alt="screen shot 2017-09-18 at 14 50 51" src="https://user-images.githubusercontent.com/83575/30542775-ee61e1d6-9c80-11e7-8c6b-802156a1e81c.png">

<img width="1034" alt="screen shot 2017-09-15 at 13 34 32" src="https://user-images.githubusercontent.com/83575/30485877-08d63b2e-9a2f-11e7-8472-ea30c3adfc49.png">

## Context

For small key-value tables default table styles feel overloaded (with a lot of spacing and heavy borders).

This was proposed as part of snap details page design: https://github.com/CanonicalLtd/snapcraft-design/issues/54#event-1219437597

Specifically (from https://github.com/canonical-websites/snapcraft-flask/issues/44#issuecomment-328897559):
- Make the key (header) cells use grey, while the value cells use black. (It’s more obvious that the first column consists of header cells when the table has only two columns.)
- Right-align the key cells.
- Remove the horizontal lines between rows. (They exist because of the potential large gaps between columns; right-aligning the headers solves the same problem with less noise.)

## State

Stateless - just an alternative styling for table element.

## Progressive enhancement

Basic styling that can be applied for all devices and screen sizes.

## Code

Proposal implementation is currently in development in: https://github.com/canonical-websites/snapcraft-flask/pull/51

**Comment by kwm14** [comment]
Thanks for this proposal @bartaz 

- matthew plans to discuss in Design patterns fortnightly 
- as this currently has a one-time use case there isn't a need to push up into base Vanilla
- if/when other Cloud products adopt this styling in tables we will revisit

**Comment by anthonydillon** [comment]
I would like to propose that this could be created with current patterns without introducing a new one. The only thing I can see that is unachievable is the grey text. Which I believe could be argued as less accessible. 

I have created an example using existing patterns: https://codepen.io/anthonydillon/pen/jGXyqo

I am aware this is slightly different from the design but I would like to push us to align where possible.

**Comment by anthonydillon** [comment]
Going to move back to a proposal until agreed.

**Comment by anthonydillon** [comment]
Agreed we should resist adding new patterns that can be achieved with current patterns. Therefore, as long as @spencerbygraves is happy with it then we can drop this new pattern and use the proposed.

**Comment by spencerbygraves** [comment]
@anthonydillon I'm happy to use existing patterns and match the alignment in the design above.

**Comment by anthonydillon** [comment]
As the proposal author is happy to use existing patterns then there is no work to be done here.
