### ISSUE TITLE
Navigation menu category text isn’t clickable

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1370]
@matthewpaulthomas commented on [Wed Jul 19 2017](https://github.com/vanilla-framework/vanilla-docs-theme/issues/51)

1\. Go to any page on a Docs-theme-using site that has categories, for example [the Vanilla Docs itself](https://docs.vanillaframework.io/).
2\. Click on the text of any of the categories, for example “Settings”, “Base”, “Patterns”, or “Utilities”.

What happens: Nothing.

What should happen: The category should expand/collapse, just as it would if you clicked the adjacent arrow.

**Comment by Caleb-Ellis** [comment]
Closing as this will be fixed when [Issue 118 on vf docs](https://github.com/ubuntudesign/docs.vanillaframework.io/issues/118) is addressed
