### ISSUE TITLE
Not obvious whether a navigation menu section heading is a link

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1372]
1\. Go to [the Vanilla documentation](https://docs.vanillaframework.io/en/).
2\. Click on any of the headings in the contents pane: for Vanilla “Settings”, “Base”, “Patterns”, or “Utilities”.
3\. Try the same on [the Maas documentation](https://docs.ubuntu.com/maas/2.2/en/).
4\. Try the same on [the Juju documentation](https://jujucharms.com/docs/stable/getting-started).
5\. Try the same on [the Snapcraft documentation](https://docs.snapcraft.io/).

What happens:
2\. The headings are not clickable.
3\. The headings are not clickable.
4\. Clicking a heading expands/collapses its section of the table of contents.
5\. Clicking a heading goes to a different page.

Whether it ever makes sense for clicking the heading to do nothing at all is covered by #1370.

Regardless of whether that is fixed, though, unless you mouse over them, there is no visual distinction between headings that are not links and headings that are.

A minimal fix would be to use the standard link colour for table of contents links all the time, not just on mouseover.

**Comment by Caleb-Ellis** [comment]
Closing as this will be fixed when [Issue 118 on vf docs](https://github.com/ubuntudesign/docs.vanillaframework.io/issues/118) is addressed
