### ISSUE TITLE
Research Disqus hosting service

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1375]
## Disqus

Research [Disqus](https://disqus.com/) hosting service for blog comment on our web sites.

- initial discussions happened [here](https://github.com/ubuntudesign/vanilla-design/issues/100#issuecomment-335485703)
- use for blog comments for our sites
- research into how we integrate in Vanilla
- pricing for hosting their services

**Comment by anthonydillon** [comment]
I don't think we need to worrying about this until we have a use case. Closing for now but will create a new issue when there is a project that requires comments.
