### ISSUE TITLE
Code blocks do not have top margins

### ISSUE THREAD

**Issue by Caleb-Ellis** [vanilla-framework/vanilla-framework#1385]
Code blocks do not have top margins by default. It might be a good idea to add a top margin to the 'pre' tag by default, unless it sits within a div that already has a top margin (for example, in a paragraph div).

## Example
![31072381-f4326526-a767-11e7-99f2-acdf45ceac2d](https://user-images.githubusercontent.com/25733845/31718224-f8bb2f6e-b406-11e7-881a-b340fd12b4ee.png)

**Comment by anthonydillon** [comment]
Approved but may already be fixed. Please investigate.

**Comment by Caleb-Ellis** [comment]
Fixed as part of 1.7.0
