### ISSUE TITLE
Update to the latest example-js

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#1388]
As we do not have an agreed consistent way to implement Javascript across components, we should remove the snippets for now.

**Comment by barrymcgee** [comment]
@anthonydillon Given that we need the JS to actually make the components work in-situ in the docs, does this change need to happen in example-js?

**Comment by anthonydillon** [comment]
Yes, if we dont want any script logic in the examples then there will need
to be an issue on example.js that strips the scripts from the code output.

**Comment by anthonydillon** [comment]
This issue will now depend on https://github.com/canonical-webteam/example-js/issues/28.
