### ISSUE TITLE
Set max-width to text elements (p, h1-6, blockquote etc.)

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1394]
# 1. Base proposal/amendment
According to tradition and some studies, the "measure" (number of characters per line) should be between 45 - 75 characters. Setting max-width: 38em can achieve that.

Unlike limiting text with grid columns, settign a max width in ems ensures that:
- Text in different sizes breaks where optimal
- Resizing the browser window maintains the optimal length as long as the window is wide enough. (Which wouldn't be the case if line length is constrained by grid columns)

## Is this a proposal or an amendment?
- Amendment

## Visual
![image](https://user-images.githubusercontent.com/2741678/31881361-37953702-b7db-11e7-8fc8-dda924e85835.png)

## Context
This is a global suggestion, meant to bring all copy on the site to adhere to best practices.
An override might be useful if text elements like a p are wrapping other elements, as sometimes happens with cms wysiwyg editors.

## State
No states

## Progressive enhancement
No fallback necessary, as max-width is universally supported (https://caniuse.com/#search=max-width)

Quote from 
[Web Typography](http://book.webtypography.net/) by [Richard Rutter](https://clearleft.com/team/richard-rutter):

> The often quoted ideal length for a line is 66 characters, with a range of 45–75 characters (including spaces) generally considered satisfactory. Rather than representing a predefined guideline, these  figures reflect the de facto habits of master printers and typesetters since the invention of the moveable type printing press nearly six hundred years ago. ...
> The implication is that any book, newspaper or other reading material printed in the last few centuries is likely to be set with lines containing between 45 and 75 characters.
> That said, we established in ‘How we read’ that reading screens is different from reading from paper. The very limited amount of research that has been undertaken on reading from screens indicates that longer line lengths (up to 100 characters) do not adversely affect readability, and can in fact increase the speed of reading. The temptation, therefore, might be to use longer lines on screens. However, the same studies revealed that readers stated a preference for shorter lines. This is an important  finding. Readability is as much about setting text that wants to be read, as it is about setting text that can be read quickly and easily.
> It leads us back to our history and the six centuries of print typography that have come before us: aim for setting paragraphs 45–75 characters wide, just as was being done on vellum all those years ago. Remember, though, that this range is an observation, not a mandate, so a little either side – for good reason – won’t do any harm.

Further info is also available in [Elements of Typographic Style](https://www.amazon.co.uk/Elements-Typographic-Style-Version-4-0/dp/0881792128/ref=sr_1_3/262-0588792-9733102?ie=UTF8&qid=1508750815&sr=8-3&keywords=elements+of+typographic+style) by Robert Bringhirst

**Comment by anthonydillon** [comment]
After a discussion in the working group we believe this is overly opinionated. The grid is used currently which allows for flexibility and reduces any unexpected behaviour. Until we find this is causing an issue we will close for now.

**Comment by anthonydillon** [comment]
To be tested on snapcraft and to be updated if the outcomes.

**Comment by lyubomir-popov** [comment]
@anthonydillon implemented on snapcraft.io, ready for review on p and h2 elements.

**Comment by kwm14** [comment]
Agreed in working group for @anthonydillon to test on ubuntu.com when applying new grid guide by @lyubomir-popov [here](https://github.com/vanilla-framework/vanilla-framework/pull/1408).

**Comment by kwm14** [comment]
This has been implemented in the latest [release](https://github.com/vanilla-framework/vanilla-framework/releases/tag/v1.6.3) of Vanilla 1.6.3.
