### ISSUE TITLE
Grid gutter width adjustment

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1395]
# 2. Pattern proposal/amendment

## Is this a proposal or an amendment?
- Amendment
If amendment, what is the name of the pattern to be amended? - Grid

Calculate gutter width as follows:
gutter width = (column width) / (golden ratio);

As an approximation, if (rounded) column width is 55px, gutters would be (rounded) 34px, as in a fibonacci sequence, because of the chosen ratio (the golden ratio, 1.61803398875). 

Since gutters are calculated as percentages currently, no rounding is necessary. (At the moment, gutter size is set to 20px, and this value is then [converted to a percentage](https://github.com/vanilla-framework/vanilla-framework/blob/bc9310274c40dd79e93403c8a285b20490c948aa/scss/grid/shelves/_variables.scss#L12) by the shelves grid.)

Example from the docs: 
![image](https://user-images.githubusercontent.com/2741678/31883966-84e816a2-b7e3-11e7-9687-3a5b8719aa51.png)

# Why is this an issue? 

Narrow gutters cause text set in adjacent columns to become too close, especially if the text in preceding column is set to right-aligned. Example of the problem:

![image](https://user-images.githubusercontent.com/2741678/31884102-fa7a44d0-b7e3-11e7-9725-383a9e912420.png)

To avoid that, various patches seem to have been applied as a "localised" solution. A couple of examples: using the current grid, text plus logo cloud would look like this: 

![image](https://user-images.githubusercontent.com/2741678/31884286-83dd9416-b7e4-11e7-8356-efe9f7492f2b.png)

(notice how close the word "make" gets to the logos.) (From [this page](https://www.ubuntu.com/internet-of-things))

The patch on this page is adding an empty column in between.

![image](https://user-images.githubusercontent.com/2741678/31884399-d4ee63da-b7e4-11e7-8fac-bb724e266ca8.png)

Other patches include vertical lines and doubling of the gutter on each side of the line, centering of content in adjacent column to keep it away from the left edge, ect.

## Visual

Provide a screenshot or link to prototype of your pattern proposal.

![image](https://user-images.githubusercontent.com/2741678/31882890-196c1a02-b7e0-11e7-8293-350e5798e060.png)

The screenshot below shows the example grid in the docs, built with the new gutter value:

![image](https://user-images.githubusercontent.com/2741678/31885144-68d0055c-b7e7-11e7-965b-174f9656d5ce.png)

## Context
Global context - everywhere a grid is currently being used.

## State
Stateless

## Progressive enhancement
Percentage should remain the same on smaller breakpoints.
Even though the shelves grid in vanilla has [settings for gutters on mobile and tablet](https://github.com/vanilla-framework/vanilla-framework/blob/bc9310274c40dd79e93403c8a285b20490c948aa/scss/grid/shelves/_variables.scss#L16), those don't seem to be used (All layouts I've seen default to a single column under 800px).
If they are indeed needed, the ratio above will provide a suficiently wide value for mobile/tablet as well, so the multipliers can be reset to 1.0.
(currently):
$shelves-mobile-gutter: $shelves-gutter * 2.375 !default;
$shelves-tablet-gutter: $shelves-gutter * 1.5 !default;

(can change to):
$shelves-mobile-gutter: $shelves-gutter * 1.0 !default;
$shelves-tablet-gutter: $shelves-gutter * 1.0 !default;

**Comment by kwm14** [comment]
Link to [PR](https://github.com/vanilla-framework/vanilla-framework/pull/1408) by @lyubomir-popov

**Comment by anthonydillon** [comment]
Approved in the working group. Barry suggests that the changes in the attached PR are good. We would like to test this change on www.ubuntu.com as a test bed. Once its good it can merge.
