### ISSUE TITLE
Tabstrip - version with 16px font-size 

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1396]
## Is this a proposal or an amendment?
- Proposal - Augment the Tabs pattern to include a version where the font-size is 16px, besides the current 14px version.

#### Why is this an issue?
On pages where all other UI is >16px, the smaller tab strip feels out of proportion with the rest of the UI. [A 16px version is already in use in MAAS](http://10.20.68.142:5240/MAAS/#/nodes), but it would be nice to standardise that and make it available for use elsewhere, like in snapcraft UIs.

## Visual

14px:

![image](https://user-images.githubusercontent.com/2741678/31886133-fe0facdc-b7ea-11e7-9d5b-08b2dca91512.png)

16px:

![image](https://user-images.githubusercontent.com/2741678/31886529-8dadb428-b7ec-11e7-9aa3-297d04dc1adc.png)

## Context
Global context - addition to the currently used flavour of the tab strip.

## State
No changes to the states of the pattern.

## Progressive enhancement
No change from the current mobile solution is strictly necessary. That said, it would be nice to have scrollable tabs functionality as in the following two example from material design:

https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B6Okdz75tqQscHVOR1FVV2JjQms/components-tabs-typesoftabs-scrollable-tabs-01-xhdpi-003.mp4
(https://material.io/guidelines/components/tabs.html#tabs-types-of-tabs)

**Comment by kwm14** [comment]
Agreed in Design patterns fortnightly that this is a valid issue and should be updated in Vanilla so we're consistent across all Cloud products.

**Comment by kwm14** [comment]
New issue created to add enhancement to this component https://github.com/vanilla-framework/vanilla-framework/issues/1407
