### ISSUE TITLE
Soft link colours for dark tooltips

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1398]
# 2. Pattern proposal/amendment

Currently, soft links in dark tooltips are indistinguishable from text (white), which forces use of strong links (bold). Would be nice if they were a different colour (that satisfies AAA contrast ratio between text and background), based on the regular blue link colour/

## Is this a proposal or an amendment?

- Proposal

If amendment, what is the name of the pattern to be amended? Links

## Visual
![image](https://user-images.githubusercontent.com/2741678/31887607-e2c4cdc6-b7f0-11e7-9656-acce571f0be5.png)

new base colour: #54A7DF (current colour used on white background, adjusted to [meet AAA contrast requirements](https://webaim.org/resources/contrastchecker/) on #111 background)

Provide a screenshot or link to prototype of your pattern proposal.

## Context

On dark background, as in tooltips

## State

All current link states, adjusted to new values when used on dark background

## Progressive enhancement

No change

**Comment by kwm14** [comment]
Moving this issue to the correct repo https://github.com/ubuntudesign/vanilla-design/issues/115
