### ISSUE TITLE
Tabs missing colours for :visited state

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1399]
# 1. Bug template

## Process

1. open https://docs.vanillaframework.io/en/patterns/tabs in incognito window 
2. click on any tab
3. Tab turns blue (visited state)

## Expected result
Visited state should match non-selected state (remain black)

## Current result
Turns blue (inherits anchor :visited colour)

## Screenshot

![image](https://user-images.githubusercontent.com/2741678/31889065-62c1fdb4-b7f6-11e7-977f-9b8adeaee826.png)

**Comment by noahlvb** [comment]
I'll take a look at this one.

**Comment by Caleb-Ellis** [comment]
This has been fixed as of 1.7.0
