### ISSUE TITLE
h5 - line-height and margin-top not matching values defined in docs 

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1403]
## Process
1. Open https://docs.vanillaframework.io/en/base/typography
2. Inspect an h5 element

## Expected result
Values matching docs: 
line-height:28px
margin-top: 32px;

## Current result
line-height:22.868px;
margin-top: 0;

## Screenshot
![image](https://user-images.githubusercontent.com/2741678/31938768-5ed7f4be-b8b0-11e7-9910-e5ae42a67cba.png)

Note: this may not be an isolated occurrence, I'll inspect the full list of heading/paragraph styles and update this issue.

**Comment by Caleb-Ellis** [comment]
@lyubomir-popov have you made more progress on this issue? I've just looked at a couple of the headings in the [hosted docs](https://docs.vanillaframework.io/en/base/typography) and [design docs](https://github.com/ubuntudesign/vanilla-design/blob/master/Typography/typography.md) and have noticed a lot of discrepancies.

**Comment by lyubomir-popov** [comment]
No, I am working on something related, but as a separate, bigger proposal.

**Comment by lyubomir-popov** [comment]
resolved in 1.7.0, closing
