### ISSUE TITLE
Create a Kubernetes secret containing HTTPS certificates for docs.vanillaframework.io

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#1420]
Copy the existing TLS certs for docs.vanillaframework.io into a Kubernetes secret that can be used by the ingress configs.

*or*, consider whether it might be worth asking IS to manage this domain (and thus create the certs & secret for us), just so we don't need to worry about certificate renewal...

**Comment by WillMoggridge** [comment]
https://portal.admin.canonical.com/107225
