### ISSUE TITLE
Go live: Update DNS to point docs.vanillaframework.io at the Kubernetes ingress

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#1422]
I believe we control the DNS. When (and only when) we've confirmed that the Kubernetes environment is correctly able to serve docs.staging.vanillaframework.io and docs.vanillaframework.io, with correct HTTPS certificates, then we should switch over DNS to point to Kubernetes.

**Comment by WillMoggridge** [comment]
The DNS change has been requested.
