### ISSUE TITLE
Accordion pattern does not appear to work with a single panel

### ISSUE THREAD

**Issue by squidsoup** [vanilla-framework/vanilla-framework#1423]
## Process

1. Create an accordion pattern with only one panel
2. Click on the panel tab to open the panel, which correctly opens the panel.
3. Click on the panel tab to close the panel.

## Expected result

I would expect the panel to close.

## Current result

The panel does not close.

**Comment by anthonydillon** [comment]
@squidsoup thank you very much for taking the time to report this issue. The Vanilla team will strive to have a fix for this shortly.
