### ISSUE TITLE
In Firefox link external icon is misplaced when next to <br>

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1426]
## Process

When external link is followed by `<br/>` its icon is misplaced in Firefox (probably because of margin applied to `<br>` by `*+*` rule).

Example code:

```html
  <p>
    <a class="p-link--external">Test</a><br>
    <a class="p-link--external">Test</a>
  </p>
```

Result:
<img width="58" alt="screen shot 2017-11-09 at 16 58 04" src="https://user-images.githubusercontent.com/83575/32615231-86913832-c56f-11e7-86bc-88747f9f8f52.png">

See example (in Firefox): https://jsfiddle.net/4t8Ljm5v/

## Expected result

Icon should be placed next to the link.

**Comment by bartaz** [comment]
I found a workaround that adding `u-no-margin` to <br> fixes it.
But this shouldn't be needed.

**Comment by kwm14** [comment]
### Notes from Working group meeting

- investigate and fix
