### ISSUE TITLE
Remove width:100% on buttons.

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1427]
## Issue Template

You can use this template to raise two different types of issue. Please choose the appropriate section and delete the other section.

# 2. Pattern proposal/amendment
## Is this a proposal or an amendment?
- Amendment - Button
Currently, buttons snap to full-width on screens smaller than 768px. This is not ideal for short buttons [    OK    ] for example, or when you have more than one button. Proposal - either set a breakpoint where width becomes auto on a much smaller resolution (480px?), or remove width: 100% altogether.

## Visual

Provide a screenshot or link to prototype of your pattern proposal.
![image](https://user-images.githubusercontent.com/2741678/32719872-ba785972-c859-11e7-87d4-2d7f4a530102.png)
![image](https://user-images.githubusercontent.com/2741678/32720266-ebef0c16-c85a-11e7-8f06-321095f12d0c.png)

## Context

No change to current context

## State

No change

## Progressive enhancement

No change

**Comment by kwm14** [comment]
Agreed in Working group to remove width: 100% from buttons on breakpoints 768px and 640px.

**Comment by michaelb17** [comment]
Apologies for not being present in the meeting. But I think removing the 100% CTA stretch completely presents a few accessibility issues on the smaller mobile breakpoints. Could we not simply reintroduce it just for the 'x-small breakpoint' (460px)?

**Comment by lyubomir-popov** [comment]
Don't mind having it on vertically held phones. Might be worth discussing whether it should be a default or a utility, as in different contexts different factors might make either preferable. (For example, in an app [    Ok    ] [    Cancel    ] might be better off on the same line). But given that this adds complexity, and that my main issue is full width on tablets, I'm happy either way.

**Comment by kwm14** [comment]
Reference of @michaelb17 update to button width on x-small breakpoint discussed in Design patterns fortnightly [here](https://github.com/ubuntudesign/meeting-notes/issues/205).
