### ISSUE TITLE
Have a base .p-icon

### ISSUE THREAD

**Issue by Lukewh** [vanilla-framework/vanilla-framework#1432]
## Is this a proposal or an amendment?

- Amendment

Add base `.p-icon` containing only the positioning and sizing. Currently there's only `.p-icon--[icon]`. 

dashboard.snapcraft.io has legacy icons that currently have no replacement. They do however currently have background-images set by classes:

`.b-revision-summary_state_unpublished {
    background-image: url(/static/dist/img/icon_approved.svg);`

So I'm getting around this like so:

`<i class="p-icon--question b-revision-summary_state_unpublished"></i>`

Some icons/ text may also be smaller sizes so adding a `vertical-align: middle;` wouldn't go amiss.

**Comment by kwm14** [comment]
Agreed in working group:

- Implement .p-icon as discussed by @Lukewh above
