### ISSUE TITLE
.p-table-compact

### ISSUE THREAD

**Issue by Lukewh** [vanilla-framework/vanilla-framework#1433]
# Proposal

## Visual

https://codepen.io/Lukewh/pen/jaGErR

## Context

MAAS already uses more compact tables, however dashboard.snapcraft.io requires some in-card tables and the current full-spaced tables are visually too spacey©.

**Comment by kwm14** [comment]
Agreed in working group:

- +1 from team
- update .p-table default to match design spec [here](https://github.com/ubuntudesign/vanilla-design/blob/master/Table/table.md)
- .75rem vertical padding
