### ISSUE TITLE
Missing top outline inconsistently

### ISSUE THREAD

**Issue by sparkiegeek** [vanilla-framework/vanilla-framework#1436]
## Process

1. Navigate to forms pattern
2. Click in a field which is in the first "row" of the form (e.g. Full name in https://docs.vanillaframework.io/en/patterns/forms )

## Expected result

Field has a blue outline around the entire field in all supported browsers.

## Current result

In Firefox Quantum (57.0) I see the top edge is missing in both Full name fields (inline and stacked).

It's present in Chromium on the inline Full name, but not the address (which is in error).

## Screenshot

![image](https://user-images.githubusercontent.com/246192/32958852-9a872cb8-cbb7-11e7-82f9-691a734dd9ad.png) <- the 'fox

**Comment by anthonydillon** [comment]
Thanks for this @sparkiegeek I think I know what is happening here. The inline form input is translated up to align with the label which is being cut off by the example iframe.
