### ISSUE TITLE
.p-action-menu

### ISSUE THREAD

**Issue by Lukewh** [vanilla-framework/vanilla-framework#1440]
# Proposal

## Visual

https://codepen.io/Lukewh/pen/PORMpP

## Context

This pattern is currently used in MAAS and will be used in snapcraft.io for snap-level actions for both creators and reviewers of snaps.

## State

There is an open and closed state, activated by clicking. I have not implemented a 'click outside' as part of the prototype and I'm happy for the pattern to be on hover (though hovers can get a bit wild if loads of things open and close).

There are also 'sections' delimited by a bottom border - some extra rules need to be defined to avoid double borders.

A '--destructive' modifier is also included for a more obvious visual cue.

## Progressive enhancement

The pattern should work on smaller screens as-is, but may need some additional work.

Thank you for your time and consideration when looking at the proposal.

1 love, nay, 5 love. xox

**Comment by Greggless** [comment]
🐴  nay nay 🏇

**Comment by Greggless** [comment]
When considering using this element, refer to [this discussion](https://github.com/ubuntudesign/meeting-notes/issues/205) for appropriateness

🐧

**Comment by kwm14** [comment]
Agreed in working group:

- Use Vanilla contextual menu for now

**Comment by kwm14** [comment]
If we need to relook/update at our current contextual menu to cater for this use case we will revisit Luke's proposal.
