### ISSUE TITLE
Table: Remove last border-bottom

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1454]
# 2. Pattern proposal/amendment

## Is this a proposal or an amendment?
- Amendment

If amendment, what is the name of the pattern to be amended?
Table
## Visual
<img width="1091" alt="screen shot 2017-11-27 at 13 58 35" src="https://user-images.githubusercontent.com/2741678/33270199-1d17bf1a-d37b-11e7-8d3e-b1680061b9b8.png">

Example: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/permissions_reference
Provide a screenshot or link to prototype of your pattern proposal.

## Context

No change to context

## State

Stateless

## Progressive enhancement
No change

**Comment by Lukewh** [comment]
Already tracked here:

https://github.com/vanilla-framework/vanilla-framework/issues/1441
