### ISSUE TITLE
Base button does not work well on dark background

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1491]
Currently the color of the button is set to dark which when on a dark background needs to be light and when hovered needs to set the color to dark as the background changes to white. 

The transition is only on the background color so makes the text colour jump. Also, hover and focus should trigger the animation.

Here was my work around in https://www.ubuntu.com/resources:
```sass
.is-dark .p-button--base {
  @include vf-animation(
    $property: all,
    $duration: fast,
    $easing: in
  );
  color: $color-x-light;

  &:hover {
    color: $color-dark;
  }
}
```

**Comment by kwm14** [comment]
@anthonydillon is this still an issue? I can't see the work around on  https://www.ubuntu.com/resources

**Comment by anthonydillon** [comment]
Looks good now. Thanks.
