### ISSUE TITLE
Tabs with labels

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1492]
I have used the tabs component on https://www.ubuntu.com/resources. These tabs needed a label to describe them so I created an extra element to the tab component which is `.p-tabs__label` which doesn't add a border to the bottom when hovering and removed the right padding as it doesn't need to display the border.

```sass
.p-tabs {
  &__label {
    @extend .p-tabs__link;
    padding-left: 0;

    &:hover {
      border-bottom: 0;
    }
  }
}
```

**Comment by kwm14** [comment]
## Agreed in working group
- one time use case so won't be proposed to Vanilla
- proposed change to design remove label and update **All** to **All topics**
