### ISSUE TITLE
Bad formatting of news titles on LXD website

### ISSUE THREAD

**Issue by stgraber** [vanilla-framework/vanilla-framework#1519]
Example: https://linuxcontainers.org/lxd/news/

The expected rendering is:
    LXD 2.21 release announcement (non-wrapped)
    20th of December 2017 (smaller, non-wrapped)

The timestamp uses class="text-muted" which is probably meaningless for vanilla, so this would need to be changed to achieve the expected rendering.

**Comment by anthonydillon** [comment]
Thanks for pointing this out. This is another case were muted text maybe required. The reason we have resisted so far, is for accessibility. Muted text or small grey text can become unaccessible in situations where the background is light grey. We tend to rely on `<small>` to reduce the font-size.

I think in the example the fix would be to reduce the font-size and drop the date onto its own line. I am happy to create a PR for this.

**Comment by stgraber** [comment]
Yeah, I think that'd be fine
