### ISSUE TITLE
Detailed step list content has no horizontal padding

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1523]
The detailed step list has lost its padding which is only visible when on a none white background:
![screenshot-2018-1-17 lists documentation](https://user-images.githubusercontent.com/1413534/35035092-e38091fc-fb78-11e7-940c-7cbbfcbe4dab.png)

This is visible on ubuntu.com:
https://www.ubuntu.com/download/cloud/try-openstack

**Comment by Caleb-Ellis** [comment]
Closing as it was decided in an earlier design review to have the instruction blocks inherit background colour (so padding is unnecessary).
