### ISSUE TITLE
Docs: Use flex to reorder the content and TOC on small screens

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1531]
Please use flex to change the order of the table of contents and the main content. I think it makes more sense to have the TOC above the content.

![screenshot-2018-1-23 breakpoints settings documentation](https://user-images.githubusercontent.com/1413534/35267361-ee10fc5c-001d-11e8-8dae-7a660cb0bb83.png)

**Comment by Caleb-Ellis** [comment]
### Design requirements from @kwm14 
- From top to bottom: header nav, documentation nav, pattern heading, TOC, content

**Comment by kwm14** [comment]
## Visual reference
![docs-toc-structure](https://user-images.githubusercontent.com/17748020/35326052-677b8f9c-00ed-11e8-9324-a787e8619b6e.png)

**Comment by anthonydillon** [comment]
This is not easy because the main content is auto generated. So no CSS way
of injecting it into the main content. We can swap the order of the
navigation, main content and the TOC.

**Comment by kwm14** [comment]
@anthonydillon request has been fixed. But @kwm14 proposal is not possible and requires Javascript 👎
