### ISSUE TITLE
Create a small button

### ISSUE THREAD

**Issue by spencerbygraves** [vanilla-framework/vanilla-framework#1559]
## Amendment

Buttons

## Context

It might be useful to have a smaller button size, which could also be used for the search box and form fields.

- The search box looks cramped in the [navigation bar](https://vanilla-framework.github.io/vanilla-framework/examples/patterns/search-box/navigation/)
- The tabs menu needed to be adjusted on the [resources page](https://www.ubuntu.com/resources)
- Jujucharms.com has a button in the header
- Might be useful in tables?

## Design TBC

![image](https://user-images.githubusercontent.com/9105999/35633386-00f9d256-06a1-11e8-814c-c86de5793c14.png)

**Comment by kwm14** [comment]
## Agreed in working group

- will it be a modifier or utility class
- @spencerbygraves @kwm14 to look at design spec
- explore different layouts
- buttons/forms/navigation/search box

**Comment by kwm14** [comment]
Design spec to be created before build can begin.

**Comment by Caleb-Ellis** [comment]
Issue moved to [ubuntudesign/vanilla-design #252](https://github.com/ubuntudesign/vanilla-design/issues/252) via [**ZenHub**](https://www.zenhub.com/)
