### ISSUE TITLE
Margin-top on Fieldset component is incorrect

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1560]
## Process

Space between consecutive field sets are incorrect.
1. Navigate to https://docs.vanillaframework.io/en/base/forms#fieldset
2. Design spec https://github.com/ubuntudesign/vanilla-design/blob/master/Forms/forms.md

## Expected result
- margin-top: `$sp-large`

## Current result
- margin-top: 20px;

**Comment by Caleb-Ellis** [comment]
@kwm14 At the moment it's using the default vertical spacing (1.25rem small, 1.75rem medium, 2rem large) - are we saying set it to 1.5rem for all cases?

**Comment by Caleb-Ellis** [comment]
@kwm14 as decided we will keep default vertical spacing
