### ISSUE TITLE
Select boxes should have right padding to mask the arrow

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1563]
Currently the text in a select box goes under the arrow in a check box. The check box needs padding on the right so the text in the option can not be seen under the arrow.

**Comment by cbrownstein** [comment]
Is there somewhere this bug can be seen in action? I'm interested in trying to fix it. Thanks.

**Comment by anthonydillon** [comment]
Yeah sure, sorry I should have put an example in the issue.
https://codepen.io/anthonydillon/pen/mXLWVj
Here you see the text in the select is going under the arrow on the right. There should be right padding so that the text does not touch the arrow.
