### ISSUE TITLE
Margin-right on social icons using incorrect value

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1570]
## Process

1. Navigate to https://docs.vanillaframework.io/en/patterns/icons#social-icons
2. Design spec https://github.com/ubuntudesign/vanilla-design/blob/master/Icons/social-icons.md

## Expected result
- margin-right - `1rem`

## Current result
- margin-right - `1.25rem`

**Comment by Caleb-Ellis** [comment]
This isn't an issue with the social icons, just that the example has the icons in a `p-inline-list` which have `margin-right: 1.25rem`. By themselves the social icons have no margin at all and instead they are defined by whatever container they are in (in example it's an inline list). I also don't think we should have a separate pattern specific to social icons (eg. `.p-list--social`) so I'm closing this for now.
