### ISSUE TITLE
Margin bottom on Modal component title using incorrect value

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1578]
## Process
1. Navigate to https://docs.vanillaframework.io/en/patterns/modal
2. Design spec https://github.com/ubuntudesign/vanilla-design/blob/master/Modal/modal.md

## Expected result
- title margin-bottom:  `1.5rem`

## Current result
- title margin-bottom: `28px`

## Screenshot
![screen shot 2018-02-07 at 12 33 20](https://user-images.githubusercontent.com/17748020/35916901-ed33af90-0c03-11e8-8c3e-3e1efbeb01cd.png)

**Comment by Caleb-Ellis** [comment]
This is using default Vanilla vertical spacing (which is in the process of being completely revamped). Closing for now.
