### ISSUE TITLE
Header misnamed as “Global navigation”

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1591]
1\. Go to docs.vanillaframework.io.
2\. Try to find the header pattern.

What happens: It’s disguised as “Global navigation” in the contents, and “Navigation” in the pattern description.

What should happen: It’s called “Header”.

Calling the header “Global navigation” makes it needlessly hard to find. It also implies that a Footer and an Accordion can’t be global navigation, when they can be.

**Comment by kwm14** [comment]
Updated in latest release v1.7.0 to 'Navigation' agreed with @Caleb-Ellis and @anthonydillon

**Comment by matthewpaulthomas** [comment]
Unfortunately, renaming “Global navigation” to “Navigation” makes this issue worse, not better. Consider @kwm14 [in #1655](https://github.com/vanilla-framework/vanilla-framework/issues/1655#issuecomment-389814141):
> - do we keep the search in the sidebar navigation or add the search into the navigation?

That’s a realistic question for developers of a Vanilla-using site to ask each other. But to understand it, you need to know and recall that:
- in the phrase “sidebar navigation”, the word “navigation” means links for navigating
- in the phrase “the navigation”, the word “navigation” means header.

For a new Vanilla user, this is needlessly difficult, and could easily be fixed by renaming the pattern to “Header”.

**Comment by kwm14** [comment]
@matthewpaulthomas in regards to the "Sidebar navigation" this component will be deprecated in due course so we don't need to worry about this component 😄 

But I disagree that "Navigation" makes it worse and i don't think that "Header" is a better alternative. 

Having looked at other CSS design frameworks to see how they name a similar component I think we were right in updating it to "Navigation".

- Lightning Design - "[Global navigation](https://www.lightningdesignsystem.com/components/global-navigation/#site-main-content)"
- Trello - "[Global navigation](https://design.trello.com/components/navigation)"
- Ant Design - "[Top navigation](https://ant.design/docs/spec/navigation#Top-Navigation)"
- Material Design - "[Navigation](https://material.io/design/navigation/understanding-navigation.html#types-of-navigation)"

The only example case of using "Header" was IBM's design system.
- Carbon Design System - "[Cloud Header](http://carbondesignsystem.com/add-ons/cloud-header/code)"

**Comment by matthewpaulthomas** [comment]
> in regards to the "Sidebar navigation" this component will be deprecated in due course so we don't need to worry about this component

I didn’t know the sidebar was a component (the docs don’t list it as one), but that’s not relevant to the problem of “navigation” referring to multiple things.

> - Lightning Design - "[Global navigation](https://www.lightningdesignsystem.com/components/global-navigation/#site-main-content)"
> - Trello - "[Global navigation](https://design.trello.com/components/navigation)"
> - Ant Design - "[Top navigation](https://ant.design/docs/spec/navigation#Top-Navigation)"
> - Material Design - "[Navigation](https://material.io/design/navigation/understanding-navigation.html#types-of-navigation)"

Thanks for those examples! They demonstrate another problem with the name “Navigation”: navigation is only _one_ of the things found inside this component. Trello is the only one that uses the term to refer to the bar as a whole. The Lightning page begins “Global Navigation is the list of navigation links your users find _in the Header_” (alongside [search](https://www.lightningdesignsystem.com/guidelines/search/global/) and a “[global actions bar](https://www.lightningdesignsystem.com/components/global-header/#Global-Actions-Bar)”), Ant distinguishes “Top Navigation” from other kinds, and Material’s equivalent component is the [top app bar](https://material.io/design/components/app-bars-top.html#usage) which “is used for “used for branding, screen titles, navigation, and actions”.

Similarly in Vanilla, the header contains navigation, search, and sometimes an account menu. Naming the header after one of the things inside it is called [synecdoche](https://literarydevices.net/synecdoche/). It’s a fun literary technique, but not the clearest thing to do when naming something technical.
