### ISSUE TITLE
Context menu stays open when clicking elsewhere

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1593]
1\. Go to [the page for context menus](https://docs.vanillaframework.io/en/patterns/contextual-menu) (which Vanilla oddly calls “contextual menus”).
2\. In the example section, click one of the “Link” links.
3\. Click anywhere else.

What happens: The menu stays open.

What should happen: The menu closes — as it does in Ubuntu, Windows, macOS, and the “More” menu on [www.ubuntu.com](https://www.ubuntu.com/).

One example of why this is bad: it can result in multiple menus open at once, even overlapping each other.

![vanilla-framework 1593 multiple menus](https://user-images.githubusercontent.com/19801137/36303244-5f0fbaae-1303-11e8-9657-e70cf3790985.png)

**Comment by kwm14** [comment]
Agreed with @Caleb-Ellis @anthonydillon you need to listen to the `<body>`.
