### ISSUE TITLE
Proposal: p-card--post / p-card--featured

### ISSUE THREAD

**Issue by Caleb-Ellis** [vanilla-framework/vanilla-framework#1594]
## Proposal

We have a new card type that's being used in three places at the moment:
- the new Insights site,
- www.ubuntu.com/resources,
- developer.ubuntu.com (currently unreleased, but the changes are on master)

I think we can either:
1. Add a modifier to the base card pattern, something along the lines of `.p-card--post` or `.p-card--featured`, or
2. Replace the current `.p-card--highlighted` with this new styling (which is actually an extension of highlighted at the moment)

## Screenshots
Example on insights:
![screenshot_3](https://user-images.githubusercontent.com/25733845/36375084-c427f6f4-1565-11e8-9d77-366138ae7d3b.png)

Example on /resources:
![screenshot_2](https://user-images.githubusercontent.com/25733845/36375092-cc9fa62e-1565-11e8-9a81-127ea222ce69.png)

**Comment by kwm14** [comment]
## Agreed in WG
- add top-border modifier to _Basic card_ component
- @anthonydillon to follow up with further details

**Comment by anthonydillon** [comment]
Implementation variants:
```
<div class="p-card--top-border">
```
or
```
<div class="p-card is-top-bordered">
```
We could create a map for a function in Vanilla to create custom card categories.
```
<div class="p-card--top-bordered is-phone">
```
or
```
<div class="p-card is-bordered" data-category="phone">

**Comment by kwm14** [comment]
It's available to build using `highlight-bar` mixin 💯
