### ISSUE TITLE
Proposal - p-stepped-list--detailed amendment

### ISSUE THREAD

**Issue by Caleb-Ellis** [vanilla-framework/vanilla-framework#1595]
## Amendment

I think there is too much empty space with the current detailed stepped list, in regards to the step titles. Currently, there is a 50/50 split between the step title/content, and I think it would look nicer more as a 40/60 split. I think adding a border helps with readability also.

## Screenshots
Current 50/50 split:
![screenshot_4](https://user-images.githubusercontent.com/25733845/36375472-4406c4e4-1567-11e8-8cdc-ce51e6e3b93b.png)

Proposed 40/60 split:
![screenshot_5](https://user-images.githubusercontent.com/25733845/36375486-566788f8-1567-11e8-9fe5-f501e88ad563.png)

Proposed 40/60 split with border
![screenshot_6](https://user-images.githubusercontent.com/25733845/36375499-62e02e46-1567-11e8-835a-ffa4d76dc3fb.png)

**Comment by kwm14** [comment]
## Agreed in WG
- review stepped-list and step-detailed-list
- look at pattern use cases on our sites
- https://github.com/search?l=HTML&q=org%3Acanonical-websites+p-stepped-list--detailed&type=Code

**Comment by kwm14** [comment]
No longer valid.
