### ISSUE TITLE
Remove flex from Matrix content

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1596]
The `.p-matrix__content` element has `display: flex` which I don't think it needs. This is causing the pattern to be broken on IE 11.
![problem](https://user-images.githubusercontent.com/1413534/36419024-b45393be-1628-11e8-951f-4cd603cc5c7b.png)

**Comment by Caleb-Ellis** [comment]
Fixed in 1.7.0

## Screenshot from IE11

![screenshot_1](https://user-images.githubusercontent.com/25733845/40243472-39b9e124-5ab8-11e8-9ce7-2086e461d061.png)
