### ISSUE TITLE
Dark "Global navigation" pattern issues

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1604]
It is possible to change color of the header with `$color-navigation-background` variable and Vanilla correctly detects dark colours and changes text colour based on that.

But navigation items hover style and `is-selected` borders are not affected and are not configurable.
This makes dark headers not usable (especially because of hover):

<img width="1057" alt="screen shot 2018-02-28 at 15 27 57" src="https://user-images.githubusercontent.com/83575/36792992-6e82e7de-1c9c-11e8-8846-6bc7647017fd.png">

### Expected result

Hover and selected styles should adapt to dark backgrounds.
Ideally all of navigation colours (background, text, hover, borders, selected) could be configurable.

**Comment by kwm14** [comment]
Thanks for reporting @bartaz. This will be fixed soon as @Caleb-Ellis is working on updated navigation styles in the coming weeks 👍

**Comment by deadlight** [comment]
The exact behaviour in this bug report is no longer the case but the default navigation still has some flaws when a dark colour is used.

I have fixed the invisibility of the on-hover state of nav items in this PR: https://github.com/vanilla-framework/vanilla-framework/pull/2072
