### ISSUE TITLE
logo clouds have bad aspect ratios

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-framework#1605]
## Process

1. go to www.ubuntu.com/containers
2. see the the docker and k8s logos are squashed

## Expected result

- all logos with correct aspect ration

## Current result

https://codepen.io/pmahnke/pen/jZdxRG

## Screenshot

![image](https://user-images.githubusercontent.com/441217/36836157-7883737c-1d30-11e8-8c76-b5d3f861dc2c.png)

##  Possible solution

https://codepen.io/pmahnke/pen/zReaOM

or on beta.ubuntu.com

**Comment by kwm14** [comment]
@pmahnke happy with your solution of setting a max-height. @spencerbygraves had a similar issue when reviewing this [issue](https://github.com/canonical-websites/www.ubuntu.com/pull/2752). I believe he also asked Caleb to set a max-height for consistency.

**Comment by kwm14** [comment]
Agreed this isn't a Vanilla issue.

We as designers @spencerbygraves @kwm14 @anasereijo @lyubomir-popov need to do an audit of all Cloud logos and update to @lyubomir-popov new logo alignment template 👍

**Comment by kwm14** [comment]
@lyubomir-popov yes it's been fixed in Vanilla, but the markup inside the SVG's are broken 😠
