### ISSUE TITLE
Incorrect values used for box-shadow on Tabs component

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1614]
## Process

Incorrect values used for box-shadow on Tabs component.

1. Navigate to https://docs.vanillaframework.io/en/patterns/tabs
2. Design spec https://github.com/ubuntudesign/vanilla-design/blob/master/Tabs/tabs.md

## Expected result
- box-shadow: `0, 1px, 2px, 0px;`

## Current result
- box-shadow: `0, 1px, 5px, 1px;`

**Comment by barrymcgee** [comment]
@kwm14 This is inherited from `.p-card--highlighted` - can I assume the box-shadow value is incorrect there at source?

**Comment by kwm14** [comment]
@barrymcgee ah ok we noticed that when doing the audit yesterday. Yes it probably is, I haven't reviewed the design spec for Cards yet.
