### ISSUE TITLE
Muted table headers

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1621]
# 2. Pattern proposal/amendment

Tables headers are currently weight 400, which makes them quite strong. This may be desirable in a situation like a pricing table, where you would want product names to stand out, but is on one hand unnecessary in more complex tables (like MAAS machine summary), and on another hand problematic in cases when that table turns into a card on mobile. This issue is exacerbated when the table is made dense, as in tightly packed situations, the bold limits how much we can condense things vertically without things becoming claustrophobic. A few examples:

## OK when:
• the items in the header are few
• they need to stand out when you skim a page you rarely visit:

![image](https://user-images.githubusercontent.com/2741678/37403353-73877a8e-2786-11e8-9a8b-cf22241ded30.png)

(https://www.ubuntu.com/support/plans-and-pricing)

## Questionably useful when:
• the part of the page you're scanning is the actual table body, while the table headers are very familiar to you:

![image](https://user-images.githubusercontent.com/2741678/37406162-6880be68-278e-11e8-8c16-3f047f60728a.png)

## Problematic when:

• tables turn into a (dense) card, because following the line from key (label on the left ) to value (on the right) is not only difficult because of the space in between, but also because bold lables focus your attention on something static and familiar, and away from the actual changing values.

![image](https://user-images.githubusercontent.com/2741678/37404268-492b5bb8-2789-11e8-99af-298bc6ea6114.png)

• Reducing the distance, which makes it easier to identify key-value pairs, also makes it look even more unbalanced:

![image](https://user-images.githubusercontent.com/2741678/37404556-1d40d46e-278a-11e8-9522-caab0d538f01.png)

• and because further optimising the layout to make much more compact use of space becomes impossible:

![image](https://user-images.githubusercontent.com/2741678/37404606-41845012-278a-11e8-9338-7638af93db7c.png)

## How do other design systems treat table headers?
For comparison, pls consider the following examples of less prominent headers in complex tables:

![image](https://user-images.githubusercontent.com/2741678/37403800-f10ee9a0-2787-11e8-95b1-24757ff25800.png)

![image](https://user-images.githubusercontent.com/2741678/37403818-fb1c04aa-2787-11e8-915f-825543ffda64.png)

![image](https://user-images.githubusercontent.com/2741678/37403852-113a642a-2788-11e8-8891-c112d99e9d78.png)

(the single column ui here is considered a table, details here https://developer.apple.com/ios/human-interface-guidelines/views/tables/)

## Is this a proposal or an amendment?

- Amendment

If amendment, what is the name of the pattern to be amended?

Table

### Before: 
![image](https://user-images.githubusercontent.com/2741678/37404808-d702b872-278a-11e8-87d3-a93fa9e6a4db.png)

### After:
![image](https://user-images.githubusercontent.com/2741678/37404948-39d80470-278b-11e8-95ca-5af163643c35.png)

## Context

In what context will the pattern be used?
Either the current context - everywhere, or added as an option available to use depending on context, as in apps.

## State

No change

## Progressive enhancement

A pattern should be designed small screen first. How does this pattern scale up?
How will this pattern degrade on less competent browsers?

This enhancement is proposed particularly with small screens and dense scenarios in mind. Also very relevant to complex, large scale scenarios like maas.

**Comment by lyubomir-popov** [comment]
@kwm14 @spencerbygraves I've filed a proposal for muted table headers, maybe something we can discuss in the next design meeting too.

**Comment by kwm14** [comment]
## Design review
_attendees: @lyubomir-popov @spencerbygraves_ 

- Lyubo ran through his proposal on MAAS
- Myself and Spencer approve updated design
- Lyubo to generate PR which will be reviewed by Ant before pushing to Vanilla

**Comment by Caleb-Ellis** [comment]
This is now included in 1.7.0
