### ISSUE TITLE
Change in height of global navigation header between desktop and mobile

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1622]
## Process

Global navigation header height from desktop should retain through to mobile version.
1. Component: https://docs.vanillaframework.io/en/patterns/navigation
2. Design spec: https://github.com/ubuntudesign/vanilla-design/blob/master/Navigation/navigation.md

## Expected result
- Desktop navigation bar height: `48px`
- Mobile navigation bar height: `48px`

## Current result
- Desktop navigation bar height: `48px`
- Mobile navigation bar height: `56px`

## Screenshot
**Desktop** 
![screen shot 2018-03-14 at 16 48 43](https://user-images.githubusercontent.com/17748020/37417284-c82ddd0a-27a7-11e8-8268-641a957919a6.png)

**Mobile**
![screen shot 2018-03-14 at 16 48 30](https://user-images.githubusercontent.com/17748020/37417306-d5f79d36-27a7-11e8-9e49-b87b53b54d0c.png)

**Comment by kwm14** [comment]
Updates blocked until Vanilla spacing PR has landed.

**Comment by Caleb-Ellis** [comment]
Fixed as of 1.7.0 release
