### ISSUE TITLE
Spacing issues in footer in Firefox

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1626]
## Process

[ordered list the process to finding and recreating the issue, example below]

1. Have some paragraphs with inline links in footer, for example: https://jsfiddle.net/tdjcz8h3/1/
2. View it in Firefox
3. Links have unnecessary top margin causing unnecessary spacing

<img width="521" alt="screen shot 2018-03-16 at 09 57 40" src="https://user-images.githubusercontent.com/83575/37511830-8793b1b6-2900-11e8-93f2-26612887ee3e.png">
<img width="651" alt="screen shot 2018-03-16 at 09 47 36" src="https://user-images.githubusercontent.com/83575/37511831-87b1239a-2900-11e8-9537-26e91a9f6942.png">

This seems to be caused by `* + *` margin rule being applied to links.

## Expected result

There should be no unnecessary margins over links.

**Comment by bartaz** [comment]
To work around this issue we needed to remove margin both on `a` and `br`, because it seems that `* + *` rule was applied to `br` as well and even though this margin was not 'visible' in debugging tools it was breaking the layout.

See fix for snapcraft.io: https://github.com/canonical-websites/snapcraft.io/pull/403/files

**Comment by anthonydillon** [comment]
Thanks again, this should be set.

**Comment by Caleb-Ellis** [comment]
With the `* + *` rule being removed in 1.7.0 this should no longer be an issue
