### ISSUE TITLE
Margin top on br in Firefox

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1627]
Go to: https://snapcraft.io/spotify
There is unnecessary spacing on bullet points, because Vanilla adds top margin to `br`.

Related to: #1626

Also reported in snapcraft: https://github.com/canonical-websites/snapcraft.io/issues/405

What you see in Chromium: | What you see in Firefox:
-|-
![snapcraft io spotify description chromium](https://user-images.githubusercontent.com/19801137/37516792-40c21190-2907-11e8-9450-2f44b1592885.png) | ![snapcraft io spotify description firefox](https://user-images.githubusercontent.com/19801137/37516793-4123d93e-2907-11e8-803b-fa22cd963f89.png)

What you should see: The description in Firefox should not have all the extra line spacing.

**Comment by anthonydillon** [comment]
Thanks @bartaz. `<br/>` should has a set margin.

**Comment by anthonydillon** [comment]
Tested and this is no longer an issue in the new 1.7.0-beta which has landed.
