### ISSUE TITLE
Consider filesize implications of omitting BEM block class in markup

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1629]
# 2. Pattern proposal/amendment
Currently, rules that would go into a .block-class {} e.g. .p-notification {}, are included via a mixin into each modified version of the block class, e.g.:
.p-notification--positive
.p-notification--caution
.p-notification--negative
.p-notification--information

The impact of that is illustrated in the following two screenshots of the generated styles in build.css –

As we have it (86 lines):
![image](https://user-images.githubusercontent.com/2741678/37596101-f611467a-2b72-11e8-8543-d4e798a4714c.png)

As BEM would have it (47 lines):
![image](https://user-images.githubusercontent.com/2741678/37596240-70a032de-2b73-11e8-96f7-c24082b02a61.png)
Just wanted to raise the question as we're looking to cut down on file size. Not sure how tricky this is in practice - as it will require injecting the block class name next to the block--modifier class name in the markup on every site that uses vanilla. Maybe it is a simple search and replace / regex match and replace, maybe not.

**Comment by kwm14** [comment]
## Agreed in working group
- use placeholders instead mixins
- this work will start once audit is complete

**Comment by kwm14** [comment]
After the recent release of v1.7.0 we now use `placeholders`.
