### ISSUE TITLE
Border on small screen active navigation items

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1630]
The active navigation item in the global navigation on small screens has a border bottom as it does on large screens. I think we need a different pattern/style for small screens.

For example, check out this example on small screens:
https://vanilla-framework.github.io/vanilla-framework/examples/patterns/navigation/default/#navigation

**Comment by kwm14** [comment]
@anthonydillon currently exploring a new design for our global navigation including hover/selected state of menu items. Agreed we do need a different solution for mobile.

**Comment by kwm14** [comment]
Closing issue and moving bug report to vanilla-design repo.
