### ISSUE TITLE
“Code snippet” is a confusing name

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1631]
Vanilla has four patterns named with the word “code”: [Inline code and Code block](https://docs.vanillaframework.io/en/base/code), [Code numbered](https://docs.vanillaframework.io/en/patterns/code-numbered), and [Code snippet](https://docs.vanillaframework.io/en/patterns/code-snippet).

Documentation IA aside, “Code snippet” is a confusing name. Its biggest difference from the other three is that it has a Copy button, but this isn’t mentioned in the name. And most often (such as in the Docs themselves) it is used for a terminal command, which might be “code” in a loose sense, but many people using it would not call it that.

I propose that the pattern be renamed to something that clarifies how it is different from the other three patterns. For example:
- Copyable command
- Copyable code
- Field with copy button

**Comment by kwm14** [comment]
@matthewpaulthomas thanks for your feedback 👍 

Agreed with @anthonydillon @Caleb-Ellis that the simplest change would be to update `Code snippet` to `Code copyable`, this will be updated in the documentation and in code 😄
