### ISSUE TITLE
Example frames on “Forms” page are unusably small

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1648]
Chromium 64.0, Ubuntu 14.04

1\. Go to [the Forms page](https://docs.vanillaframework.io/en/base/forms).
2\. Try to view the form, text field, text area, select, or fieldset examples.

What happens: The frame is so small that it’s impossible to view the whole control.
![docs vanillaframework io-forms](https://user-images.githubusercontent.com/19801137/37968747-dc10019e-31c6-11e8-9bc2-a370ace20974.png)

What should happen: The frames are tall enough that you can see _at least_ one control in each.

**Comment by kwm14** [comment]
We need to investigate the issue with example.js. Moving issue to correct repo.

**Comment by kwm14** [comment]
Moved issue [here](https://github.com/canonical-webteam/example-js/issues/31). Closing 💯
