### ISSUE TITLE
Footer pattern should have 14px font-size

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1660]
The footer pattern has lost its font-size. The [spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Footer/footer.md) states that the font-size should be `14px` but its now getting the base font-size which is 16px.

**Comment by Caleb-Ellis** [comment]
Closing as we are going ahead with 16px font in the footer. @kwm14 Spec to be updated. [Link](https://github.com/ubuntudesign/vanilla-design/blob/master/Footer/footer.md)
