### ISSUE TITLE
Header can no longer be contained 

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1661]
If a navigation contains a row it makes both the logo (banner) and navigation (nav) element full width. This is due to the flex being applied to the `p-navigation` which is wiped out when there is a nested `row` div.

For example: https://codepen.io/anthonydillon/pen/rdKGYg

**Comment by lyubomir-popov** [comment]
I've added the relevant rules to .row as well.

**Comment by lyubomir-popov** [comment]
Closing as the pr has been merged
