### ISSUE TITLE
Card Design Documentation 404

### ISSUE THREAD

**Issue by pojntfx** [vanilla-framework/vanilla-framework#1662]
## Process

1. Visit https://docs.vanillaframework.io/en/patterns/card
2. Click on "Card design" link

## Expected result

Get redirected to card design docs

## Current result

404 error on "https://github.com/ubuntudesign/vanilla-design/tree/master/Card"

## Screenshot

![screenshot from 2018-04-02 22-22-17](https://user-images.githubusercontent.com/28832235/38214270-6aa22bec-36c4-11e8-957c-b8aa39190306.png)

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this issue. 

The link should go to Cards not Card. We will update this for the next release.
