### ISSUE TITLE
p-heading--five is inheriting the baseline size of 16px

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1664]
## insights.ubuntu.com upgrade to v1.7.0-alpha-1

Reviewing the beta test branch I noticed that `p-heading--five` is inheriting the baseline grid size of 16px. This is incorrect and should follow what is listed [here](https://docs.vanillaframework.io/en/base/typography).

## Expected result
p-heading--five: `20px`

## Current result
p-heading--five: `16px`

## Screenshot
![screen shot 2018-04-03 at 10 09 27](https://user-images.githubusercontent.com/17748020/38240886-b9bd231c-3728-11e8-8193-b3292223fe07.png)

**Comment by anthonydillon** [comment]
Oh I thought the changes to the typography had been discussed and agreed.

**Comment by kwm14** [comment]
@anthonydillon just discussed with @spencerbygraves and it has been agreed that `p-heading--five` has been updated to use `16px` font-size, I was unaware of this change and thought we'd only updated styling of `p-heading-six`.

Going forward we will have to make sure sites that use `p-heading--five` in hero strips will have to update to `p-heading--four`

**Comment by kwm14** [comment]
## Review
Looking at our current marketing sites it seems that only **ubuntu.com** and **canonical.com** use `p-heading--five` as the font-size in hero sections on site pages. So when we upgrade these sites to v1.7.0 we need to be aware of this.

### Actions
Make sure `p-heading--five` are upgraded to `p-heading--four` across the site when upgraded to v.1.70.
