### ISSUE TITLE
Remove margin-bottom from p-list__item component

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1668]
## insights.ubuntu.com upgrade to v1.7.0-alpha-1
Reviewing the beta test branch I found an example of `p-list_item` that uses margin-bottom: `24px`, which is causing a large amount of white space for under each list item.

Link to issue: http://insights.ubuntu.com-pr-290.run.demo.haus/2018/03/21/kernel-team-summary-march-21-2018

## Current result
![screen shot 2018-04-03 at 11 04 45](https://user-images.githubusercontent.com/17748020/38243288-d9ba91b2-372e-11e8-91cb-fc0eb19cb278.png)

**Comment by anthonydillon** [comment]
To be clear, the 24px `margin-bottom` is coming from the label inside the list item. We may just what to add some logic there to reduce the margin then a label is inside a list.
