### ISSUE TITLE
Hidden object causing content to align center in matrix component

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1670]
## cn.ubuntu.com upgrade to v1.7.0-alpha-1
Reviewing the beta test branch I found an example on /cloud and `p-matrix` content is aligned almost to the center due to a hidden image/logo object. Not sure why this is happening?

Link to issue: http://cn.ubuntu.com-pr-204.run.demo.haus/internet-of-things/

### Current result
![screen shot 2018-04-03 at 15 09 13](https://user-images.githubusercontent.com/17748020/38254377-11969992-3751-11e8-83b4-dd10d854a883.png)

**Comment by kwm14** [comment]
## ubuntu.com upgrade v1.7.0-alpha-1
Same issue but contents wraps around hidden/logo image.

### Current result
![screen shot 2018-04-04 at 16 10 48](https://user-images.githubusercontent.com/17748020/38316602-047ba432-3823-11e8-96e9-e782a78c2388.png)

**Comment by Caleb-Ellis** [comment]
This is due to a `::before` pseudo-element being applied to every matrix item, not that there is an invisible image.
