### ISSUE TITLE
p-button--neutral class applied but styles not displaying on button

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1671]
## conjure-up.io upgrade to v1.7.0-alpha-1
Reviewing the beta test branch I found an example under 'How to contribute to conjure-up' section, button class 'neutral' is applied but the styles aren't displaying.

Link to issue: http://conjure-up.io-pr-30.run.demo.haus/

## Current result
![screen shot 2018-04-03 at 15 35 01](https://user-images.githubusercontent.com/17748020/38255807-af1b5786-3754-11e8-8bef-75d161ded434.png)

**Comment by Caleb-Ellis** [comment]
PR: https://github.com/canonical-websites/conjure-up.io/pull/32

**Comment by kwm14** [comment]
Above PR merged by @steverydz
