### ISSUE TITLE
External link icon with title is not aligned correctly

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1675]
## ubuntu.com v1.7.0-alpha-1
Reviewing the beta test branch. External link icon with title is not aligned correctly, not sure if this is down to the paddings or baseline grid.

Link to issue: http://www.ubuntu.com-pr-2859.run.demo.haus/openstack

## Current result
![screen shot 2018-04-04 at 15 07 37](https://user-images.githubusercontent.com/17748020/38312588-0826e258-381a-11e8-89ce-d6c8eee1bcb1.png)

![screen shot 2018-04-04 at 15 37 58](https://user-images.githubusercontent.com/17748020/38314485-3a467fba-381e-11e8-8ad2-2dc5bd2d55c1.png)

![screen shot 2018-04-04 at 16 08 29](https://user-images.githubusercontent.com/17748020/38316376-82ba97aa-3822-11e8-84c2-9c4503d00923.png)

**Comment by Caleb-Ellis** [comment]
This is an issue with the bespoke styling on ubuntu.com, namely:
- `p-link--external` on header tags
- `p-heading-icon__title--muted`
- `p-heading-icon__img--small`

I will create a PR in the ubuntu.com repo that minimises bespoke styling as much as possible, and fixes the alignment errors

**Comment by Caleb-Ellis** [comment]
Fixed as per https://github.com/canonical-websites/www.ubuntu.com/pull/2934
