### ISSUE TITLE
Pull quote paragraph inheriting line height from heading

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1680]
## ubuntu.com v1.7.0-alpha-1
Reviewing the beta test branch. Pull quote line height is too large for paragraph text, it's looks as if it's  inheriting the line height from the h3 heading above as it's contained within that div.

Issue found here: http://www.ubuntu.com-pr-2859.run.demo.haus/desktop/education

## Current result
![screen shot 2018-04-04 at 17 05 40](https://user-images.githubusercontent.com/17748020/38319802-ae68692e-382a-11e8-9f8d-a3bc057de65a.png)

Same issue seen on desktop/government.

![screen shot 2018-04-04 at 17 09 20](https://user-images.githubusercontent.com/17748020/38319922-03ae586c-382b-11e8-92c4-5a7756ab334b.png)

**Comment by Caleb-Ellis** [comment]
This is an issue with the custom SCSS/markup in the u.com codebase, and should be fixed there.
https://github.com/canonical-websites/www.ubuntu.com/blob/master/static/sass/_pattern_pull_quotes.scss
