### ISSUE TITLE
Header card is misaligned

### ISSUE THREAD

**Issue by spencerbygraves** [vanilla-framework/vanilla-framework#1690]
## ubuntu.com v1.7.0-alpha-1
Reviewing the beta test branch, the image and link are misaligned in the header card.

### Current result
![image](https://user-images.githubusercontent.com/9105999/38370783-d03908fc-38e2-11e8-90d8-e942bbc57537.png)

**Comment by kwm14** [comment]
Duplicate of https://github.com/vanilla-framework/vanilla-framework/issues/1669
