### ISSUE TITLE
Table header has lost padding-top

### ISSUE THREAD

**Issue by spencerbygraves** [vanilla-framework/vanilla-framework#1691]
## ubuntu.com v1.7.0-alpha-1
Reviewing the beta test branch, the table header has lost padding-top. This becomes a problem when the cell is highlighted, as on the [pricing table](http://www.ubuntu.com-pr-2859.run.demo.haus/cloud/foundation-cloud)

Incidentally, the table looks better at 12 col, which also gives more room at smaller sizes.

Issue can be found here: http://www.ubuntu.com-pr-2859.run.demo.haus/support/plans-and-pricing

### Current result
![image](https://user-images.githubusercontent.com/9105999/38371954-a065d512-38e5-11e8-9178-58a50f355fbb.png)

**Comment by kwm14** [comment]
Pr fixed and merged here: https://github.com/canonical-websites/www.ubuntu.com/pull/2950#event-1573409549
