### ISSUE TITLE
Split list isn't splitting by number of elements

### ISSUE THREAD

**Issue by shivjoshi1996** [vanilla-framework/vanilla-framework#1698]
Split lists do not split equally by the number of elements. 

Screenshot: 
![listsplit](https://user-images.githubusercontent.com/33127429/38512129-4bfb016a-3c22-11e8-85a5-c14d120bcefa.png)

The list is split 8/4, whereas it could be evenly split 6/6, making it look nicer.

**Comment by kwm14** [comment]
@shivjoshi1996 good spot and a valid issue to report. We will investigate further on how to solve this issue 👍

**Comment by deadlight** [comment]
The split list component uses css columns that the browser will auto-split into equal-sized chunks of content. Your specific site may need updating to utilise the latest version of the component.

I'm closing this issue; if you think that this is in error, please provide some markup for testing.
