### ISSUE TITLE
Review heading sizes on mobile and decide if reduction on mobile is needed

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1708]
## Issue Template

The headings in 1.7.0-alpha are currently not being reduced on mobile. We need to review and decide if we need to reduce them.

We briefly talked with @spencerbygraves about reducing headings on smaller screens, if I remember correctly we decided to postpone a decision on that until we review all sites and see if it is needed (mainly for simplicity, and the new headings are slightly smaller anyway). I think we should probably discuss this again. If we decide to reduce them, we can reduce the step up the modular scale from 2 to 1 on mobile. For example, currently we have:

Desktop h1(8), h2(6), h3 (4), h4(2), h5,h6,p(1), small(-1)

We can add:

Mobile h1(5), h2(4), h3 (3), h4(2), h5,h6,p(1), small(-1)
Where the number in the parentheses is the power to which the modular scale ratio is raised.

**Comment by kwm14** [comment]
## Design review
attendees: @lyubomir-popov @spencerbygraves @kwm14

- Agreed that Lyubo will create 2 demos showcasing new sizing scale for mobile based on values above

**Comment by kwm14** [comment]
Moving this issue to v1.7.0-beta-1 bug fixes Epic.

**Comment by lyubomir-popov** [comment]
@spencerbygraves @kwm14 @Caleb-Ellis I am currently writing explanations about the modular scale, and realised my explanations are getting complicated :) Which led me to the conclusion that switching ratios between breakpoints might be overcomplicated too. There might be a simpler way to define the mobile/desktop sizes with a double stranded modular scale (which is also arguably the more traditional way of doing it). But to do that it would help if we have some flexibility on the smaller value which is currently 14.

So just wanted to ask – is the assumption that we need small copy to be exactly 14px based on some constraints / requirements or research?
