### ISSUE TITLE
Stepped list doesn't follow correct numerical order/sequence 

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1729]
## v1.7.0-beta-1 review on canonical.com

Stepped list doesn't follow numerical order/sequence of 1,2,3 and 4.
- Issue can be found here: http://www.canonical.com-pr-264.run.demo.haus/services

### Current result
![screen shot 2018-04-16 at 11 03 33](https://user-images.githubusercontent.com/17748020/38803110-20357a9e-4166-11e8-954e-5fdc35b41f63.png)

### Expected result
![screen shot 2018-04-16 at 11 05 54](https://user-images.githubusercontent.com/17748020/38803126-29eba6a8-4166-11e8-92cf-1b5ef9670f62.png)

**Comment by lyubomir-popov** [comment]
In the new vanilla, we have a counter that sets the numbers. Inline spans with numbrs are hidden and can be safely ommitted. The issue here is due to these being two separate lists, rather than one split in two with the relevant pattern.
