### ISSUE TITLE
Logos in inline-images component are warped/distorted

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1732]
## v1.7.0-beta-1 review on cn.ubuntu.com

Kubernetes and Docker logos in inline-images component are warped/distorted.
- Issue can be found here: http://cn.ubuntu.com-pr-205.run.demo.haus/containers/
## Current result
![screen shot 2018-04-16 at 11 55 15](https://user-images.githubusercontent.com/17748020/38805289-368b68f6-416d-11e8-96e6-c70160d4c1e2.png)

**Comment by lyubomir-popov** [comment]
This comes from width: 100%. Removing that fixes it. Logos should have a max-height and max-width and then width and height auto.

.p-inline-images__item * {
    max-height: 3rem;
    max-width: 7rem;
    /* width: 100%; */
}

**Comment by lyubomir-popov** [comment]
The sizes here look quite arbitrary, maybe something to add to the icon sizes audit:
 medium sized screens and smaller:
        max-height: 3rem;
        max-width: 7rem;
bigger:
          max-height: 5.5rem;
          max-width: 9rem;
