### ISSUE TITLE
Navigation dropdown positioned behind selected state tab

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1737]
## v1.7.0-beta-1 review on insights.ubuntu.com

Navigation dropdown positioned behind selected state tab.
- Issue can be found here: http://insights.ubuntu.com-pr-306.run.demo.haus/cloud-and-server

## Current result
![screen shot 2018-04-17 at 10 41 50](https://user-images.githubusercontent.com/17748020/38862118-054d72a6-422c-11e8-87d2-cd69f3294d31.png)

**Comment by lyubomir-popov** [comment]
@Caleb-Ellis this nav is quite bespoke, is it something that will be superseeded by your nav changes? Or should we fix it as it is at the moment?
