### ISSUE TITLE
No padding between hero section and list of cards

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1738]
## v1.7.0-beta-1 review on insights.ubuntu.com

No padding between hero section and list of cards.
- Issue can be found here: http://insights.ubuntu.com-pr-306.run.demo.haus/topics/design
- Issue can be found here: http://insights.ubuntu.com-pr-306.run.demo.haus/topics/juju
- Issue can be found here: http://insights.ubuntu.com-pr-306.run.demo.haus/topics/maas
- Issue can be found here: http://insights.ubuntu.com-pr-306.run.demo.haus/topics/snapcraft

## Current result
![screen shot 2018-04-17 at 10 47 26](https://user-images.githubusercontent.com/17748020/38862414-c5d9ff9e-422c-11e8-92ea-119353f44ed7.png)

**Comment by kwm14** [comment]
Looking at the current live site it seems to be a problem there too - https://insights.ubuntu.com/topics/design

**Comment by lyubomir-popov** [comment]
This is just a markup issue. PR on the insights repo: https://github.com/canonical-websites/insights.ubuntu.com/pull/312

(It is also not 1.7.0 related, as that's what is live atm). @kwm14 I suggest we close this.

**Comment by kwm14** [comment]
@lyubomir-popov if it's not related to 1.7.0 beta-1 then happy to close 👍 you've done the work for fixing it up inside insights markup.
