### ISSUE TITLE
“Forms” page: “Related” links return 404 Not Found

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1756]
1\. Go to [the Forms page](https://docs.vanillaframework.io/en/base/forms).
2\. In the “Related” section, follow either of the links.

What happens: a 404 Not Found error.

What should happen: either
- each link exists and goes to the correct page, or
- the “Related” section does not exist.

(It may save time to fix #1648 at the same time as this bug.)

**Comment by anthonydillon** [comment]
Confirmed this is an issue. All the related links need to be reviewed and updated for the next release.
