### ISSUE TITLE
“Forms” page: All examples include an irrelevant switch

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1757]
1\. Go to [the Forms page](https://docs.vanillaframework.io/en/base/forms).
2\. Look at any of the examples.

What you see: At the bottom of the example, an unlabelled switch.

What you should see: The switch should not be present.

(It may save time to fix #1648 at the same time as this bug.)

**Comment by anthonydillon** [comment]
@matthewpaulthomas I believe the switch has been removed. Can you confirm this issue is resolved please?

**Comment by matthewpaulthomas** [comment]
Confirmed, the switches are gone. That was fast. 😊
