### ISSUE TITLE
Search box has no padding on the right

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1761]
When creating the 360 project I noticed the search box doesn't have padding or margin on the right by default.

Example:
https://codepen.io/anthonydillon/pen/vjLyGm

**Comment by Caleb-Ellis** [comment]
This will be fixed as part of 1.7.0 (you can check by changing the css in the codepen example to https://assets.ubuntu.com/v1/vanilla-framework-version-1.7.0-beta.2.min.css)

**Comment by Caleb-Ellis** [comment]
Fixed as of 1.7.0 release
