### ISSUE TITLE
Update snap install instructions from p-heading-five to p-heading-four

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1766]
## v1.7.0-beta-2 review on conjure-up.io
Update snap install instructions from p-heading-five to p-heading-four on 'Get started' section.
- Issue can be found here: http://conjure-up.io-pr-33.run.demo.haus/#navigation-closed

### Current result
![screen shot 2018-04-24 at 10 45 55](https://user-images.githubusercontent.com/17748020/39179824-342f62b0-47ad-11e8-99af-b7ada497934a.png)

### Expected result
![screen shot 2018-04-24 at 10 46 21](https://user-images.githubusercontent.com/17748020/39179830-3a53f098-47ad-11e8-9ca9-3134c6282de2.png)

**Comment by Caleb-Ellis** [comment]
This has now been addressed as part of https://github.com/canonical-websites/conjure-up.io/pull/33
