### ISSUE TITLE
Update /cloud hero section copy from p-heading-five to p-heading-four

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1767]
## v1.7.0-beta-2 review on cn.ubuntu
Update /cloud hero section copy from p-heading-five to p-heading-four.
- Issue can be found here: http://cn.ubuntu.com-pr-205.run.demo.haus/cloud/

### Current result
![screen shot 2018-04-24 at 11 51 14](https://user-images.githubusercontent.com/17748020/39182818-024c501a-47b6-11e8-9f09-a0c5bb39e316.png)

### Expected result
![screen shot 2018-04-24 at 11 51 31](https://user-images.githubusercontent.com/17748020/39182822-05c1a628-47b6-11e8-957d-a9d4fb412a3e.png)

**Comment by Caleb-Ellis** [comment]
Fixed as part of https://github.com/canonical-websites/cn.ubuntu.com/pull/205
