### ISSUE TITLE
u-align-center class applied to heading but is positioned on the left

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1768]
## v1.7.0-beta-2 review on cloud-init.io
u-align-center class applied to heading but is positioned on the left.
- Issue can be found here: http://cloud-init.io-pr-76.run.demo.haus/

### Current result
![screen shot 2018-04-24 at 12 03 07](https://user-images.githubusercontent.com/17748020/39183374-a7e1ac2c-47b7-11e8-935d-4a5cf2c86f5a.png)

**Comment by Caleb-Ellis** [comment]
Fixed as part of https://github.com/canonical-websites/cloud-init.io/pull/76
