### ISSUE TITLE
Rogue external link icon appearing on mobile view in footer

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1769]
## v1.7.0-beta-2 review on cloud-init.io
Rogue external link icon appearing on mobile view in footer?
- Issue can be found here: http://cloud-init.io-pr-76.run.demo.haus/

### Current result - Desktop
![screen shot 2018-04-24 at 12 08 25](https://user-images.githubusercontent.com/17748020/39183568-630f04f4-47b8-11e8-9f88-75c5df7da306.png)

### Current result - Mobile
![screen shot 2018-04-24 at 12 08 35](https://user-images.githubusercontent.com/17748020/39183581-70c0fecc-47b8-11e8-9472-9dd4fed0e43e.png)

**Comment by Caleb-Ellis** [comment]
Fixed as part of https://github.com/canonical-websites/cloud-init.io/pull/76
