### ISSUE TITLE
No margin/padding on split-list so column content overlaps

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1770]
## v1.7.0-beta-2 review on canonical.com
No margin/padding on split-list so column content overlaps.
- Issue can be found here: http://www.canonical.com-pr-264.run.demo.haus/services

### Current result
![screen shot 2018-04-24 at 12 24 53](https://user-images.githubusercontent.com/17748020/39184263-b2c1e56e-47ba-11e8-923f-b0f29aef2400.png)

**Comment by Caleb-Ellis** [comment]
Fixed as part of https://github.com/canonical-websites/www.canonical.com/pull/264
