### ISSUE TITLE
Line height on p-testimonial__quote looks to tight

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1775]
## v1.7.0-beta-2 review on ubuntu.com
Line height on p-testimonial__quote looks to tight which is wrapped in a paragraph tag so I'd expect it to be `16px`.
- font-size: `22px`
- line-height: `24px`
- Issue can be found here: http://www.ubuntu.com-pr-3035.run.demo.haus/containers/lxd

### Current result
![screen shot 2018-04-25 at 10 13 54](https://user-images.githubusercontent.com/17748020/39236724-6d058bae-4871-11e8-9be4-62d018e86ea1.png)

**Comment by Caleb-Ellis** [comment]
@kwm14 I've updated the demo with a fix here: http://www.ubuntu.com-pr-3035.run.demo.haus/containers/docker-ubuntu

**Comment by kwm14** [comment]
@Caleb-Ellis perfect, looks good 👍
