### ISSUE TITLE
Hero section title on /cloud/storage doesn't wrap to one-col on mobile view

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1777]
## v1.7.0-beta-2 review on ubuntu.com
Hero section title on /cloud/storage doesn't wrap to one-col when in mobile view but rest of the page.
- Issue can be found here: http://www.ubuntu.com-pr-3035.run.demo.haus/cloud/storage (mobile viewport)

### Current result
![screen shot 2018-04-25 at 10 44 16](https://user-images.githubusercontent.com/17748020/39238278-bbc02c3c-4875-11e8-9d37-7dad57ea44ce.png)

**Comment by Caleb-Ellis** [comment]
This has been fixed as of https://github.com/canonical-websites/www.ubuntu.com/pull/3035
