### ISSUE TITLE
Update pull quote text size

### ISSUE THREAD

**Issue by spencerbygraves** [vanilla-framework/vanilla-framework#1779]
# Proposal/amendment

Currently it looks unnecessarily large (see below). Can it be smaller or adapt to column sizes.

[Pull quote](https://vanilla-framework.github.io/vanilla-framework/examples/patterns/pull-quotes/)

## Visual

![image](https://user-images.githubusercontent.com/9105999/39239713-a18f0a82-4879-11e8-9ca3-aca67edd389c.png)

Stacked vertically to try and fix
![image](https://user-images.githubusercontent.com/9105999/39241489-fca746a0-487e-11e8-9dbc-2762ca79701f.png)

Small screen
![image](https://user-images.githubusercontent.com/9105999/39240821-d81bb4d0-487c-11e8-9a36-b0032771d7b2.png)

At the least we could remove the large size above 1030px. Below is 1.5 with 1rem citation.
![image](https://user-images.githubusercontent.com/9105999/39239889-2a7dbd0c-487a-11e8-89b1-c6204dd3f039.png)

**Comment by Caleb-Ellis** [comment]
@spencerbygraves One solution would be to allow any text element in the pattern (`<h1>`, `<h2>`, `<p>` etc) and then have the pull quote pattern itself basically just apply some nicely scaled quotation marks.

**Comment by kwm14** [comment]
## Agreed in WG
- +1 @Caleb-Ellis solution above
- we need further conversation on atomic level components with @anthonydillon 
- for now we can update the components current font size from `h3` to `h4`
