### ISSUE TITLE
`u-align-text` doesn't work

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1780]
## Process

1. Navigate to align utility demo https://docs.vanillaframework.io/en/utilities/align
2. See examples for `u-align-text--` utilities
3. Text alignment is not changed by it.

## Expected result

This utility should work or should be removed from docs.

**Comment by Caleb-Ellis** [comment]
@bartaz This will be fixed in the next release - accidentally included 1.7.0-beta stuff before it was ready

**Comment by Caleb-Ellis** [comment]
Fixed as of 1.7.0 release
