### ISSUE TITLE
Putting logo in navigation bar isn't vertically centred by default

### ISSUE THREAD

**Issue by steverydz** [vanilla-framework/vanilla-framework#1782]
## Process

The new logo for insights needed some nudging to be vertically centred. This should happen by default.

See: https://github.com/canonical-websites/insights.ubuntu.com/pull/325#pullrequestreview-115898293

## Expected result

When putting a logo inside `.p-navigation__logo`, no matter what it's height is, it should be vertically centred.

## Current result

When putting a logo inside `.p-navigation__logo`, the top is flush with the top of the navigation bar

## Screenshot

![screenshot from 2018-04-27 12-32-19](https://user-images.githubusercontent.com/501889/39360678-19f60f18-4a17-11e8-96c9-680428f29e9d.png)

**Comment by Caleb-Ellis** [comment]
This will be fixed when 1.7.0 is released (hopefully soon!)

**Comment by Caleb-Ellis** [comment]
Fixed as of 1.7.0 release
