### ISSUE TITLE
Update documentation builder template with Vanilla docs 1.7.1 styling

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1783]
## Design discussion 
- Original design issue can be found [here](https://github.com/ubuntudesign/vanilla-design/issues/217).

## Template design
- Default template design can be found [here](https://raw.githubusercontent.com/ubuntudesign/vanilla-design/master/Templates/Documentation-homepage/001%20Default%20template/default-documentation-home-template.png).
- @anthonydillon created an example of the design using Vanilla and CSS Grid https://codepen.io/anthonydillon/full/qYZQoV/

**Comment by Caleb-Ellis** [comment]
PR https://github.com/canonical-webteam/documentation-builder/pull/110

**Comment by kwm14** [comment]
Meeting notes [here](https://github.com/ubuntudesign/meeting-notes/issues/281) from our discussion with Docs team 👍

**Comment by kwm14** [comment]
PR merged. Closing issue.
