### ISSUE TITLE
Build Juju documentation homepage template

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1785]
## Design discussion 
- Original design issue can be found [here](https://github.com/ubuntudesign/vanilla-design/issues/220).

## Template design
- Default template design can be found [here](https://raw.githubusercontent.com/ubuntudesign/vanilla-design/master/Templates/Documentation-homepage/003%20Juju%20template/juju-documentation-home-template.png).
- Hero background: https://assets.ubuntu.com/v1/bd1d8c1d-juju-suru-blue-background.png
- Getting started image: https://assets.ubuntu.com/v1/843c77b6-juju-at-a-glace.svg

**Comment by kwm14** [comment]
Blocked. Awaiting new system for Documentation #discourse

**Comment by Caleb-Ellis** [comment]
PR: https://github.com/canonical-webteam/documentation-builder/pull/118

**Comment by kwm14** [comment]
PR merged 🥇
