### ISSUE TITLE
Build MAAS documentation homepage template

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1786]
## Design discussion 
- Original design issue can be found [here](https://github.com/ubuntudesign/vanilla-design/issues/219).

## Template design
- Default template design can be found [here](https://raw.githubusercontent.com/ubuntudesign/vanilla-design/master/Templates/Documentation-homepage/004%20MAAS%20template/maas-documentation-home-template.png).
- Hero background: https://assets.ubuntu.com/v1/a328d904-MAAS-background-desktop-large-screen.png

**Comment by kwm14** [comment]
Blocked. Awaiting new system for Documentation #discourse

**Comment by Caleb-Ellis** [comment]
PR: https://github.com/canonical-webteam/documentation-builder/pull/119

**Comment by kwm14** [comment]
PR merged 🥇
