### ISSUE TITLE
Build conjure-up documentation homepage template

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1787]
## Design discussion 
- Original design issue can be found [here](https://github.com/ubuntudesign/vanilla-design/issues/218).

## Template design
- Default template design can be found [here](https://raw.githubusercontent.com/ubuntudesign/vanilla-design/master/Templates/Documentation-homepage/002%20conjure-up%20template/conjure-up-documentation-home-template.png).
- Getting started image: https://api.jujucharms.com/charmstore/v5/bundle/canonical-kubernetes-30/diagram.svg

**Comment by kwm14** [comment]
Blocked. Awaiting new system for Documentation #discourse

**Comment by Caleb-Ellis** [comment]
PR: https://github.com/canonical-webteam/documentation-builder/pull/120

**Comment by kwm14** [comment]
PR merged 🥇
