### ISSUE TITLE
Build Enterprise proxy documentation homepage template

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1788]
## Design discussion 
- Original design issue can be found [here](https://github.com/ubuntudesign/vanilla-design/issues/221).

## Template design
- Default template design can be found [here](https://raw.githubusercontent.com/ubuntudesign/vanilla-design/master/Templates/Documentation-homepage/005%20Enterprise%20proxy%20template/enterprise-proxy-documentation-home-template.png).
- Getting started image: https://assets.ubuntu.com/v1/074862f8-snaps-hero.png

**Comment by kwm14** [comment]
Blocked. Awaiting new system for Documentation #discourse

**Comment by Caleb-Ellis** [comment]
PR: https://github.com/canonical-webteam/documentation-builder/pull/121

**Comment by kwm14** [comment]
PR merged 🥇
