### ISSUE TITLE
Context menu icon looks like a drag handle

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1813]
[The Vanilla icons](https://docs.vanillaframework.io/en/patterns/icons) include a “contextual menu” icon, `p-icon--contextual-menu`:

![context-menu-icon](https://user-images.githubusercontent.com/19801137/39998147-1d1f221a-577d-11e8-85ef-0566d1b804ad.png)

In the January snapcraft.io prototype, @lyubomir-popov used this icon for a menu inside a card:

![release cards](https://user-images.githubusercontent.com/19801137/39998313-9d93117c-577d-11e8-89ed-17d24daf09c2.png)

Unfortunately, test participants misinterpreted the icon as a drag handle:
- “Because you have this little design element right here, the three lines, I just kind of assumed that you can just drag this and drop, you know?”
- “I think immediately I’d try dragging the little dots.”

Some people, through repeated exposure, may recognise this icon as a menubutton in the context of a header bar in an Android or Google app. But it may not be suitable for Vanilla sites in general.

**Comment by kwm14** [comment]
Moving [issue](https://github.com/ubuntudesign/vanilla-design/issues/244) to vanilla-design 👍
