### ISSUE TITLE
Failed to build _patterns_icons because of missing %u-hide-text

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1821]
`_patterns_icons` uses `%u-hide-text` mixin that is defined and included elsewhere.

But icons don't include it themselves making it impossible to build icons if `vf-u-hide` is not included before.

If patterns depend on some other patterns or utils they should include them, so they can be built independently.

This is causing our `./run build` to fail when we updated Vanilla to 1.7.0.

**Comment by Caleb-Ellis** [comment]
@bartaz This is fixed as of https://github.com/vanilla-framework/vanilla-framework/pull/1815, to be released next week sometime.

Basically `%u-hide-text` lives in `_utilities_hide.scss`, so for now you need to `@include vf-u-hide;` for it to work. We'd only tested on sites that include all of Vanilla so didn't catch this error :(

**Comment by Caleb-Ellis** [comment]
Nevermind, 1.7.1 is out and fixes this issue
