### ISSUE TITLE
Docs footer doesn’t contain usual “Report a bug” links

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1824]
1\. Look at the bottom of [any page on the Vanilla site that is not in the “Docs” section](https://vanillaframework.io/browser-support).
2\. Look at the bottom of [any page that _is_ in the “Docs” section](https://docs.vanillaframework.io/en/patterns/aside).

What happens:
1\. There are links to “Report a bug with this site” and “Report a bug with Vanilla framework”.
2\. The links are missing.

What should happen:
2\. The same links are present.

**Comment by Caleb-Ellis** [comment]
Fixed in https://github.com/vanilla-framework/vanilla-framework/pull/1835
