### ISSUE TITLE
Clicking any “contextual menu” example scrolls the page

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1825]
1\. Go to [the “Contextual menu” page](https://docs.vanillaframework.io/en/patterns/contextual-menu).
2\. In the examples section, click any of the “Link” links.

What happens:
- The menu opens.
- The page scrolls.

What should happen:
- The menu opens.
- The page does not scroll.

(This does not seem to be anything to do with ensuring that the menu is visible: the page scrolls to the same point regardless of which example you click, and the third example menu opens partly out of sight regardless.)

**Comment by Caleb-Ellis** [comment]
Probably just need to add an `e.preventDefault()` to the JS - will look at it later
