### ISSUE TITLE
“Aside” pattern is misnamed/ambiguous

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#1827]
[The description of the “Aside” pattern](https://docs.vanillaframework.io/en/patterns/aside) is, in full:
> An aside can be used to display a contextual menu within a page, such as a table of contents.

This is confusing in several ways.

First, “contextual menu” is a macOS-specific synonym for “context menu”. Anyone familiar with either term will know it as a menu of items related to an element that has just been right-clicked or long-pressed (references: [Windows](https://msdn.microsoft.com/en-gb/library/windows/desktop/dn742392.aspx), [macOS](https://developer.apple.com/macos/human-interface-guidelines/menus/contextual-menus/), [Gnome](https://developer.gnome.org/hig/stable/menus.html.en), [KDE](https://community.kde.org/KDE_Visual_Design_Group/HIG/ContextMenu)). Anything that appears “within a page” is, therefore, not a contextual menu.

Second, this pattern both evokes and uses [HTML’s `<aside>` element](https://html.spec.whatwg.org/multipage/sections.html#the-aside-element), which “represents a section of a page that consists of content that is tangentially related to the content around the aside element, and which could be considered separate from that content.” But a table of contents is not, in any sense, “tangentially related to the content around the aside element”.

Third, tables of contents are presented as an _example_ of when you might use this pattern. But it seems to provide markup specific to tables of contents:
```html
<li><a class="p-aside__link is-active" href="#link3">Link 3 (Active)</a></li>
```
It’s not clear whether the pattern is useful for anything else, and if so, what benefit you get from using it.

I suggest:
- If tables of contents are a legitimate use for this pattern, it should not be called “Aside”.
- If tables of contents are not a legitimate use for this pattern, the reference shouldn’t give one as an example.
- If anything else is a legitimate use for this pattern, the reference should provide an example.

**Comment by Caleb-Ellis** [comment]
I might be wrong, but I don't think this pattern is used as anything other than a ToC. @kwm14 is that right? If that's the case we should call it `.p-table-of-contents` or something, and then we should deprecate the `.p-aside` pattern. It would then also make sense to use the `<nav>` element.

**Comment by kwm14** [comment]
@Caleb-Ellis nope this component is only used on Vanilla documentation as ToC, happy for it to be renamed and deprecate `.p-aside` component. I've scheduled component deprecation next cycle so we can add it to the list 😄

**Comment by deadlight** [comment]
I agree that "contextual menu" is not the correct term for this component's use - that's meant "supplementary drop-down menu" right back the the Xerox days! I'll be sure to update the docs.

I, however, disagree with "table of contents" as a name for this pattern as it describes one use-case and limits future use. We don't want users of Vanilla not using this component for supplementary, right-hand information of other types. I do agree that this component is useful for ToCs but there's nothing table-of-contents specific about it.

The pattern isn't used on [ubuntu.com's legal pages](https://www.ubuntu.com/legal/data-privacy) but it absolutely should be - both for the "older versions" and "contents" boxes.

The name _aside_ is the same name as an HTML element (although that's true of other components - button, table) and I would be happy to change it to something else which is distinct but also as descriptive of use as "aside".

I'm, personally, happy to keep _.p-aside_ as a name but am open to replacing it with something else with a similar level of broad definition which allows for the most versatile use.

**Comment by kwm14** [comment]
## Similar examples
A quick scout of other frameworks to see what they name this particular component, by the looks of it very different per company.

**https://materializecss.com/getting-started.html**
- name: 'table of contents' component
![Screenshot 2019-03-20 at 12 34 05](https://user-images.githubusercontent.com/17748020/54684554-8dab1100-4b0c-11e9-8630-45af8e27fe2f.png)

**https://www.lightningdesignsystem.com/components/accordion/**
- name: 'sticky nav bar' component
![Screenshot 2019-03-20 at 12 36 47](https://user-images.githubusercontent.com/17748020/54684673-d9f65100-4b0c-11e9-9785-844e89c510ef.png)

**https://ant.design/docs/react/introduce**
- name: 'table of contents' component
![Screenshot 2019-03-20 at 12 39 39](https://user-images.githubusercontent.com/17748020/54684848-4d985e00-4b0d-11e9-8185-a0820f309df0.png)

https://bulma.io/documentation/components/dropdown/#hoverable-or-toggable
- name: 'anchor's component
![Screenshot 2019-03-20 at 12 46 34](https://user-images.githubusercontent.com/17748020/54685233-3ad25900-4b0e-11e9-920e-52dbaf1a32aa.png)

https://luna.sainsburys.co.uk/library/components/accordion
- name: 'flag' component
![Screenshot 2019-03-20 at 12 54 41](https://user-images.githubusercontent.com/17748020/54685694-5ab64c80-4b0f-11e9-980b-1e00e1cd7a62.png)

Happy for you to make the call on this one @deadlight, not a widely used component across our suite of products and services so don't want this to be a blocker moving forward with work items.
