### ISSUE TITLE
There should be a pattern to make headings thin

### ISSUE THREAD

**Issue by Caleb-Ellis** [vanilla-framework/vanilla-framework#1841]
There is currently no way to change font-weights outside of custom/inline styling. We should have guidelines for when we should/shouldn't change font-weights, but we are using thin `h1`s in a few places so I think it should be a pattern.

![screenshot_6](https://user-images.githubusercontent.com/25733845/40649797-b3263e76-6329-11e8-931b-71c82dac6130.png)

![screenshot_5](https://user-images.githubusercontent.com/25733845/40649803-b5c113f4-6329-11e8-91d6-f40a0bd6c125.png)

**Comment by kwm14** [comment]
## Agreed in working group
- change font-weight of `h1` to 100
