### ISSUE TITLE
Remove or update p-link--strong?

### ISSUE THREAD

**Issue by spencerbygraves** [vanilla-framework/vanilla-framework#1845]
p-link--strong looks the same as our new h5 style, which could lead to confusion when used together on a page.

![image](https://user-images.githubusercontent.com/9105999/40789662-dcdd6d8a-64ea-11e8-92ee-6eb76b6ac788.png)

We could remove it and use either:

- Blue links (p-link)
- #111111 for areas where links are expected e.g. left navigation or footer (p-link--soft)

In the example below, the strong links could be blue (one of the original reasons for the strong style was to avoid lists of blue links, but we may now feel that it's not a problem).

![image](https://user-images.githubusercontent.com/9105999/40789816-3a8fed18-64eb-11e8-86c8-78de07dd30fd.png)

Or we keep it for use on dark backgrounds only and update the description in docs:

> The .p-link--strong class should be used on hyperlinks that require emphasis or on a dark background.

**Comment by anthonydillon** [comment]
If I remember rightly, the reason we created the strong link were the tables that were deemed a "sea of blue". Do we still have this issue? Is it something to take into account?

**Comment by spencerbygraves** [comment]
@anthonydillon yep, that would be something to consider.

For reference, [MAAS is now using blue links in tables](https://maas.io/tour)

**Comment by kwm14** [comment]
## Agreed in working group
- +1 to deprecate `p-link--strong`
- `h5` by default is bold so we can apply p-link to this style

**Comment by kwm14** [comment]
Issue created here to deprecate- https://github.com/vanilla-framework/vanilla-framework/issues/1996
