### ISSUE TITLE
Navigation search should include allow for overlay

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#1865]
# Pattern proposal/amendment

for Jujucharms.com, when clicking the search field, an overlay pops up. There is a design requirement that a white border should then surround the search field which connects it to the overlay.. like so:

<img width="828" alt="screen shot 2018-06-14 at 17 10 45" src="https://user-images.githubusercontent.com/505570/41424441-f2cd63fa-6ff5-11e8-8a36-5510b40d7e01.png">

There is not the space available above the input field for equal border spacing without breaking the pattern.

Proposal: overall height of the navigation should be increased to allow for equal space around the input field.

**Comment by kwm14** [comment]
@spencerbygraves agreed to go with vanilla defaults 👍
