### ISSUE TITLE
Forced flexbox alignment on image

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#1880]
Default styles for `img` in Vanilla now have `align-self: flex-start;` ( https://github.com/vanilla-framework/vanilla-framework/blob/develop/scss/_base_media.scss#L7). This forces image to the start/top of it's flexbox parent regardless of the alignment defined by parent.

This makes it impossible to (for example) vertically center the image using flexbox without overriding this property on `img`. This is already causing at least 2 bugs in snapcraft.io (misaligned logos on home page, image not centered in lightbox).

Is this style necessary? If so, I guess patterns that require centering images vertically would need to start overriding this.
If it's not necessary maybe it can be removed from Vanilla default styles?

**Comment by Caleb-Ellis** [comment]
Thanks @bartaz. After speaking with @lyubomir-popov I think this was introduced to ensure aspect ratios were maintained in elements with defined max height/width (e.g in Matrix or Inline-images). Still, the rule should definitely be part of the respective pattern as opposed to on `img` itself. I'm just doing some tests now to see what removing the `align-self: flex-start;` affects

**Comment by Caleb-Ellis** [comment]
So it looks like nothing is changed on the surface (https://percy.io/vanilla-framework/vanilla-framework/builds/804257). As a temp workaround you should be able to add the rule:
``` scss
img {
  align-self: initial;
}
```
right after including Vanilla.
