### ISSUE TITLE
Isolate specific legacy sites code in additional files

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1896]
_moving [original issue](https://github.com/ubuntudesign/vanilla-design/issues/290) to correct repo_

> Issue raised by @therealjuan 
> To keep reducing file-size of Vanilla, it will be good to compile all style code related to legacy sites into a specific CSS that will be loaded by legacy sites so new sites wouldn't need to include these when using the latest Vanilla.

**Comment by kwm14** [comment]
### Agreed in WG
- Added feature for planned 2.0 release 👍

**Comment by deadlight** [comment]
Ahead of the 2.0 release, we have removed all of the deprecated patterns from the codebase. When we release 2.0, there will be no legacy-specific CSS and all code will be recommended for new sites.

Be aware, if generated CSS files are still too large for your use case then it it possible to compose a subset of only the Vanilla patterns that you use.
