### ISSUE TITLE
Tabstrip (possibly other uls/ols as well): White space between items

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1898]
# 1. Bug template

## Process
1. Inspect adjacent .p-tabs__item's;
2. add border-top to them
3. inspect space between them
cause - [white space between inline-block items ](https://stackoverflow.com/questions/5256533/a-space-between-inline-block-list-items)

## Expected result
No space between items

## Current result
Space between items

**Comment by anthonydillon** [comment]
@lyubomir-popov I cant replicate the issue.

![screenshot_2018-07-24 tabs vanilla framework](https://user-images.githubusercontent.com/1413534/43134306-8c3efed8-8f39-11e8-8668-4e76aa273e98.png)

**Comment by anthonydillon** [comment]
Oh I see, it only happens on Chrome. Firefox is fine.
