### ISSUE TITLE
Tabstrip items wrap when content overlows on desktop

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1899]
# 1. Bug template

## Process
1. go to https://codepen.io/lyubomir-popov/pen/eKPLpx
2. observe overflow

## Expected result
overflow: scroll-x should be applied to desktop as well, so when items exceed available space, they behave nicely

## Current result
Items just wrap to a second line

**Comment by anthonydillon** [comment]
Fixed in https://github.com/vanilla-framework/vanilla-framework/issues/1899
