### ISSUE TITLE
Wrapping images in links in the matrix pattern causes a layout issue

### ISSUE THREAD

**Issue by steverydz** [vanilla-framework/vanilla-framework#1908]
## Pattern to amend

[Matrix](https://docs.vanillaframework.io/en/patterns/matrix)

## Visual

![screenshot from 2018-07-04 10-08-11](https://user-images.githubusercontent.com/501889/42267973-4e57d472-7f72-11e8-8db2-e6240355b411.png)

## Context

Suggest adding a class such as `.p-matrix__img--link` which handles this case

**Comment by Caleb-Ellis** [comment]
@steverydz Could you elaborate how you got this bug? This is what I get on https://vanilla-framework.github.io/vanilla-framework/examples/patterns/matrix/ when I wrap the `<img>`s in `<a>`s

![screenshot_4](https://user-images.githubusercontent.com/25733845/42323995-d4f2c126-8059-11e8-9c6a-8b3710aef25c.png)

**Comment by steverydz** [comment]
@Caleb-Ellis Looks like it's been fixed since the version the beta site is using. I'll close this.
