### ISSUE TITLE
Develop a consistent and understandable naming convention for spacing variables

### ISSUE THREAD

**Issue by Caleb-Ellis** [vanilla-framework/vanilla-framework#1923]
**Describe the bug**
As of the 1.7.0 release, we have introduced a completely new way to visualise and understand spacing which includes a bunch of new spacing variables. My issue is that at the moment it takes some mental gymnastics to understand what they do, in part because of their names.

Currently, there are a number of things that are needed for a variable name. Is the spacing:
1. Vertical or horizontal? `spv / sph`
2. Inside a component or outside a component? `intra / inter`
3. Should the density be modified? `condensed / regular / expanded`
4. If the component is a container (e.g. `p-strip`), should the spacing be modified from default? `shallow / regular / deep`
5. Should the spacing scale with the `$multi` variable? `scaleable`

This naming convention means we end up with names like `$spv-intra--condensed--scaleable` and `$spv-inter--deep-scaleable` which are difficult to parse. My proposal is for us to have a discussion about it and get an idea of what people think makes more sense. Here are some suggestions to get the ball rolling (not committing to any, just throwing them out there):

- `sv / sh` for vertical / horizontal
- `inner / outer` for inside or outside a component
- `1 / 2 / 3` or `dense / normal / sparse` for the different densities
- `fluid` to imply the spacing can be multiplied
- Maybe separate out the scalability to a mixin, e.g.
``` scss
@mixin vf-scalable($sp-var, $multiplier) {
  @return $sp-var * $multiplier;
}

margin-bottom: vf-scalable($spv-inter, 3);
```

**Comment by kwm14** [comment]
## Agreed in WG
- Further discussion for 2.0 release

**Comment by clagom** [comment]
@deadlight is considering this for the space-variable work

**Comment by deadlight** [comment]
Having thought about it, "condensed / regular / expanded" seems the best option for describing density and is common design parlance
