### ISSUE TITLE
p-contextual-menu__toggle has too much margin as a button

### ISSUE THREAD

**Issue by Caleb-Ellis** [vanilla-framework/vanilla-framework#1927]
**Describe the bug**
Since buttons have a margin-bottom by default, the dropdown is displaying way below the button. As an aside, the little arrow is missing as well?

**To Reproduce**
1. Go to https://vanilla-framework.github.io/vanilla-framework/examples/patterns/contextual-menu/
2. Replace the markup in `<body>` to
``` html
<span class="p-contextual-menu--left">
    <button href="#" class="p-contextual-menu__toggle" aria-controls="#menu" aria-expanded="true" aria-haspopup="true">Link</button>
    <span class="p-contextual-menu__dropdown" id="menu" aria-hidden="false" aria-label="submenu">
        <span class="p-contextual-menu__group">
            <a href="#" class="p-contextual-menu__link">Link</a>
            <a href="#" class="p-contextual-menu__link">Link</a>
            <a href="#" class="p-contextual-menu__link">Link</a>
        </span>
        <span class="p-contextual-menu__group">
            <a href="#" class="p-contextual-menu__link">Link</a>
            <a href="#" class="p-contextual-menu__link">Link</a>
            <a href="#" class="p-contextual-menu__link">Link</a>
        </span>
    </span>
</span>
```
3. Check that there is a huge gap between the button and dropdown

**Expected behavior**
They should be closer together

**Screenshots**
![screenshot_5](https://user-images.githubusercontent.com/25733845/42814133-2eef8726-89bb-11e8-9648-92dcdb489950.png)

**Comment by kwm14** [comment]
@Caleb-Ellis would a fix for this be to remove `margin-bottom: 0px;` from the button?

Or would that have conflicts with `p.button` due to it importing the button style for p-contextual-menu?
