### ISSUE TITLE
Checkbox and radio button aren't spaced the same

### ISSUE THREAD

**Issue by Caleb-Ellis** [vanilla-framework/vanilla-framework#1929]
**Describe the bug**
`<input type="checkbox">` and `<input type="radio">` have different margins/paddings surrounding the input, so they look strange when placed on top of one another.

**To Reproduce**
1. Go to https://vanilla-framework.github.io/vanilla-framework/examples/base/forms/checkboxes/
2. Replace the markup in `<body>` with:
``` html
<form>
  <input type="radio" name="RadioOptions" id="Radio1" value="option1">
  <label for="Radio1">Radio option 1</label>
  <input type="radio" name="RadioOptions" id="Radio2" value="option2">
  <label for="Radio2">Radio option 2</label>
  <input type="radio" name="RadioOptions" id="Radio4" value="option4" disabled="disabled">
  <label for="Radio4">Radio option 3 - disabled</label>
  <input type="checkbox" id="checkExample1">
  <label for="checkExample1">Checkbox option 1</label> 
  <input type="checkbox" id="checkExample2" disabled="disabled">
  <label for="checkExample2">Checkbox option 2 - disabled</label>
</form>
```

**Expected behavior**
Horizontal spacing should be the same for checkboxes and radio buttons *in all browsers*.

**Screenshots**
![screenshot_1](https://user-images.githubusercontent.com/25733845/42874223-72f31844-8a78-11e8-8335-cae258473d7e.png)

**Comment by deadlight** [comment]
@kwm14 which spacing - radios or checkboxes - is correct?

**Comment by kwm14** [comment]
@deadlight design spec here for checkboxes and radio buttons, but it doesn't identify horizontal spacing:

- Checkbox/radio button: browser default
- Margin right: `0.75rem`
- Text color: `$color-dark`
- Font size: `1rem`

**Comment by anthonydillon** [comment]
Testing develop the checkboxes and radio buttons are aligned on all browsers:
![Screenshot_2018-10-16 Forms Checkboxes Vanilla framework - Examples.png](https://images.zenhubusercontent.com/55f93fbc4f7a08fbb7f4ee18/6baa3369-b449-4b0e-9cfd-567d99f833f0)

@Caleb-Ellis can you confirm please.

**Comment by Caleb-Ellis** [comment]
Fixed via https://github.com/vanilla-framework/vanilla-framework/pull/2006
