### ISSUE TITLE
Update name of 'contextual-menu' icon in library

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1943]
## Pattern to amend

Based on discussions of the contextual menu looking like a drag handle [here](https://github.com/ubuntudesign/vanilla-design/issues/244) we've decided to to update the class name to accommodate it's actual action

## Context
This update will be part of our deprecation process working towards v2.0 release.

**Update name of icon:**

- Current: `p-icon--contextual-menu`
- Update: `p-icon--drag`

## Visual
![vanilla-440-drag-1](https://user-images.githubusercontent.com/19801137/43002845-27dc4500-8c22-11e8-9ebd-8d9bcc147e20.png)

![vanilla-440-drag-2](https://user-images.githubusercontent.com/19801137/43002846-27f98fc0-8c22-11e8-8b86-91f3b94c762a.png)

**Comment by anthonydillon** [comment]
I'm not a fan of the new name. I think the action should do more then
reordering. For example, it could be used to add to a list/bucket. I would
like to recommend `p-icon--drag`.

**Comment by kwm14** [comment]
@anthonydillon that's a fair point, the updated name was between either `p-icon-reorder` and `p-icon-drag`

Happy to go with either and see how it tests 👍
