### ISSUE TITLE
Update p-sidebar in Documentation to include third level

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1946]
## Pattern to amend
- Update p-sidebar in Documentation to include third level as requested by the docs team [here](https://github.com/juju/docs/issues/2847)
- Design issue can be found here for reference [too](https://github.com/ubuntudesign/vanilla-design/issues/250)
- Icon used for third-level accordion:
   - Open - `p-icon--plus`
   - Close - `p-icon--minus`

### Default
![toc-updated-007](https://user-images.githubusercontent.com/17748020/43408804-24c5acc6-941a-11e8-9095-2ed1ef9e74dc.png)

### Open
![toc-updated-007-open](https://user-images.githubusercontent.com/17748020/43408817-2bd75dac-941a-11e8-99af-f9bf1eebf4e3.png)

## Context
- Allow for third-level content as currently we only allow for two-levels and styling looks identical for main and sub section titles and becomes confusing for users.

**Comment by deadlight** [comment]
p-sidebar is no longer a component. Please use the grid and accordion to achieve similar results - if you require modifications to that pattern then please submit a bug against it
