### ISSUE TITLE
Slider pattern causes a build error with rollup-sass

### ISSUE THREAD

**Issue by Caleb-Ellis** [vanilla-framework/vanilla-framework#1947]
Trying to build include Vanilla with rollup is giving the error:
```bash
Error: Lexical error on line 1. Unrecognized text.
100% - ($thumb-size / 2)
```

Replacing `$thumb-size` with `#{$thumb-size}` fixes the issue.

**Comment by anthonydillon** [comment]
Thanks for reporting this issue. Fingers crossed it is selected for small tasks next iteration.
