### ISSUE TITLE
Configure Shelves grid to generate nested pushes / pulls

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1949]
## Pattern to amend

Shelves grid

## Visual
At the moment, shelves by default only generates top level push / pull classes. Here's dpocs how to do it:
http://shelvesgrid.org/docs/css#push-pull

## Context

Nested push pulls are the only way to not add empty cols in a case like this:

![image](https://user-images.githubusercontent.com/2741678/43652932-853aa418-973e-11e8-8e7c-74fec2ac22f8.png)

In this image, the push doesn't push far enough, as the percentage is calculated for the 12 column context, not the 6col one.

**Comment by anthonydillon** [comment]
We recommend using `suffix-2` or `prefix-2`. Please try this and see if it resolves the issue.

**Comment by lyubomir-popov** [comment]
@anthonydillon prefix-2 adds padding, not margin so not suitable in this case:
![image](https://user-images.githubusercontent.com/2741678/43710497-baa11562-9967-11e8-9eb3-050a1284d206.png)

And, as push, it doesn't factor in the context - whether nested or not, it still outputs padding-left: 17.21462%

**Comment by lyubomir-popov** [comment]
Example with enabled nested pushes, pulls, suffix and prefix:
![image](https://user-images.githubusercontent.com/2741678/43712964-e577eec0-996f-11e8-8e54-26c81090c647.png)

For comparison, example as it is at the moment, without:
![image](https://user-images.githubusercontent.com/2741678/43712930-ca66a3d8-996f-11e8-9fe4-9410caccaa1c.png)

**Comment by lyubomir-popov** [comment]
Turns out these can be set to true from within another project, so no need to alter the defaults in vanilla as that adds file size; for reference, to enable them, just add these:

// enable nested push pull suffix and prefix
$shelves-nested-prefixes: true !default;
$shelves-nested-suffixes: true !default;
$shelves-nested-pushes: true !default;
$shelves-nested-pulls: true !default;
$shelves-tablet-prefixes: true !default;
$shelves-tablet-suffixes: true !default;
$shelves-tablet-pushes: true !default;
$shelves-tablet-pulls: true !default;
$shelves-mobile-prefixes: true !default;
$shelves-mobile-suffixes: true !default;
$shelves-mobile-pushes: true !default;
$shelves-mobile-pulls: true !default;
