### ISSUE TITLE
Value from placeholders settings does not use !default

### ISSUE THREAD

**Issue by sveetch** [vanilla-framework/vanilla-framework#1950]
**Describe the bug**
Values from `_settings_placeholders.scss` are not defined with `!default` flag opposed to every other values from other settings.

And so we can't override from a settings file imported before vanilla stuff as it's described from https://docs.vanillaframework.io/en/customising-vanilla

**To Reproduce**
1. Create a `_settings.scss` in your Sass project;
2. Append `$border-radius: 0;` to this settings file;
3. Import this settings file before vanilla import `@import "vanilla";`;
4. Build CSS;
5. Common border radius value from `_settings_placeholders.scss` is applied;

**Expected behavior**
Values from placeholders settings should be overridden from a custom settings file loaded before vanilla.

Actually these values would need to be overridden from another settings file to import just before vanilla.

**Additional context**
Reported from Vanilla 1.8.0 and libsass 3.5.4

**Comment by deadlight** [comment]
Good spot and thanks for reporting this issue.

You should, indeed, be able to override these variables.
