### ISSUE TITLE
Improve usability of Sketch source file

### ISSUE THREAD

**Issue by therealjuan** [vanilla-framework/vanilla-framework#1977]
There are some serious of improvements that can help the usability of the Sketch source file for Vanilla:

- Make sure symbols have resizing attributes so components do not break
- Make the symbols easy to navigate, I want to search for a button element, not a positive element. The class is a useful addendum but when you search within symbols, you search by general components
- Use a better hierarchy for symbols ( Button > Positive > neutral)
- Label symbols as you would expect from other design systems.  i.e. A drop-down is a select item on HTML but normally you refer to it as dropdown
- There may be instances in which some elements might require labels or not so would be good to provide alternatives
- All the above can be applied to layer styles and font sizes as well
- Adding general colours being used as an additional artboard can be handy

**Comment by lilyvidenova** [comment]
- heading five is using the medium font weight, it should use regular

**Comment by kwm14** [comment]
Thanks @therealjuan these are all valid points in improving the master Sketch file, I'm continuing to improve it each release so I will plan these items for v2.0 👍 

This is a design related issue so will move to https://github.com/ubuntudesign/vanilla-design/

**Comment by kwm14** [comment]
> * heading five is using the medium font weight, it should use regular
> * remove the bottom border from the last row of the example tables, so they reflect how the tables are supposed to look in real life

**Comment by kwm14** [comment]
Moved to correct repo here: https://github.com/ubuntudesign/vanilla-design/issues/311
