### ISSUE TITLE
Inline code doesn't stand out

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#1995]
Inline code blocks aren't as visible as they should be - see: https://docs.vanillaframework.io/en/base/code

![image](https://user-images.githubusercontent.com/519935/45738555-1cd47c00-bbf1-11e8-9cac-9098b592aecf.png)

GitHub's styling is better, for example:

![image](https://user-images.githubusercontent.com/519935/45738582-2d84f200-bbf1-11e8-8c5f-2827c097896d.png)

**Comment by nottrobin** [comment]
@degville was interested in this

**Comment by deadlight** [comment]
@kwm14 - thoughts on this?

**Comment by anthonydillon** [comment]
I think a light grey background is good. Be aware of dark background though.

**Comment by kwm14** [comment]
@deadlight @nottrobin I like the idea and looks good but like @anthonydillon worth thinking about if used on a darker background how this could work.

Definitely worth bringing up as a WG proposal 👍

**Comment by kwm14** [comment]
## Agreed in WG
- +1 from the team to implement
- @kwm14 to add to features backlog

**Comment by kwm14** [comment]
Design signed off and build [issue](https://github.com/vanilla-framework/vanilla-framework/issues/2040) created. Plan to update in v2.0 release 💯
