### ISSUE TITLE
Stop using BlinkMacSystemFont

### ISSUE THREAD

**Issue by fitojb** [vanilla-framework/vanilla-framework#1997]
https://github.com/vanilla-framework/vanilla-framework/blob/983dc73655e3aa3f3bd905202580ce57e9ec3a17/scss/_settings_font.scss#L2

That name has been deprecated for a long time already. [It will be removed from Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=554590). In Chrome under macOS, `system-ui` is enough.

**Comment by deadlight** [comment]
Thanks for raising this issue; we'll ensure that the font stack is fixed for the next release.
