### ISSUE TITLE
Accessibility outline offset causing numerous issues

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#2017]
## Pattern to amend

The blue accessibility outline on form elements currently has an offset of 2px; this causes numerous  issues, like this clipping that happens when the parent has overflow: hidden (which happens very often):

<img width="272" alt="screen shot 2018-10-08 at 16 21 31" src="https://user-images.githubusercontent.com/2741678/46618039-5c1e2a80-cb16-11e8-8289-14a2c782a19c.png">

If we want to fix that and can't make set the overflow on the parent to visible, we need to write custom css in non-vanilla repos.

## Visual

By setting the outline to coincide with a border's element, all this can be avoided; also, it resolves the numerous nested borders/gradients: 
<img width="261" alt="screen shot 2018-10-08 at 16 21 22" src="https://user-images.githubusercontent.com/2741678/46618269-fbdbb880-cb16-11e8-9854-bd791277382f.png">

## Context

Anywhere elements with accessibility outline are used.

**Comment by kwm14** [comment]
## Agreed in WG
- It's alright it but...
  - we need to look at other examples
  - look into alternative notification styles
  - @kwm14 to look into 👍

**Comment by kwm14** [comment]
Issue fixed here: https://github.com/vanilla-framework/vanilla-framework/pull/2056 👍 and will be in next release 2.0 💯
