### ISSUE TITLE
Tighten letter-spacing for Ubuntu font at larger sizes

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#2023]
## Pattern to amend

[Typography](https://docs.vanillaframework.io/en/base/typography)

## Visual

Three examples, before and after:

![dark on light](https://user-images.githubusercontent.com/19801137/46746748-a08d0000-cca7-11e8-9b1c-92725ff16f10.png)
![light on dark](https://user-images.githubusercontent.com/19801137/46746764-a97dd180-cca7-11e8-814f-0df91f3160ef.png)
![h2 dark on light](https://user-images.githubusercontent.com/19801137/46746736-979c2e80-cca7-11e8-8e6a-fcbbaef55183.png)

## Context

The Ubuntu font was designed foremost to be highly legible in GUIs, at small sizes, at 2010-era screen resolutions.

As a result, the letter spacing is very loose, to ensure at least 1 pixel empty space between characters at small sizes.

Unfortunately, this makes it look _too_ loose when the font is used at much larger sizes, such as the size of Vanilla `h1` and `h2` headings. (The recent change of `h1` to use Ubuntu Thin makes this even more noticeable, but it is an issue with the regular weight too.)

When fonts are adjusted for size, the letter spacing is tightened for larger sizes. For example, try adjusting the optical size of [Zeitung](https://v-fonts.com/fonts/zeitung) or [Dunbar](https://v-fonts.com/fonts/dunbar).

We can achieve most of the same effect by adjusting the letter-spacing in Vanilla for the largest heading sizes:
```css
h1 {letter-spacing: -2px} /* compensate for loose letter-spacing of the Ubuntu font */
h2 {letter-spacing: -1px} /* compensate for loose letter-spacing of the Ubuntu font */
```

If someone uses Vanilla with a different font, that has tighter letter spacing by default, tweaking the letter spacing may no longer be appropriate. So it may be helpful to put these rules immediately following the rule that specifies the Ubuntu font, minimizing the chance that they’ll be overlooked when the font is changed.

**Comment by kwm14** [comment]
## Design review
_with Marcus, Wayne @spencerbygraves @lyubomir-popov @anasereijo_ 
- As the typeface was designed to be open, we developed a system for the font to be used for both print and web
- We spent 2 years developing this typeface so we've agreed to no amend the letter spacing

**Comment by matthewpaulthomas** [comment]
> As the typeface was designed to be open, we developed a system for the font to be used for both print and web

Is this system written up anywhere?
