### ISSUE TITLE
Review code snippet font-size (dev request on snapcraft repo)

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#2032]
## Pattern to amend

We have a request to reduce font size of code snippets:
https://github.com/canonical-websites/snapcraft.io/issues/1221#event-1917154137

https://github.com/canonical-websites/blog.ubuntu.com/issues/415

I am not sure the size is bigger but maybe the thicker font-weight makes it look so:

## Visual

(image from the original request)
https://user-images.githubusercontent.com/946674/47173380-c1b2a980-d2c2-11e8-948c-c7a847f2e0c4.png

## Context

In what context does your amendment solve a problem?
Narrow fixed-width sites and small screens.

**Comment by kwm14** [comment]
## Agreed in WG
- initial fix to allow inline code snippets to scroll rather than wrap
- issue fix created here: https://github.com/vanilla-framework/vanilla-framework/issues/1986
