### ISSUE TITLE
Combine code, code numbered and code snippet components onto a single page

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#2055]
**Describe the bug**
Based on a recent content [analysis](https://github.com/ubuntudesign/vanilla-design/issues/317) it occurred that these components weren't getting much traction, combining code, code numbered and snippet components onto a single page will benefit users using our site.

**To Reproduce**
1. Go to https://docs.vanillaframework.io/
2. Scroll down to **Text**
4. You will see Code, Code numbered and Code snippet as separate pages:
   - https://docs.vanillaframework.io/en/base/code
   - https://docs.vanillaframework.io/en/patterns/code-numbered
   - https://docs.vanillaframework.io/en/patterns/code-snippet

**Expected behavior**
1. Go to https://docs.vanillaframework.io/
2. Scroll down to **Text** and click **Code** 
3. This page will surface all Code related compoents
4. Contents menu to the right will contain:
   - Inline code
   - Code block
   - Code numbered
   - Code snippet

**Comment by matthewpaulthomas** [comment]
Four months later, these are still three separate pages, both [on docs.vanillaframework.io](https://docs.vanillaframework.io/en/patterns/code-snippet) and [on docs.staging.vanillaframework.io](https://docs.staging.vanillaframework.io/en/patterns/code-snippet).

**Comment by deadlight** [comment]
This has landed in the codebase and will be live with the next release of Vanilla Framework.

Cherry-picking changes to the docs between releases is a manual process and is reserves for more serious bugs until we change the system with v2.0. After v2.0 releases (sometime in the next month) release cadence will be ~2 weeks and any docs changes will be released alongside patch releases.
