### ISSUE TITLE
Tooltip cut off in example

### ISSUE THREAD

**Issue by hatched** [vanilla-framework/vanilla-framework#2066]
When hovering on "Left tooltip" button on https://docs.vanillaframework.io/en/patterns/tooltips the top of the tooltip is cut off in Firefox.

![screen shot 2018-11-28 at 10 47 38 am](https://user-images.githubusercontent.com/532033/49167475-0c303880-f2fb-11e8-9bb6-8c6c802745aa.png)

**Comment by deadlight** [comment]
Thanks for reporting this @hatched; this is, however, more of a website issue so I have re-filed it [here](https://github.com/canonical-websites/vanillaframework.io/issues/184) and will close this issue.
