### ISSUE TITLE
Heading spacing adjustment

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#2077]
## Pattern to amend

Text elements h*, .p-heading-*, p, small, etc.

## Visual

Provide a screenshot or link to a prototype of your pattern amendment.
![image](https://user-images.githubusercontent.com/2741678/49726902-f447a580-fc66-11e8-8fb1-e7ad76565095.png)

## Context

Over the last 6 months of heavy use of the vertical rhythm and spacing introduced in in vanilla 1.7*, I feel some adjustments are needed. In many cases, the spacing around headings is larger than it needs to be, so this proposal tries to remedy that.

Spacing under all headings is now much more consistent, and slightly reduced. This also gets rid of a few spacing related bugs due to styles overriding each other when the .p-heading-* classes are applied. I'll explain more in the working group meeting and show a working demo. This is just a placeholder issue until the demo is ready to push up.

Bonus features (will all go into separate prs):
1) .u-min-margin--bottom class that removes all but the baseline nudge compensation. We've had partial implementations of that in a few repos, but since this is a common need, I think we should have it in vanilla.

2) an "Eyebrow" - all headings accept a .has-eyebrow class, which makes it easy to place a small heading close to a large heading, a practice known as "eyebrow". In effect, it overrides thew large 3rem gap separating the end of a preceding paragraph from the next heading.

**Comment by lyubomir-popov** [comment]
draft PR: https://github.com/vanilla-framework/vanilla-framework/pull/2078

**Comment by kwm14** [comment]
## WG
- Approved with team
- @lyubomir-popov split proposal into 3 PR
- Proposal for 2.0 release
- Great contribution @lyubomir-popov you will receive a t-shirt inline with 2.0 release 💯

**Comment by lyubomir-popov** [comment]
The work has been moved to a new PR: https://github.com/vanilla-framework/vanilla-framework/pull/2107
