### ISSUE TITLE
Checkboxes have custom appearance but radio buttons don’t

### ISSUE THREAD

**Issue by matthewpaulthomas** [vanilla-framework/vanilla-framework#2084]
According to [the forms mockup](https://github.com/ubuntudesign/vanilla-design/blob/master/Forms/forms.png), checkboxes and radio buttons are supposed to have consistent appearance: a grey outline, checked with a white symbol on a navy background.

![forms cropped-checkboxes-and-radio-buttons](https://user-images.githubusercontent.com/19801137/50056960-fc6a7e00-015b-11e9-9bed-075df075f101.png)

Currently, however, a checked checkbox has a black checkmark on a transparent background:

![vanilla-checkbox-checked](https://user-images.githubusercontent.com/19801137/50056998-874b7880-015c-11e9-8d2f-eccfaa7c4fde.png)

And while Vanilla does alter the margins, padding, etc of radio buttons, it doesn’t seem to make any attempt to change their appearance:

![vanilla-radio-buttons](https://user-images.githubusercontent.com/19801137/50057131-173df200-015e-11e9-8966-4840eca2cc32.png)

This looks quite ugly in forms where checkboxes and radio buttons are found together, such as one @Lukewh has been working on:

![vanilla-radio-buttons-vs-checkboxes](https://user-images.githubusercontent.com/19801137/50057202-135e9f80-015f-11e9-85ee-e1312824c313.png)

What should happen: checkboxes and radio buttons either
- have consistent custom appearance, as shown in the mockup; or
- are both left with the browser’s default appearance.

**Comment by kwm14** [comment]
Thanks for reporting @matthewpaulthomas 

The latest [the forms mockup](https://github.com/ubuntudesign/vanilla-design/blob/master/Forms/forms.png) looks different to current build in Vanilla as it's ready for our 2.0 release 😄 

If you build and run our develop branch you will see that it matches the forms mockup.

![screenshot 2019-01-09 at 10 58 29](https://user-images.githubusercontent.com/17748020/50895642-8f66a300-13fe-11e9-83aa-99918f9d325e.png)
![screenshot 2019-01-09 at 10 58 44](https://user-images.githubusercontent.com/17748020/50895643-8f66a300-13fe-11e9-99bb-72fc44aeda11.png)

Planned 2.0 release will be at the end of this cycle, then the feature you and @Lukewh are woking on will look top notch 👍
