### ISSUE TITLE
Rename spacing variables

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#2100]

**Comment by lyubomir-popov** [comment]
Setting this to blocked by #2099, as if done in parallel it will cause a lot of conflicts with the refactor there.

**Comment by kwm14** [comment]
## Spacing examples
Recently discussed in Wg [here](https://github.com/vanilla-framework/vanilla-framework/issues/2140) and [here](https://github.com/vanilla-framework/vanilla-framework/issues/1923) I decided to have a quick look at some systems using spacing to see how they named their variables.

**Salesforce - Lightning Design**
https://www.lightningdesignsystem.com/design-tokens/#category-spacing

`$spacing-medium` = `1rem / 16px`
`$spacing-small` = `0.75rem / 12px`
`$spacing-x-small` = `0.5rem / 8px`

**Skyscanner - Backpack**
https://backpack.github.io/tokens/spacings

`$spacing-md` = `1.125rem / 18px`
`$spacing-sm` = `.75rem / 12px`
`$spacing-xs` = `.375rem / 6px`

**GitHub - Primer**
https://styleguide.github.com/primer/support/spacing/

`$spacer-3` = `16px`
`$spacer-2` = `8px`
`$spacer-1` = `4px`
