### ISSUE TITLE
Increase font-size: Combined pr including the changes made for the rest of the issues in this epic (for design review in percy)

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#2103]

**Comment by kwm14** [comment]
@lyubomir-popov demo PR can be found here: https://github.com/canonical-websites/www.ubuntu.com/pull/4428

**Comment by lyubomir-popov** [comment]
@deadlight @kwm14 made this pr against 2.0-refactor to ensure the new typography and spacing adjustments combined with the fontsize bump don't upset the baseline grid.

**Comment by lyubomir-popov** [comment]
@kwm14 I broke this down into a few separate issues (in the same epic), so I can associate a small, easy to review pr with each. 

Can we rename this to something like: "Prepare combined pr for visual review" and set the estimate to 3? This way all work will be accounted for under a more meaningful issue.

**Comment by kwm14** [comment]
@lyubomir-popov sure thing, that makes sense breaking the issues down so it's more understandable for us to know what you're doing 😉 

You can rename and estimate issues however you like 👍

**Comment by lyubomir-popov** [comment]
@kwm14 great, I renamed and changed the estimate to 3.
