### ISSUE TITLE
Update heading spacing

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#2104]
Link branch 👍

**Comment by lyubomir-popov** [comment]
Besides heading spacing, the linked pr refactors the huge _typography.scss file. This is so that the spacing-related rules can be edited easier, in a smaller file. 

Functionality has been moved to:

```@import 'base_font-declarations'; ``` – the fontface declarations
```@import 'base_measure'; ``` – max-widths 
```@import 'base_heading-definitions'; ``` – actual heading rules
```@import 'base_heading-mixins';``` – heading mixins

**Comment by lyubomir-popov** [comment]
Unable to link this to the PR, but here it is: https://github.com/vanilla-framework/vanilla-framework/pull/2117
