### ISSUE TITLE
Error states are not obvious

### ISSUE THREAD

**Issue by Greggless** [vanilla-framework/vanilla-framework#2115]
# Spot the errors
## 1 
![image](https://user-images.githubusercontent.com/23459065/51262939-3de48800-19ab-11e9-83d2-a6ee2f0b6606.png) 
## 2
![image](https://user-images.githubusercontent.com/23459065/51262876-22797d00-19ab-11e9-8772-dbae43534f11.png)

**Comment by anthonydillon** [comment]
This is not an issue with Vanilla framework. The Vanilla validation is like this: https://docs.vanillaframework.io/en/base/forms#validation-classes.

The example you have is a limitation with Marketo. We cannot customise the validation mark-up appended on Marketo.
