### ISSUE TITLE
Spacing terminology is hard to memorise

### ISSUE THREAD

**Issue by therealjuan** [vanilla-framework/vanilla-framework#2140]
Currently we are using spacing names like:

```
condensed
expanded
regular
intra
inter
```

![image](https://user-images.githubusercontent.com/8167677/52062847-2e4b6e80-2569-11e9-975e-6156a4df8989.png)

On other design systems like [Backpack from Skyscanner](https://backpack.github.io/tokens/spacings), [IBM Carbon DS](https://www.carbondesignsystem.com/guidelines/spacing/), [Pluralsight Design System](https://design-system.pluralsight.com/core/spacing/), [Space](https://sparkdesignsystem.com/patterns/fundamentals/space), [Bolt](https://bolt-design-system.com/docs/visual-language/spacing.html), [Ether](https://ether.thescenery.co/)  they use "design tokens" labelled in shirt sizes (or a variant) which is more understandable and easy to remember:

```
xsmall
small
medium
large
xlarge
xxlarge
```

Likewise, we can update intra and inter to something easier to remember like `in` or `out`. I find myself sometimes confusing both.

**Comment by clagom** [comment]
@deadlight is considering this for the space-variable work
