### ISSUE TITLE
Vanilla docs pretend that docs for older versions are available

### ISSUE THREAD

**Issue by bartaz** [vanilla-framework/vanilla-framework#2150]
https://docs.vanillaframework.io/en/ have a select input in top left corner with a version number that suggests that docs for other versions are accessible.
This doesn't seem to be the case (not sure if it ever was and if there are any plans do to so in future).

If docs for older (or/and upcoming) versions are not available version select is only a source of confusion.

<img width="514" alt="screenshot 2019-02-05 at 15 49 06" src="https://user-images.githubusercontent.com/83575/52281316-2f600f80-295e-11e9-9182-52397c140fb1.png">

It would be great if docs for older versions would be available. Not all projects are (or can be) moved to never versions, so being able to reference older docs would be very helpful sometimes.

**Comment by kwm14** [comment]
@bartaz thanks for reporting. I actually removed the select dropdown last year for the same reason you mentioned above.

https://github.com/vanilla-framework/vanilla-framework/pull/2039

Not sure how it's re-appeared 🤔  @deadlight do you think this happened with the latest release of v1.8.1?

**Comment by deadlight** [comment]
@kwm14 yeah, it could have been a mistaken merge. We can fix this.

**Comment by kwm14** [comment]
@deadlight Sweet, I'll add the small tasks to fix 👍

**Comment by kwm14** [comment]
As the code has already been removed by me in a previous PR, no work needs to be done. I've asked @anthonydillon to back-port documentation changes 💯
