### ISSUE TITLE
Slack icon is out of date

### ISSUE THREAD

**Issue by fitojb** [vanilla-framework/vanilla-framework#2153]
The Slack icon provided here: https://github.com/vanilla-framework/vanilla-framework/blob/17485ef2d7d7cff1165b27c5ceb4a1a6d7944775/docs/sass/styles.scss#L202

is out of date. Slack [rebranded](https://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_slack_by_pentagram_and_in_house.php) on 16 January.

**To Reproduce**
1. Go to https://docs.vanillaframework.io/en/
2. Scroll down to “Getting help”.

**Expected behavior**
The icon should depict a symbol composed of eight bars, in place of the current octothorpe.

**Screenshots**
![screenshot from 2019-02-14 11-08-57](https://user-images.githubusercontent.com/554953/52783302-695d9f80-3049-11e9-8edd-d46dfe69cb82.png)

**Comment by deadlight** [comment]
Thank you for reporting this issue, we will update the logo.
