### ISSUE TITLE
Spinner icon in button doesn't inherit the text colour

### ISSUE THREAD

**Issue by steverydz** [vanilla-framework/vanilla-framework#2178]
# Description
When using the spinner icon within a button, instead of inheriting the colour of the text (white in this case) it remains grey, making it hard to see.

# To reproduce
Add the spinner icon to a button such as `p-button--negative` and see that isn't clearly visible due to its colour

# Expected behaviour
When using the spinner icon within a button it should be the same colour as the text

# Screenshots
![screenshot from 2019-03-01 09-23-23](https://user-images.githubusercontent.com/501889/53628894-2502ff80-3c04-11e9-94db-03b65e8be64a.png)

**Comment by kwm14** [comment]
@steverydz this may help with your issue, we actually have light and dark icon sets. So if you're using icons on a dark background I'd recommend using this set 😄 

- https://docs.vanillaframework.io/en/patterns/icons#standard-dark
- https://github.com/vanilla-framework/vanilla-framework/blob/develop/scss/_patterns_icons.scss

Hope this helps 👍

**Comment by steverydz** [comment]
Closing as this can be solved with the `is-light` utility class.
