### ISSUE TITLE
Need to standardise avatar design

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#316]
## Context

Currently we have at least 2 different avatar styles: squircle with inset shadow, and circle.

We should decide if we're making avatars circular across the sites and add that pattern to Vanilla.

@Lucapaulina

**Comment by yaili** [comment]
@spencerbygraves are avatars in juju always circular?

**Comment by spencerbygraves** [comment]
@yaili yes, we're moving to all circular.

**Comment by anthonydillon** [comment]
@yaili we don't have any avatar patterns in Vanilla. Can this be closed?

**Comment by yaili** [comment]
It should be moved to design repo

**Comment by anthonydillon** [comment]
@yaili could you move this to a design repo please.

**Comment by yaili** [comment]
This issue was moved to ubuntudesign/vanilla-design#18
