### ISSUE TITLE
Allow for modular build of Vanilla

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#412]
## Proposal

Users may not want to use the entire suite of tools and components contained within Vanilla nd may only want to pick a subset. 

We should allow for this and document how it can be easily done.

One possible solution would be to use an open source CDN such as http://www.jsdelivr.com to concatenate different css files and allow easy <link> tag for including them.

**Comment by yaili** [comment]
Is this Type: Enhancement, Priority: Low?

**Comment by anthonydillon** [comment]
@barrymcgee we do provide this by allowing them in import the build instead of the framework and cherry include that patterns they want. Granted this is not well documented.

**Comment by anthonydillon** [comment]
> I'm not sure this cherry-pick approach from any part of the framework will work as it's only really the patterns part of the stack that is fully encapsulated.

> All pattern styling is based on the reset already being applied not to mention other base styles, you can't just knock out lower layers and expect the patterns to still stand up.
