### ISSUE TITLE
check if cyrilic works in ubuntu font

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-framework#699]

**Comment by barrymcgee** [comment]
@pmahnke Can you provide more context please? How should this be tested?

**Comment by pmahnke** [comment]
Basically, we need to make sure we do not restrict the fonts in Vanilla or
offer good defaults for character sets not included (I think Chinese for
example).

**Comment by EugeneDae** [comment]
Nope. This is `-apple-system` in effect:

![ubuntu](https://cloud.githubusercontent.com/assets/980835/20018216/e6ba3d82-a2d7-11e6-94a7-8752749d014a.png)

**Comment by yaili** [comment]
@pmahnke what is the next step here?
