### ISSUE TITLE
Vanilla local development doesn't state you need Docker

### ISSUE THREAD

**Issue by richmccartney** [vanilla-framework/vanilla-framework#700]
## Process
1. Run `./run build`
2. Told I require a docker daemon to be running to connect
## Expected result

I expected this to run the build of vanilla with out any other requirements apart from `npm i`
## Current result

It tells me to run the docker daemon but it doesn't state anywhere in the documentation that this is required at all and is a pre-req for building Vanilla. This was done on OSX I am not sure what the process would be for Windows developers.

**Comment by yaili** [comment]
Is this a fix to the readme file?
