### ISSUE TITLE
_patterns_navigation.scss should include all its dependencies

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#715]
If I try to only include the file `_patterns_navigation.scss`,

``` scss
@import 'vanilla-framework/scss/patterns_navigation';
@include vf-p-navigation;
```

I get this error:

``` node
Error: vanilla-framework/scss/_patterns_navigation.scss
Error: ".p-navigation" failed to @extend "%clearfix".
       The selector "%clearfix" was not found.
       Use "@extend %clearfix !optional" if the extend should be able to fail.
        on line 4 of node_modules/vanilla-framework/scss/_patterns_navigation.scss
>>     @extend %clearfix;
   ----^
```

All patterns should include their own dependencies so they can be used in isolation if required.

**Comment by yaili** [comment]
Notes from working group meeting:
- concerns about duplication:
  - there should be no duplication if it's using mixins or variables
  - the resulting CSS shouldn't have duplication
- maintenance overhead for this is quite hard
- is the increased complexity worth the benefit?
- create utilities mixin that includes all globals placeholder and make requirement that all components to include those - would only have to maintain one file - would this break IT CSS?
- do we want this ability in Vanilla right now? - maybe for web components

Next steps:
- move the placeholders to outside the mixins
- this will make sure that all placeholders are global and when you include Vanilla you can cherry-pick patterns
- documentation needs to specify that if you want to cherry-pick you need to include Vanilla and then select patterns

**Comment by barrymcgee** [comment]
Placeholders outside mixins issue was resolved by https://github.com/vanilla-framework/vanilla-framework/pull/907

**Comment by barrymcgee** [comment]
README now contains - "If you don't want the whole framework, you can just @include specific parts - e.g. @include vf-b-forms."
