### ISSUE TITLE
Headings padding need to be reviewed for linear text, to allow for visual association

### ISSUE THREAD

**Issue by MonicaSG** [vanilla-framework/vanilla-framework#719]
For sections of content on a page where the text not contained in a box we need more padding on top of a title than below to aid scannability of the content. At the moment the equal padding makes it very hard to know what content is associated with which title, it also visually makes it hard to scan the sections.

**Comment by yaili** [comment]
Next steps:
- Monica will share findings, see if there's any suggested balance
- Spencer will try some values for new margin-top

**Comment by MonicaSG** [comment]
I struggled to find any of the articles that I read quite a while ago where it talks about Heading padding specifically. But here is some reference material:
- " headers closer to paragraphs are seen as related via context." https://designshack.net/articles/layouts/web-design-best-practices-minimalism-typography/
- "Golden ratio is a magical number 1.618" http://conversionxl.com/8-universal-web-design-principles-you-should-to-know/
- "White space helps to offset large amounts of text and helps the user’s eyes flow through the text." https://www.smashingmagazine.com/2009/03/10-principles-for-readable-web-typography/

This format is regularly used amongst the majority of the reputable website as well as those above, such as:
- https://www.coursera.org/learn/machine-learning
- https://www.gov.uk/take-pet-abroad
-  https://www.nngroup.com/articles/mobile-content/

**Comment by yaili** [comment]
Related to #732

**Comment by barrymcgee** [comment]
Closing this issue as the conversation has now moved to #960
