### ISSUE TITLE
We should standardise spacing in Vanilla

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#728]
Inspired by an article shared by @yaili (https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62#.rk9ky220b), we should standardise the spacings in Vanilla for consistency and flexibility.

Currently most spacing in Vanilla is covered by:

* 0 .5rem - 8px
* 0.8125rem - 12px
* 1rem - 16px 
* 1.5rem - 24px

These should be given an appropriate naming convention (t-shirt sizes) and the code refactored accordingly. Any outlying spacing not covered by these values should then be pulled into line.

**Comment by yaili** [comment]
Cool. Would you mind including a couple of examples per size? My first instinct is that 8px is too small for the "smallest" and 24px is too small for the "largest" but with examples it's easier to assess. Thanks!

**Comment by yaili** [comment]
Next steps:
- Do a catch-all of all the values we're using
  - Add examples to values
- Investigate how this will affect the existing grid
- Is 8px too small? 24px too small for largest value
- We should define a scale
- Confirm with @barrymcgee the implementation suggested (use spacing variables like colour variables are used within patterns): e.g. ```.box { padding: $small; }```

**Comment by barrymcgee** [comment]
I think t-shirt sizes is probably the least complex way to do this?

(rem values tbc)

0 .5rem - 8px - $x-small
0.8125rem - 12px - $small
1rem - 16px - $medium
1.5rem - 24px - $large
etc

..and yes, implementation would be like: `.box { padding: $small; }`

**Comment by richmccartney** [comment]
I believe this will get effected by @spencerbygraves work on vertical alignment after speaking to myself and @yaili. We should get new updates soon and be able to set the amount of sizes we need plus what the responsive sizes should be.

**Comment by barrymcgee** [comment]
This article is very relevant: http://alistapart.com/article/learning-from-lego-a-step-forward-in-modular-web-design

**Comment by anthonydillon** [comment]
Very good article! Would like to see this consistency throughout the
framework but think it could be hidden/seamless to a user of the framework.
Thoughts?

**Comment by yaili** [comment]
I would need to read this again with more time to understand fully. Is it basically an utility class that applies padding to the innermost element?

**Comment by barrymcgee** [comment]
So - is the action here to implement a scale such as:

```scss
$xx-small: 1rem*.25; // 4px
$x-small: 1rem*.5; // 8px
$small: 1rem*.75; // 12px
$medium: 1rem; // 16px
$large: 1rem*1.5; // 24px
$x-large: 1rem*2 // 32px
$x-large: 1rem*3; // 48px
```

...and then work through each pattern and swap out corresponding spacing values with variables as above? Any spacing values which fall out outside of the above scale should then be flagged for review?

**Comment by yaili** [comment]
Yes: the next steps are listed in [my previous comment](https://github.com/vanilla-framework/vanilla-framework/issues/728#issuecomment-270879211). I don't know about the comments on the 23rd, I didn't understand the article.

**Comment by yaili** [comment]
@barrymcgee @anthonydillon will there be any value changes in existing patterns? If so, can you list them for review?

**Comment by anthonydillon** [comment]
No changes, this branch simply replaces the values with variable names.

**Comment by barrymcgee** [comment]
Worth mentioning though that the next step here is to highlight the patterns with spacing that do not directly swap out.

**Comment by yaili** [comment]
OK, if we find any that should be added as issues in the design repo to update.
