### ISSUE TITLE
Wish to have an easy node.js script for compiling and adapting the scss into a css file

### ISSUE THREAD

**Issue by bottinbio** [vanilla-framework/vanilla-framework#729]
Really love that framework and using it for my websites about organic farming. But being more a gardener than a coder I find it very hard to compile the thing and adapt it to my needs (I still know some coding because I have a lot of free time during winter). So if somebody has some time a simple node JavaScript would helps a lot of us mere mortals....

**Comment by barrymcgee** [comment]
@bottinbio Good to hear you love the framework!

Vanilla Framework is already available as an NPM package here: https://www.npmjs.com/package/vanilla-framework

Is that what you have been using? If so, where are you becoming unstuck?

**Comment by bottinbio** [comment]
@barrymcgee I tried to use the NPM package, but I need a dead simple way to at generate CSS files (no personalizations for now)

**Comment by bottinbio** [comment]
./run build
Unable to find image 'jan:latest' locally
Pulling repository docker.io/library/jan
docker: Error: image library/jan:latest not found.
See 'docker run --help'.

**Comment by barrymcgee** [comment]
Sorry @bottinbio - I missed this reply from you. Did you get sorted in the end?

**Comment by anthonydillon** [comment]
I believe the hotlink should help you simply include the CSS on your website without dealing with building. Please reopen if you have an issue.
