### ISSUE TITLE
Improve typographic scale

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#732]
The currently implemented [typographic scale](https://docs.vanillaframework.io/base/typography/) on Vanilla could do with some improvements, as it was a bit rushed for release of v1.

The initial idea with the current scale was to keep to a strict vertical rhythm, but I don't think this has worked. We should review the font sizes and spacing between elements and update them with values that work well on large to medium to small screens.

It should include:
- h1 to h6 headings
- paragraph
- blockquote
- inline code and code block
- ordered and unordered lists (current spacing is too tight)
- definition lists
- consider margin top of text elements that follow other text elements (e.g. h1/h2/h3/etc that follows paragraph, lists that follow headings or paragraphs, blockquotes that follow headings/paragraphs, etc.)

See also issue #719

**Comment by barrymcgee** [comment]
@yaili I think they should be split into separate tasks? Is there a spec for these typography rules yet?

**Comment by yaili** [comment]
@barrymcgee they are all interconnected, so it has to be done as one piece, if that's what you mean… @spencerbygraves could you add the latest spec in the comments, please? Thanks!

**Comment by yaili** [comment]
Here are the latest specs from @spencerbygraves - the next step should be to do a demo of Spencer's proposal so we can evaluate it on different devices and tweak if necessary. After that's done we can implement in Vanilla.

![vanilla type scale - block elements](https://cloud.githubusercontent.com/assets/223966/23551938/1c168e22-0011-11e7-8078-83ae04247032.png)
![vanilla type scale - form elements float label](https://cloud.githubusercontent.com/assets/223966/23551941/1f95743c-0011-11e7-969a-6d7b9479d8ae.png)
![vanilla type scale - form elements](https://cloud.githubusercontent.com/assets/223966/23551942/1ffe308a-0011-11e7-8095-73736db648f0.png)
![vanilla type scale - headers](https://cloud.githubusercontent.com/assets/223966/23551943/2014348e-0011-11e7-92fb-4ca69f3ba1f3.png)

**Comment by spencerbygraves** [comment]
Adding these for different screen sizes.

**Large**

Title sizes

- h1 = 48px
- h2 = 36px
- h3 = 28px
- h4 = 24px
- h5 = 20px
- h6 = 16px regular
- p = 16px

![image](https://cloud.githubusercontent.com/assets/9105999/23947211/afa143fe-0975-11e7-8a8a-903336df61c1.png)

**Medium**

Title sizes

- h1 = 40px
- h2 = 32px
- h3 = 24px
- h4 = 22px
- h5 = 18px
- h6 = 16px regular
- p = 16px

![image](https://cloud.githubusercontent.com/assets/9105999/23947239/cbd41ed4-0975-11e7-95f1-31c2a0776ac9.png)

**Small**

Title sizes

- h1 = 32px
- h2 = 28px
- h3 = 24px
- h4 = 22px
- h5 = 18px
- h6 = 16px regular
- p = 16px

![image](https://cloud.githubusercontent.com/assets/9105999/23947278/f4d71cf0-0975-11e7-97d8-03fad151e65d.png)

**Comment by barrymcgee** [comment]
The latest heading changes have been added as a [separate proposal ](https://github.com/vanilla-framework/vanilla-framework/issues/960) and should not block the [PR already submitted](https://github.com/vanilla-framework/vanilla-framework/issues/955).

**Comment by barrymcgee** [comment]
Closing this issue as the conversation has now moved to #960
