### ISSUE TITLE
Navigation patterns breaks in tablet view

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#736]
The navigation pattern should gracefully deal with an infinite number of navigation items, regardless of the number of items in the navigation label.

Currently - adding more than four medium sized navigation items breaks the navigation in medium sized screens.

https://www.dropbox.com/s/xvrezizgg7b2jr5/Screenshot%202017-01-12%2015.07.58.png?dl=0

**Comment by yaili** [comment]
@barrymcgee should this be in the design repo?

**Comment by barrymcgee** [comment]
@yaili Yes.. needs a design solution.

**Comment by barrymcgee** [comment]
@yaili Does this have a corresponding design issue or should I create one?

**Comment by yaili** [comment]
Yes, it's linked above.

**Comment by anthonydillon** [comment]
Closed with https://github.com/vanilla-framework/vanilla-framework/issues/1042
