### ISSUE TITLE
[Proposal] Utility naming conventions and breakpoints

### ISSUE THREAD

**Issue by richmccartney** [vanilla-framework/vanilla-framework#745]
Referencing the conversation started here #743 I have seen we are creating utility classes which have multi-purpose, named too loosely and neglect the fact we should be factoring in responsive development and usability.

### Multi-purpose

Utility classes should only be used for one purpose and thats it, I suggest we review all utility classes and make sure we are not trying to do more than 1 property change per class. These classes are to be used as trumps which override a specific property. @anthonydillon has worked on the alignment classes which not only assigns ```text-align: center``` but also effect ```justify-content: center```.

I feel they should be described accordingly and in their own classes. ```justify-content: center``` sub-property of the Flexible Box Layout module and should fall under that category of utility trump classes. E.g ```u-flex-justify-content--center / flex-start / flex-end / space-between / space-around```.

### Naming

Again pointing at what we are changing, trump classes should call out exactly what they're affecting. In ```_utilities_visibility.scss``` I feel classes within this file should be explicit. I am affecting the display property and should be named accordingly e.g ```.u-display--inline``` or ```.u-display--none```. This also gives the options to add all ```display``` options as trump classes.

Using ```visible``` should relate again to the ```visibility``` property and being a clear trump class.

### Responsive

Classes should incorporate a strong responsive outlook and especially for trump/utility classes. An element might be best design to align left on desktop but the design or flow of UX would best see that element as centred on mobile. 

I suggest we add responsive prefix to our classes e.g

```.u-xs-text-align--left``` ```.u-sm-text-align--left``` ```.u-md-text-align--left``` ```.u-lg-text-align--left``` 

These class examples will only trump the text-align property on their respective size. I believe this will lower certain issues and over specificity for patterns when not required and also improve the overall flexibility of our framework and bring it more in line with other powerful frameworks which follow this mantra of not excluding breakpoints for utility classes.

**Comment by yaili** [comment]
Some notes from working group meeting:
- the example of multi-purpose utility classes can be justified (2 classes are okay)
- @richmccartney could you split the proposal into two: one about multi-purpose and one about responsive

**Comment by barrymcgee** [comment]
@richmccartney This issue has been awaiting action for quite a while, can you get to it soon?

**Comment by pmahnke** [comment]
@barrymcgee FYI, he has been on holiday for a week now... but it has been a month.

**Comment by anthonydillon** [comment]
@richmccartney can you action this proposal for the next working group meeting please.

**Comment by nottrobin** [comment]
@richmccartney closing this now, please feel free to re-open it if you get a chance to update it as mentioned.
