### ISSUE TITLE
Develop branch should create demo on each merge

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#757]

**Comment by barrymcgee** [comment]
This could be easily achieved using Firebase: https://marlosoft.net/posts/automatic-deploy-firebase-github-travis.html

**Comment by yaili** [comment]
@barrymcgee is this done?

**Comment by barrymcgee** [comment]
@yaili No, not yet.

**Comment by yaili** [comment]
@barrymcgee is it in progress, or in backlog? what's the priority?

**Comment by barrymcgee** [comment]
Not in progress that I know of and thinking about it, now that we create a demo for each PR, perhaps this isn't needed anymore. Closing.
