### ISSUE TITLE
Setup Vanilla docs should use documentation-builder

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#758]
Vanilla documentation is almost in the right format
- Take out custom Metalsmith that Barry built and use Robin’s system instead
- Other docs’ url are docs.ubuntu.com/xyz
- Need to build functionality for having own url like docs.vf.io
- We won’t have a transitionary phase with 302 to docs.ubuntu.com/vf
- We will rewrite docs to be built with documentation builder 
- Should have a landing page for vf.io ready for this
- JS script to cherry pick example markup

**Comment by yaili** [comment]
@barrymcgee what's the status/next steps of this issue? Is it ready to be worked on?

**Comment by barrymcgee** [comment]
@yaili It's done.
