### ISSUE TITLE
Refactor docker build process to improve workflow

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#759]
Use ./run --extra-nodemodules ~/vf to build vf.io link to local dependancies

**Comment by nottrobin** [comment]
This was solved for www.ubuntu.com (which is where it's really needed) in https://github.com/canonical-websites/www.ubuntu.com/pull/1411

**Comment by barrymcgee** [comment]
But shouldn't `vanilla-framework` also use the same model - using docker to manage dependencies etc?

**Comment by nottrobin** [comment]
@barrymcgee it should. But I don't think this is what this issue is about, since the "--extra-modules" stuff will never be used on `vanilla-framework` itself. I'm totes happy for there to be another issue about adding it though, or a PR :)
