### ISSUE TITLE
Create social media posts automatically in the build

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#762]

**Comment by yaili** [comment]
@barrymcgee Can you add more detail to this issue?

**Comment by barrymcgee** [comment]
We should be able to use something using IFTTT that would post a message like -

"We've just released vX.X.X of Vanilla Framework! 🎉 View the latest release notes here: [link]"

..as part of the Jenkins release process.

**Comment by anthonydillon** [comment]
I have been tweeting with the latest releases. I have templated a tweet in the social media document. I like too add a personal message with a summary of the changes. I hadn't had much trouble doing this. 

I would opt to close this issue until we find an issue with it.

**Comment by yaili** [comment]
Yes, I think we can use that format and add one or two things that are relevant for that particular release, like:

> Vanilla 1.2.0 has just been released! Updated card highlighted pattern, new utilities and more: https://github.com/vanilla-framework/vanilla-framework/releases/tag/v1.2.0

**Comment by anthonydillon** [comment]
Closing for now. Until it becomes a problem.
