### ISSUE TITLE
Improve heading documentation

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#831]
Current documentation over two pages is confusing, should be merged and simplified:
- https://docs.vanillaframework.io/base/typography/
- https://docs.vanillaframework.io/patterns/headings/

**Comment by yaili** [comment]
Issue/proposal #881 is related to this one.

**Comment by barrymcgee** [comment]
Closed by https://github.com/vanilla-framework/vanilla-framework/pull/936
