### ISSUE TITLE
Should we use rems unit for all values

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#854]
Currently, we use rems for padding and font-sizing. There has been a discussion about using rems for all values. For example, border-radius. 

We need to come to an agreement on with properties should be set as rems.

**Comment by yaili** [comment]
We will use pixels for styling properties for now:
- border-width
- border-radius
- box-shadow

In general, typography, layout and positioning properties should use rems.

Would be good to get some external feedback on any usability and/or accessbility issues that doing this might cause?

**Comment by anthonydillon** [comment]
Yes, issue created: https://github.com/ubuntudesign/webteam-practices/issues/16
