### ISSUE TITLE
Update code numbered pattern

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#856]
## Is this a proposal or an amendment?

- Amendment

If amendment, what is the name of the pattern to be amended?
Code numbered

## Visual

Current build with right-aligned line numbers:
![code numbered vanilla framework examples2](https://cloud.githubusercontent.com/assets/1413534/22974938/8ab1ca46-f37c-11e6-84e3-9a42af3ae3ff.png)

Proposal build with background-color behind the line numbers:
![code numbered vanilla framework examples](https://cloud.githubusercontent.com/assets/1413534/22974955/a5ec3710-f37c-11e6-8f86-0549ecfe3231.png)

## Context
A recent update to the numbered code block required the line numbers to right-align as to prevent the numbers with double digits pushing out single digit number lines. This requires the number area to be a set width to allow room for the numbers to grow to the left.

This styling makes it clear the numbers are separate from the code content. Giving a clear indication of the length of growth too.

The current line number growth with the attached design is 9999.

**Comment by yaili** [comment]
Cool. What colour is the background in the proposal? cdcdcd?

**Comment by anthonydillon** [comment]
Yes, `$color-mid-light`.

**Comment by anthonydillon** [comment]
This has been validated but has no approved spec. Did we decide we were happy with `$color-mid-light` as the background of the numbers?

**Comment by barrymcgee** [comment]
@yaili Can you confirm the above please yay or nay so we can it moving again? Ta!

**Comment by yaili** [comment]
@barrymcgee this is blocked until the issue referenced in vanilla-design is signed off. I will update the design with the feedback from the design review (which we had today) and it should be ready to work on by Thursday. Thanks!

**Comment by yaili** [comment]
Design spec: https://github.com/ubuntudesign/vanilla-design/tree/master/Code
