### ISSUE TITLE
Headings have mismatched elements and classes in docs

### ISSUE THREAD

**Issue by earnubs** [vanilla-framework/vanilla-framework#878]
Visit: https://docs.vanillaframework.io/patterns/headings/

Headings have mismatched elements and classes, eg:

```<h6 class="p-heading--one">Heading six</h6>```

Suggest tag and class should match.

**Comment by barrymcgee** [comment]
@earnubs That's actually deliberate. The purpose of that pattern is to allow users to assign different visual heading styles based on their semantic equivalents. 

For example, in a sidebar, headings may be semantically `<h3>` according to page flow but visually the design dictates they should use a `.p-heading--four` style.

Do you find the explanation on that page ambiguous? If so, perhaps it could be improved?

**Comment by earnubs** [comment]
@barrymcgee Aha! Well that's a great feature that's kind of made to look like a mistake in the docs ;)

In the past I've used class names that didn't imply level (1-6) but style (heavy, mid, light), but maybe in this case a simple line would be enough to help the likes of me:

```
Heading classes are not tied to elements and can be freely mixed, for example you can apply `p-heading--one` style to an `h3` element if that better suits your document style and tree.
```

Perhaps with a regular h1-h6 list before that, and a mixed up example after?

But I'm also happy if you close this issue without change.

**Comment by barrymcgee** [comment]
@earnubs We're aware there is room for improvement docs wise across all patterns and your suggestion sounds like a sensible enhancement to me. Anything which makes it clearer to the user the why & where is  👍🏻

**Comment by yaili** [comment]
Hi, I only noticed this issue now. There are 2 open issues to improve heading documentation:

- https://github.com/vanilla-framework/vanilla-framework/issues/831
- https://github.com/vanilla-framework/vanilla-framework/issues/881

So hopefully this should be done soon. 👍

**Comment by barrymcgee** [comment]
Closed by https://github.com/vanilla-framework/vanilla-framework/pull/936
