### ISSUE TITLE
How can we avoid having two pages called List in docs

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#880]
If someone is reading our documentation to know which types of lists are available in our framework, it's odd that there are lists in two different pages. In some pages, I've added a section at the bottom of the page with the title "Related" that links to other relevant pages — for example, link to Buttons in Forms. In the case of lists though I think we should only have one page. Is this something that can be done in the documentation? I don't mean to change the way we divide the actual sass files.

**Comment by anthonydillon** [comment]
Docs could have just one lists page with both the base and patterns in it
as we have separate example pages now.

**Comment by yaili** [comment]
Thought of something else: unordered, ordered and description lists are in theory part of typography. Maybe "Lists" only exists in Patterns, and the base lists move to Typography? E.g. http://getbootstrap.com/css/#type

**Comment by anthonydillon** [comment]
Agreed to move the base list documentation to typography.
