### ISSUE TITLE
Move the Heading docs to the Typography page

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#881]
Currently we have the Typography page https://docs.vanillaframework.io/base/typography/ and the Headings page https://docs.vanillaframework.io/patterns/headings/ which I think is confusing.

I don't think we need more than what Boostrap does where they just say you can also use .h1 to .h6 classes: http://getbootstrap.com/css/#type

Thoughts?

**Comment by barrymcgee** [comment]
The only problem with this is that it breaks the ITCSS convention where the 'base' level is where styling is only applied to directly to elements and patterns is are where patterns are styled using classes... hence why we have sidebar headings to make that distinction?

**Comment by anthonydillon** [comment]
We can keep base heading examples but remove from the documentation?

**Comment by anthonydillon** [comment]
This has been approved.

**Comment by yaili** [comment]
Hi. I'm confused. We agreed to remove headings from docs and only reference them in typography  but the change that was done doesn't reflect that decision.

**Comment by barrymcgee** [comment]
The change this week also included the change agreed here: https://github.com/vanilla-framework/vanilla-framework/issues/878

**Comment by yaili** [comment]
I see. That wouldn't address the issue described in this proposal though. I could update the typography docs page to include headings and heading classes and propose it in a branch, shall I do that?

**Comment by barrymcgee** [comment]
@yaili Yes, please do...

**Comment by anthonydillon** [comment]
@yaili I would like to free this one up for any of us to work on. I will update the title of the issue to reflect the task. If copy is due to be updated then we should create a new issue for that.
