### ISSUE TITLE
Is the injecting examples work complete?

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#889]
Looking at the docs as they stand, there seems to be two ways the docs are presented.

Link out to example: https://docs.vanillaframework.io/en/base/table

Example embedded: https://docs.vanillaframework.io/en/patterns/headings

Is there still work to be completed?

**Comment by anthonydillon** [comment]
Yes there is work to be done. I'll create tasks.

**Comment by anthonydillon** [comment]
The issues have been created to compete this task.
