### ISSUE TITLE
Pull quote doesn't match design spec

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#904]
Comparing the latest version of pull quote: http://127.0.0.1:4000/vanilla-framework/examples/patterns/pull-quotes/ from https://github.com/vanilla-framework/vanilla-framework/pull/901

with design: https://github.com/ubuntudesign/vanilla-design/blob/master/Pull%20quote/pull-quote.png

- [ ] the space between the left quotation mark and the start of the text seems too tight - the space between text and right quotation mark seems correct
- [ ] in small screens, the second and following lines of text seem to have too much left indentation (they should all align left)

**Comment by grahambancroft** [comment]
The right quotation also wraps

<img width="933" alt="screen shot 2017-03-05 at 19 12 10" src="https://cloud.githubusercontent.com/assets/2152/23590428/b6566e04-01d7-11e7-8e68-839911566dbd.png">
