### ISSUE TITLE
[Proposal] Include markup for panels

### ISSUE THREAD

**Issue by slimjim777** [vanilla-framework/vanilla-framework#906]
## Proposal
Include markup for panels that can be used to highlight a section or for widget design (like an accordion)

## Visual

http://getbootstrap.com/components/#panels
https://certification.canonical.com/pools/#/pools/42

## Context

Highlighting a section of content, similar to a card, but providing a darkened background e.g. similar to the `<pre>` code sections here: https://docs.vanillaframework.io/en/patterns/card.

Providing markup for widgets like an accordion.

Some panels may just have a header (like a collapsed accordion section), just content (like a container for a table or highlighted section of content), or both.

## State

The panel itself does not have state, though it would be helpful to have different colour themes (like buttons e.g. panel--brand, panel--neutral). For an accordion, it does have the concept of open/closed, but that is just a matter of whether the panel has content or not (which would be handled outside of vanilla).

## Progressive enhancement

Panels are containers for content - header or body or both. So There should not be any scaling issues as such.

**Comment by anthonydillon** [comment]
We may look at extending the card component. But will require some more design exploration.

**Comment by barrymcgee** [comment]
Design exploration task added here: https://github.com/ubuntudesign/vanilla-design/issues/11
