### ISSUE TITLE
Create Percy blog post

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#915]

**Comment by barrymcgee** [comment]
http://design.canonical.com/?p=40281&preview=true

**Comment by barrymcgee** [comment]
@yaili Are image captions on the blog supposed to look like this? https://cl.ly/2c2P2k3P1d32

**Comment by yaili** [comment]
@barrymcgee hi, no, we never properly did captions, I tend to use an em tag around the caption. You can check another post for an example, thanks.
