### ISSUE TITLE
Write an introductory guide

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#921]
Introduce people to how to use Vanilla Framework with example markup, and how to include it and build it in your project.

**Comment by yaili** [comment]
@nottrobin this is the Get started page on VF's site. I will assign to me and @anthonydillon and will share copy doc once we've got something.

**Comment by yaili** [comment]
We've done a draft copy doc and shared it with you for comment. Closing this for now, but reopen if needed.
