### ISSUE TITLE
Link patterns should be simplified

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#925]
I think the link patterns are too complex and should be simplified. 

By altering multiple aspects of a link in each variant as the current spec suggests means a lot of overriding CSS needs to be written, especially when two variants need to be used in conjunction with each other (strong/external). 

I think we can achieve a similar outcome by changing only one aspect of a link between variants - for example, only the font-weight should change for the "strong" variant, not the font-weight _and_ color.

This also provides a simpler proposition for the user. Further link permutations should be picked up at theme level.

I've made a demo here: http://codepen.io/barrymcgee/pen/aJNjBe

**Comment by anthonydillon** [comment]
Strong does need to remain different in more than one property so we will keep what we have and will keep an eye on the maintenance of links.
