### ISSUE TITLE
Vanilla Framework or Vanilla framework?

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#926]
Can we please clarify this?

I thought it was Vanilla Framework, but I don't have a preference for either. It's the inconsistency that isn't great. 

Can I have a show of hands for each of the alternatives? Add anything if you have any Reasons®.

Thanks!

**Comment by barrymcgee** [comment]
I only changed to using `Vanilla framework` because I thought that's what you preferred? 🤔

My preference is `Vanilla Framework`

**Comment by anthonydillon** [comment]
My preference is Vanilla Framework too

**Comment by yaili** [comment]
I spoke with @pmahnke and he agrees with Vanilla Framework, so it seems we all agree. I'm closing the issue.
