### ISSUE TITLE
Docs need example helper

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#942]
In the previous version of the docs, certain examples such as the equal height util had a helper to outline the borders of the containers. 

This was different to the markup that was displayed as an example but now that the same markup is used for both, these outlines no longer appear making examples slightly inadequate.

**Comment by barrymcgee** [comment]
Related #939

**Comment by barrymcgee** [comment]
I've been struggling with this and can't quite get to a solution that doesn't seem hacky/dirty.

This is what the Equal Height Util docs look like right now:

<img width="1094" alt="screen shot 2017-03-10 at 16 29 11" src="https://cloud.githubusercontent.com/assets/505570/23803526/bcba1374-05ae-11e7-8f40-b400456e2fb1.png">

This example fails to demonstrate the effect of applying the util class. 

We need to visually demonstrate the effect of applying the util, ideally demonstrating where the elements are in relation to the parent, like so:

<img width="1099" alt="screen shot 2017-03-10 at 16 27 08" src="https://cloud.githubusercontent.com/assets/505570/23803501/ab8c96f8-05ae-11e7-8eb7-195cc1187be6.png">

However, because both the example and the code to create the example displayed within the `<code>` block are both pulled from the same source, we don't want to pollute the `<code>` snippet with the inline styles needed to accurately display the example.

I explored a couple of options:

Option one - Add a few of helper classes to VF - `.eg-o`, `.eg-p` and `.eg-m`

```css
.eg-o {
  outline: 1px dashed #333;
}
.eg-p {
  padding: 1rem;
}
.eg-m {
  padding: 1rem;
}

```

These could then be added where needed and stripped from the code before they are injected into the code block. The issues here are that those helper classes would need to be included in Vanilla itself as they need to be used inside the iframe which would really mean they should be documented as util in their own right. Also, those three cases might not cover all the styles needed to accurately display all the examples.

Option two - add a class of `.inline-styles` to any elements needing them and actually add the styles inline. These styles could then be targeted and the style attribute stripped before injected the code into the `<code>` block. This may however leave redundant wrapping `<divs>`. This appraoch also risk inconsistencies in how example styling is applied.

**Comment by yaili** [comment]
Couldn't we just use the p-card class to demonstrate, and mention in the description?
