### ISSUE TITLE
Why is there so much top/bottom padding in the example code blocks?

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#952]
Can we please remove that?

E.g. https://docs.vanillaframework.io/en/base/typography

**Comment by barrymcgee** [comment]
This is a bug with https://github.com/canonical-webteam/example-js - I'll raise an issue there and keep this for reference.

**Comment by barrymcgee** [comment]
Issue raised here: https://github.com/canonical-webteam/example-js/issues/14

**Comment by yaili** [comment]
OK, you can close this one if you want. Thanks.
