### ISSUE TITLE
Should there be 2 folders called settings in docs?

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#953]
If you go to https://github.com/vanilla-framework/vanilla-framework/tree/develop/docs

There is a folder called settings and if you go into "en" there is another folder called settings.

Is this correct? @barrymcgee @anthonydillon

**Comment by barrymcgee** [comment]
No - that's incorrect - good spot!

PR to correct here: https://github.com/vanilla-framework/vanilla-framework/pull/954
