### ISSUE TITLE
Add p-strip--light

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#966]
## Is this a proposal or an amendment?

- Proposal

## Context

In Vanilla, we currently have `p-strip` (#f7f7f7) and `p-strip--dark` (#111). But in a lot of cases we need a strip that is white.

Therefore, I am proposing that we add `p-strip--light` which has a background-color of `$color-x-light`.

**Comment by yaili** [comment]
In theory there should already be a strip light already which is light grey: https://github.com/ubuntudesign/vanilla-design/tree/master/Strip

Maybe we'd need to change the names.

**Comment by anthonydillon** [comment]
@yaili are you saying we should convert `p-strip` to be white and add `p-strip--light` which will be light grey?

**Comment by barrymcgee** [comment]
@anthonydillon This already exists exactly as you describe, just one shade out?

![screen shot 2017-03-22 at 13 50 20](https://cloud.githubusercontent.com/assets/505570/24200956/915e374e-0f06-11e7-8e60-3b48ce5df544.png)

**Comment by anthonydillon** [comment]
I am suggesting we change `$colour-light` to `$color-x-light`

**Comment by yaili** [comment]
So the proposal is we have the option to have strips that are:

- transparent (default)
- white
- light grey
- dark grey

I think that sounds OK, but I don't know about names. Is it confusing that the strip--light makes the background x-light and not light?

**Comment by anthonydillon** [comment]
Personally, I consider strip--light to be white and strip--dark to be close
to black when developing sites. If the default strip is transparent then
that works too. I am not sure what would be a good name for the light-grey.
Or even if it's required for Vanilla.

I guess my proposal is that we change the background of the body to
light-grey. Therefore, `p-strip` would be light-grey and then we have light
and dark to apply exactly that.

I don't think it's a good idea to closely couple the naming of strips to
colour names as they may change and would result in extra maintenance.

**Comment by barrymcgee** [comment]
I don't think we should be prescribing a background colour on the body element. If you need a strip to be white, why isn't a transparent strip not white by default?

**Comment by anthonydillon** [comment]
I seems odd for `p-strip` to be lighter then `p-strip--light`.

**Comment by barrymcgee** [comment]
But it isn't - `.p-strip` is transparent?

**Comment by anthonydillon** [comment]
As the background of the body is white. The resulting background of
`p-strip` is also white because of its transparency. Where as,
`p-strip--light` is light grey.

We therefore effectivity have:
- `p-strip`: white
- `p-strip--light`: light grey
- `p-strip--dark`: dark grey

**Comment by barrymcgee** [comment]
...and if someone decides to style their body background, either in theme or locally, the default strip will also appear as that color.

Exactly, just as I'd expect.

**Comment by yaili** [comment]
So is this the conclusion?

- p-strip: transparent (inherits body background, which by default is white in Vanilla)
- p-strip--light: $color-light
- p-strip--dark: $color-dark

**Comment by anthonydillon** [comment]
Yeah that's fine. I still find it weird naming but I understand why it's
like that.
