### ISSUE TITLE
ARIA navigation update

### ISSUE THREAD

**Issue by richmccartney** [vanilla-framework/vanilla-framework#971]
Here is a proposed option for making the navigation far more accessible. After speaking to @anthonydillon I've re-written the navigation in a codepen which we can use with JS to manipulate the ARIA controls to hide / show and display the current page.

https://codepen.io/anon/pen/evrwRB

**Comment by barrymcgee** [comment]
@richmccartney Issues shouldn't be triaged until they have been validated in the Working Group.

**Comment by anthonydillon** [comment]
I asked Rich to triage it as it's an issue that we don't have an accessible navigation. Not all issues need to be proposals.

**Comment by barrymcgee** [comment]
@anthonydillon Well, if it has the label 'WG: Proposal', I can only assume it's a proposal.
