### ISSUE TITLE
Button styles do not match the spec

### ISSUE THREAD

**Issue by spencerbygraves** [vanilla-framework/vanilla-framework#976]
**Bug**

Go here - https://docs.vanillaframework.io/en/patterns/buttons

- Neutral button has the wrong hover state
- Negative button is displayed as a neutral button
- Inline button has the wrong default and hover state. I assume this should be using the neutral styling

I'm including the spec again here:
![image](https://cloud.githubusercontent.com/assets/9105999/24399580/238390f4-13a5-11e7-9443-b1c5ce8a1d27.png)

**Comment by barrymcgee** [comment]
@spencerbygraves 

- The Neutral button background color changes to `#f7f7f7` on hover which is correct as per the spec as far as I can see?

- Negative showing Neutral - good catch, i've now corrected that.

- Inline button refers moreso to its behavior than how it looks. If you place any button after a `<span>`, it will sit inline. This is for use with banner CTAs.
