### ISSUE TITLE
Change notification name from warning to caution

### ISSUE THREAD

**Issue by spencerbygraves** [vanilla-framework/vanilla-framework#979]
# 2. Pattern proposal/amendment

##Amendment: .p-notification--warning

https://docs.vanillaframework.io/en/patterns/notification

We currently have the class names - Note, Positive, Warning, Negative. The class names aren't always the labels shown to the user.

The docs team want to use - Info, Tip, Note, Caution, Warning for admonitions in the docs theme. These will be the labels shown to the user.

After speaking to @nottrobin, the proposal is to update Warning to Caution in Vanilla Framework to avoid confusion in our class names and the way they are visually represented.

**Comment by yaili** [comment]
- We will change the name of warning to caution in Vanilla
- We will deprecate warning
