### ISSUE TITLE
[Proposal] We are polluting the global namespace with mixins

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#985]
I am not sure of a solution for this but I wanted to highlight that, by moving mixins out of the patterns we may cause naming clashes with themes or local styling.

**Comment by anthonydillon** [comment]
We should namespace the same as we do for patterns.

**Comment by yaili** [comment]
@anthonydillon what's the priority level of this issue?

**Comment by anthonydillon** [comment]
High, as this is going to hurt us sooner or later if not fixed.

**Comment by anthonydillon** [comment]
As part of this work we should replace mixins with placeholders were we can to reduce the size of the code base.

**Comment by yaili** [comment]
@anthonydillon could we move this issue to one of the themes migration epics? otherwise we won't be able to close this epic any time soon…

**Comment by anthonydillon** [comment]
Removed from the epic and can be picked up once we have a single code base.
