### ISSUE TITLE
Add info as a notification style

### ISSUE THREAD

**Issue by spencerbygraves** [vanilla-framework/vanilla-framework#987]
# Pattern proposal

The docs team have requested an info admonition style and I think it might be a useful addition to Vanilla. It's coincidentally come up in some new juju designs.

![image](https://cloud.githubusercontent.com/assets/9105999/24500439/4ccd56c2-153d-11e7-91d1-95f11b5b2a92.png)

https://docs.vanillaframework.io/en/patterns/notification

**Comment by anthonydillon** [comment]
:+1:

**Comment by yaili** [comment]
This issue was moved to ubuntudesign/vanilla-design#17
