### ISSUE TITLE
p-button--brand link color strange

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-framework#991]
# 1. Bug template

## Process

*using - p-button--brand with a $color-brand set to ubuntu orange, I get a light blue button that is hard to see.

## Expected result

* I would expect nearly white for color

## Current result

* currently the inverse of Ubuntu orange is blue
* this should be configurable or forced to color-x-light or color-x-dark based on color-brand
* also, I attempted to copy the mixin to my local scss and overwrite, but that didn't appear to work.

![image](https://cloud.githubusercontent.com/assets/441217/24602260/f11ed930-1853-11e7-80b2-a0ece196df1f.png)

## Screenshot

![image](https://cloud.githubusercontent.com/assets/441217/24602228/d549f15e-1853-11e7-8488-81c855fe3b6f.png)

**Comment by yaili** [comment]
- text in button brand should be color-x-light or color-dark, depending on brand colour
- define implementation details later

**Comment by richmccartney** [comment]
Suggest using this then to set dark or light colour based on background.

```
@function set-text-color($color) {
  @if (lightness($color) > 50) {
    @return #000000; // Lighter backgorund, return dark color
  } @else {
    @return #ffffff; // Darker background, return light color
  }
}

.button {
  background: $brand-color;
  color: set-text-color($brand-color);
}
```

[Demo](http://www.sassmeister.com/gist/3eac29579d217cfdda6942144047815a)

/cc @pmahnke @anthonydillon

**Comment by anthonydillon** [comment]
Yep that is what we need to do. I think we have a mixin for this in Vanilla
already. If not we had one.

**Comment by richmccartney** [comment]
@anthonydillon Just looking through VF thats a no, this function utility would need to be created.
